moonbitlang/core

array/array.mbt
assertion/assertion.mbt
list/list.mbt
option/option.mbt
ref/ref.mbt

I noticed that #24 #25 #26 have used the default formatting feature of the Moon tool. In order to ensure that the community code contributions have the same format for merging, this PR has formatted all the code.

style: format

---

assertion/assertion.mbt

Unfortunately, it's not yet easy to write a test to cover this due to the lack of `@string` capabilities.

Fix error message of assert_ne() to use `!=`

---

assertion/assertion.mbt

Slightly more meaningful tests in the `@assertion` package.

Fix tests in @assertion

---

array/array.mbt
assertion/assertion.mbt

We should probably introduce a `!==` operator ... ?

Add assert_is() and assert_is_not()

---

list/list.mbt

`Some(a, b)` seems not to be a valid syntax with the latest moonbit version.
```sh
moon 0.1.0 (73a0162 2024-03-11)
```

fix: tuple with some

---

result/result.mbt

Similar to `Option`, the following functions are included.
- map
- map_err
- err
- ok
- is_err
- is_ok
- or
- or_else
- flatten
- bind
- fold
- to_option

feat: basic operations for result

---

vec/moon.pkg.json
vec/vec.mbt

- Generalize the realloc operation in `push` to a `realloc` function.
- Add missing examples and test cases for some methods.
- Add more useful utils for `Vec`: append, iter, iteri, clear, map, mapi, is_empty, reverse, split_at, contains, starts_with, ends_with, search, swap, sort, remove, retain, resize, insert, fill, flatten, repeat, join.

feat: vector utils and modification.

---

list/list.mbt
stack/moon.pkg.json
stack/stack.mbt

In this PR I implemented a Stack based on the existing List in the standard library.

Add a list-based stack implementation

---

map/map.mbt
map/moon.pkg.json

This PR provides some basic operations for map, including `from_array`, `insert`, `remove`, `lookup`, and `member`.

add Map[K,V], based on size balanced binary tree.

---

immutable_set/immutable_set.mbt
immutable_set/moon.pkg.json

> When creating this PR, I found that the work of immutable_set seems to partially overlap with #53 
This PR implements a set data structure without side effects based on a balanced binary tree, this means the add and find value take time logarithmic in the size of the set.

Add balanced binary tree based immutable_set implementation

---

array/array.mbt
array/sort.mbt

This PR adds the following methods to Array:
- `pub fn sort[T : Compare](self : Array[T])`
- `pub fn sort_by_key[T, K : Compare](self : Array[T], map : (T) -> K)`
- `pub fn sort_by[T](self : Array[T], cmp : (T, T) -> Int)`
- `pub fn reverse[T](self : Array[T])`
- `pub fn swap[T](self : Array[T], i : Int, j : Int)`
The implementation uses a heuristic algorithm to choose the pivot value to avoid the worst case of quick sort, as Rust std does. It will also try to use bubble sort instead when the array is likely sorted or when it is small. The time complexity is O(n) if the array is sorted ascendingly or descendingly.

feat: array sort(quick sort), swap, reverse

---

math/algebraic.mbt
math/moon.pkg.json

Ported from [muts](https://gitee.com/fantix/muts/blob/v0.5.2/utils/math.mbt).

Add `@math.maximum()` and `@math.minimum()`

---

deque/README.md
deque/deque.mbt

As we mentioned in #69, this PR adds the pop function, which does not require a return value, and two utility functions.

feat: add more function to deque

---

immutable_hashmap/HAMT.mbt
immutable_hashmap/README.md
immutable_hashmap/bitset.mbt
immutable_hashmap/bucket.mbt
immutable_hashmap/moon.pkg.json
immutable_hashmap/sparse_array.mbt

add immutable hash map data structure, implemented using HAMT (Hash Array Mapped Trie). Most of the code come from the HAMT example on the playground, with some small tweaks and tests.

add immutable hash map data structure

---

array/moon.pkg.json
array/slice.mbt
array/sort.mbt

reafactor: refactor some function in sort and separate file for slice

---

immutable_hashmap/HAMT.mbt
immutable_hashmap/README.md
immutable_hashmap/bucket.mbt
immutable_hashmap/sparse_array.mbt

the HAMT implementation in #88 is missing a removal API. This PR adds the missing API

add removal API for immutable hash map

---

hashmap/README.md
hashmap/hashmap.mbt

- Caching the hash value in the entry to speeds up the lookup operation for non-integer keys.
- Tweak the hash calculation to let the higher 16 bits of the hash value participate in the calculation.

Tweak the hash map

---

array/array.mbt
deque/deque.mbt
immutable_set/immutable_set.mbt
vec/vec.mbt

#144 Since array/vec/deque's fold and iter are homologous implementations, modifications were made to all three structures.

refactor: iter_revi and fold_left/right

---

.gitignore
array/moon.pkg.json
assertion/moon.pkg.json
bool/moon.pkg.json
bytes/moon.pkg.json
char/moon.pkg.json
coverage/coverage.mbt
coverage/moon.pkg.json
deque/moon.pkg.json
double/moon.pkg.json
hashmap/moon.pkg.json
immutable_hashmap/moon.pkg.json
immutable_set/moon.pkg.json
int/moon.pkg.json
int64/moon.pkg.json
list/moon.pkg.json
map/moon.pkg.json
math/moon.pkg.json
num/moon.pkg.json
option/moon.pkg.json
priority_queue/moon.pkg.json
queue/moon.pkg.json
ref/moon.pkg.json
result/moon.pkg.json
stack/moon.pkg.json
string/moon.pkg.json
unit/moon.pkg.json
vec/moon.pkg.json

This PR allows for coverage testing for all core libraries, except for the coverage library itself.
This PR removes external dependencies for the coverage library, in order to add it as a dependency of all other dependencies.
Remaining questions:
- Can we insert the dependency to `moonbitlang/core/coverage` from the build system iff coverage is enabled, instead of right here?
- Add coverage output into CI in this PR?
Blocking issues:

Add coverage support for core libraries

---

array/sort_by.mbt
vec/moon.pkg.json
vec/slice.mbt
vec/sort.mbt
vec/sort_by.mbt
vec/vec.mbt

This PR implements the sort, sort_by, sort_by_key methods on Vec as Array does.
It also adopts the suggestions from https://github.com/moonbitlang/core/pull/72#discussion_r1537002612 to use `T:Compare` directly to enhance the performance by 20%.

feat: add sort, sort_by, sort_by_key to Vec

---

vec/vec.mbt

Vec::to_string() should have the same space spacing as Arrary::to_string to enhance readability.

chore: Vec::to_string

---

array/array.mbt

Note the CI failure actually means intrinsic works, since `x.iter` gets inlined, and coverage drops, this works like charm

mark array.iter as intrinsic

---

assertion/assertion.mbt
math/algebraic.mbt

The semantic of physic eq is not cross platform consistent. 
This PR address this issue: use struct with mutable field to force consistent semantic across platforms.

fix physic_eq related tests

---

builtin/traits.mbt

move builtin traits to core. These traits are previously hard coded in the compiler

move builtin traits to core

---

builtin/byte.mbt

Implement the Show, Eq, Compare traits for Byte. These method are implemented in `moonbitlang/core/builtin` to avoid cyclic dependencies.

implement Show, Eq, Compare traits for Byte

---

array/array.mbt
array/array.mbti

Hi all,
This parameter `f : (T, Int) -> U` of the function `mapi` is not consistent with the function `iteri`. This patch adjusts the position of the index in `f : (T, Int) -> U` in order to maintain the consistency.
Thanks for taking the time to review.
Best Regards,
-- Guoxiong

Adjust the position of the index parameter in Array::mapi

---

strconv/int.mbt
strconv/moon.pkg.json
string/string.mbt
string/string.mbti

And use `%string.substring` intrinsic to allow it compile to `s.slice(a, b)` in js target

Add substring method to string

---

array/array.mbt
array/array.mbti
array/moon.pkg.json
iter/consumers.mbt
iter/iter.mbti
iter/iter_test.mbt
iter/moon.pkg.json
iter/operators.mbt
iter/producers.mbt
iter/types.mbt

This PR add Iter package to core. Closes #294 
also added a Array::to_iter method.
Other `to_iter`s will be added later in separated PRs

iter: mvp version

---

_typos.toml
deque/deque.mbt
uuid/README.md
uuid/moon.pkg.json
uuid/ops.mbt
uuid/uuid.mbt
uuid/uuid.mbti
uuid/variant.mbt

This PR adds RFC 4122 UUID with basic functions.
Reference: https://github.com/python/cpython/blob/3.12/Lib/uuid.py
Depends on:

Add `@uuid` package

---

json5/internal_types.mbt
json5/lex_number.mbt
json5/lex_prop.mbt
json5/lex_string.mbt
json5/util.mbt

Note: This may made bad performance on wasm target. We will solve that if anyone care it.

json5: Use StringBuilder instead of Buffer to avoid expensive bytes operations

---

strconv/decimal.mbt

Wasm1 backend didn't implement bound check for accessing elements in string.... We will also fix the compiler.

fix out-of-bound access

---

ref/ref.mbt
ref/ref.mbti

remove Ref::incr, Ref::decr, they are not shorter to type and hard to optimize

---

hashset/hashset.mbt
hashset/hashset.mbti
hashset/hashset_test.mbt
hashset/moon.pkg.json
hashset/types.mbt

- Move all tests to a test file.
- Refactor with labeled enum.
- Add `as_iter` method.
- Clean up the package import.

Refactor HashSet with labeled enum and add `as_iter`

---

.github/workflows/check.yml

Added `--exit-code` to report exit code correctly
The CI should pass after #314 merged.

ci: fix format diff

---

devec/devec.mbt
devec/devec.mbti
devec/moon.pkg.json

As described in #50 , this attempted to `add as_iter for each data structure`

feat: Add Devec::as_iter method

---

bigint/bigint.mbt
bigint/bigint_test.mbt

a missing case: from_string("0") , which will cause RuntimeError if not fix

fix BigInt 'from_string' when input is 0

---

linked_hashmap/README.md
linked_hashmap/impl.mbt
linked_hashmap/impl_test.mbt
linked_hashmap/linked_hashmap.mbti
linked_hashmap/moon.pkg.json
linked_hashmap/types.mbt
linked_hashmap/utils.mbt

This PR adds a linked hash map that maintains the order of insertion while iterating. 
TODO:

Add LinkedHashMap

---

map/map.mbt
map/map.mbti
map/map_test.mbt
map/moon.pkg.json

following the guidelines of #402

remove list conversions from map

---

immutable_hashmap/HAMT.mbt
immutable_hashmap/immutable_hashmap.mbti
map/map.mbti
map/utils.mbt

add `op_get` for the lookup/find operations of maps, so that they can utilize the to-be-landed map pattern syntax.

add [op_get] for map and immutable hash map

---

int64/int64.mbt
int64/moon.pkg.json

see #409.
The old version of int64 hash will create a lot of collision when the hi and lo part of the int64 ranges over a similar range, and hence the performance degradation seen in #409.
One drawback of this approach is, it allocates a `Bytes` object every time the `hash` function is called, but as per my micro-benchmarks they doesn't seems to be affect much.
This patch copied the `Int64` to a `Bytes` then call xxhash internally.

use xxhash for int64

---

builtin/buffer.mbt
builtin/builtin.mbti
builtin/bytes.mbt
builtin/intrinsics.mbt
bytes/bytes.mbt
bytes/xxhash.mbt
char/char.mbt
double/ryu.mbt
strconv/decimal.mbt
string/string.mbt

MoonBit has introduced a `Byte` type, which represents an 8-bit unsigned integer. Currently we lacks the necessary primitives to convert between `Byte` and other basic types,  which limits its usability.
---
In this PR:
- add some intrinsics and arithmetic operations for byte: 
- `Int::to_byte` `Int64::to_byte` `Byte::to_int64` 
- refine Bytes APIs (`Bytes::make` `Bytes::op_set` `Bytes::op_get`) to use `Byte` type, update codebase to adapt this changes
- add new method `Buffer::write_byte` for `moonbitlang/x/encoding`
---
NOTE: This PR requires collaboration with the compiler as it involves intrinsics. For the sake of easy testing and review, the implementations of `Int::to_byte` and `Int64::to_byte` in `intrinsics.mbt` temporarily use `%identity`. **These implementations will be replaced …

[break change] tweak Bytes API, migrate to Byte type

---

bytes/bytes_test.mbt
bytes/xxhash.mbt
int64/int64.mbt
int64/xxhash.mbt
int64/xxhash_test.mbt

follow up of: https://github.com/moonbitlang/core/pull/414

feat: add int64 xxhash implementation

---

hashset/hashset.mbt
hashset/hashset_test.mbt
hashset/types.mbt

- Remove the `Empty` enum of the `Entry`
- Use `FixedArray`

Refactor HashSet

---

option/option.mbt
option/option.mbti

implement `map_or` and `map_or_else` method for `Option` type.
Close: #471

feat: impl `map_or` and `map_or_else`

---

assertion/assertion.mbt

This change is to help when error detected, vscode terminal can quickly navigate the location(whitespace makes the loc clickable). cc @lijunchen

whitespace to allow vscode navigate the error location quickly

---

builtin/linkedhashmap.mbt
builtin/linkedhashmap_test.mbt

- Add a ListNode array to eliminate circular references
- Remove abs()

Optimize LinkedHashMap

---

hashmap/hashmap.mbt

- simplify the remove operation
- simplify shift_back
- tweak

futher simplify remove and shift_back operations in hashmap

---

builtin/linkedhashmap.mbt

In this PR:
- Introduced a capacity_mask field, `capacity_mask = capacity - 1`, which is used extensively in the code
This should hopefully improve performance

tweak Map capacity calculation and masking logic

---

immut/list/README.md
immut/list/list.mbt
immut/list/list.mbti
immut/list/list_test.mbt
immut/list/moon.pkg.json

This package (`immut/list`) is essentially the same as the previously removed package `moonbitlang/core/list`. The only difference is that the `List` type is now defined within the package itself; it's no longer a special built-in type.
The built-in `List` type in the compiler is scheduled to be removed in the release next week.

add list package back to immut/list

---

bytes/bytes.mbt
bytes/bytes.mbti
bytes/bytes_test.mbt

Used in Unicode encoding (https://github.com/moonbitlang/x/commit/daa53ced0ca9ef3538064de41e80dae8bb730fee)
But Bytes itself should also mean byte array, so this may be confusing

feat: Add to_array method to Bytes

---

array/array_test.mbt
builtin/array.mbt
builtin/builtin.mbti

This PR make capacity of array no longer a guarantee.
With turning it to a hint, we can compile array to js native array without semantic inconsistent.

make capacity of array no longer a guarantee

---

builtin/array.mbt
builtin/arraycore.mbt
builtin/arrayview.mbt

This PR refactor "builtin/array.mbt" to "builtin/arraycore.mbt" and "builtin/array.mbt".
The file "builtin/arraycore.mbt" contains core primitives to implement an array. And "builtin/array.mbt" has zero knowledge about what's the underlying type of `Array`. 
This abstraction make it easier to introducing compiling array to js native array.
This PR also fix the memleak issue.

Refactor array and fix memleak issue

---

builtin/array.mbt
builtin/array_block.mbt
builtin/arraycore.mbt
builtin/builtin.mbti
builtin/test/array_test.mbt

Previous implementation has bug on `FixedArray[T]` while T is a ref type. This PR fixed it.
This PR also add a pub `Array::unsafe_blit_fixed` method.

Fix blit from fixed array

---

option/option.mbt
option/option.mbti

This new method allows an `Option` to be converted into an iterator, making it easier to use with `Iter::flat_map`.

feat: add Option::as_iter

---

immut/hashset/HAMT.mbt
immut/hashset/HAMT_test.mbt
immut/hashset/hashset.mbti
immut/list/list.mbt
immut/list/list.mbti
immut/list/list_test.mbt
immut/sorted_map/README.md
immut/sorted_map/map_test.mbt
immut/sorted_map/sorted_map.mbti
immut/sorted_map/utils.mbt
immut/sorted_set/README.md
immut/sorted_set/immutable_set.mbt
immut/sorted_set/immutable_set_test.mbt
immut/sorted_set/sorted_set.mbti
sorted_set/README.md

Rename the function `contain`/`member` in `immut/list`, `sorted_set`, `sorted_map` to `contains` to align with other collections.

rename `contain`/`member` to `contains`

---

immut/sorted_set/README.md
immut/sorted_set/immutable_set.mbt
immut/sorted_set/immutable_set_test.mbt
immut/sorted_set/sorted_set.mbti

Both `forall/exists` and `all/any` make sense to me, but `all/any` are shorter. So in this PR, the `forall/exists` in sorted_set will be renamed to align with other collections.

rename `forall/exists` to `all/any` in sorted_set

---

devec/devec.mbt
devec/test/test.mbt

- Option::Some is a bad user experience, we would like `Some(x)` to work out of box
- whitebox test is a bad idea, most whitebox test needs to be adapted to use as blackbox tests, for example T::with_capacity has to be adapted use `@pkg.T::with_capacity` or `@pkg.with_capacity`. To guide people to write blackbox tests, we should make it as easy as possible

continue tidy up devec

---

array/array.mbt
array/fixedarray.mbt
builtin/builtin.mbti
builtin/iter.mbt
builtin/iter_test.mbt
builtin/linked_hash_map.mbt
devec/devec.mbt
hashmap/utils.mbt
hashset/hashset.mbt
immut/array/array.mbt
immut/hashmap/bucket.mbt
immut/hashset/bucket.mbt
immut/list/list.mbt
immut/priority_queue/priority_queue.mbt
immut/sorted_map/utils.mbt
priority_queue/priority_queue.mbt
queue/queue.mbt
string/string.mbt

This is part 2 of https://github.com/moonbitlang/core/pull/538
Which added explicit iter result support, and removed helper function `iter_result_of_bool` and `bool_of_iter_result`

Explicit iter result

---

builtin/builtin.mbti
builtin/linked_hash_map.mbt
builtin/linked_hash_map_test.mbt

feat: add Map::set_default

---

sorted_map/map.mbt
sorted_map/map_test.mbt
sorted_map/moon.pkg.json
sorted_map/sorted_map.mbti
sorted_map/types.mbt
sorted_map/utils.mbt

This PR adds a sorted map package, contains a sorted map based on an iterative AVL tree.
Closes #497

Add mutable sorted map

---

builtin/builtin.mbti
builtin/console.mbt
builtin/intrinsics.mbt
coverage/coverage.mbt
coverage/coverage.mbti
coverage/coverage_test.mbt

Only expose println in core

---

builtin/console.mbt

This MR changes `println` to use `%println` primitive

use %println primitive

---

array/fixedarray_sort.mbt
array/view_test.mbt
builtin/arrayview_test.mbt
immut/sorted_set/immutable_set_test.mbt
json/lex_main.mbt
json/lex_misc.mbt
json/lex_number.mbt
json/lex_string.mbt
string/string.mbt

The syntax for array slice has been changed from `arr[b..e]` to `arr[b:e]`, and the old syntax will be removed shortly. This PR ports core to the new syntax. The old syntax will be removed shortly.
There are also some formatter change in the most recent compiler release. Since the formatter will now format the old `arr[b..e]` to the new `arr[b:e]`, these changes must be shipped together.

adapt new array slice syntax

---

builtin/builtin.mbti
builtin/int64.js.mbt
builtin/int64.wasm-gc.mbt
builtin/int64.wasm.mbt
builtin/intrinsics.mbt
builtin/intrinsics_test.mbt

add `land`,`lor`,`lxor`,`lnot`,`lsl`,`lsr` methods to `UInt`/`UInt64` types

add bitwise operations for UInt/UInt64

---

array/array.mbt
array/array.mbti
array/array_test.mbt

This PR introduces the `push_iter` method to the `array`, allowing users to append all elements from an iterator to the end of an array.
- Implemented the `push_iter` method in `array/array.mbt`.
- The method iterates over each element provided by the iterator and appends it to the array using the built-in `push` method.
```moonbit
let u = [1, 2, 3]
let v = [4, 5, 6]
u.push_iter(v.iter())
```

add `push_iter` method to array

---

array/fixedarray_sort.mbt
builtin/buffer.mbt
builtin/builtin.mbti
double/ryu.mbt
rational/rational.mbt
strconv/decimal.mbt
strconv/int.mbt
strconv/number.mbt

There are some format diff caused by the changed behavior of moonfmt.
@qazxcdswe123

remove deprecated Buffer::make

---

builtin/builtin.mbti
builtin/int64.js.mbt
builtin/int64.wasm-gc.mbt
builtin/int64.wasm.mbt
builtin/intrinsics_wbtest.mbt

cc @Yoorkin, I couldn't find a proper intrinsic in wasm. The closest I found is `i32.wrap_i64` and it doesn't seem correct?

feat: add uint64 to uint

---

builtin/linked_hash_map.mbt

Fix an error caused by not adjusting the linked list during `shift_back`

fix linked hash map

---

bool/bool.mbt
bool/bool.mbti
builtin/builtin.mbti
builtin/byte.mbt
builtin/hasher.mbt
builtin/hasher_test.mbt
builtin/linked_hash_map_wbtest.mbt
builtin/traits.mbt
bytes/bytes.mbti
bytes/xxhash.mbt
char/char.mbt
char/char.mbti
double/double.mbt
double/double.mbti
hashmap/hashmap_wbtest.mbt
hashset/hashset_wbtest.mbt
immut/hashset/HAMT_wbtest.mbt
int/int.mbt
int/int.mbti
int64/int64.mbti
int64/xxhash.mbt
string/string.mbt
string/string.mbti
unit/unit.mbt
unit/unit.mbti

This PR changes the hash trait to follow the first step of #689 .
- add `hash_combine(Self, Hasher)` to hash trait.
- add `hash_combine` method to types that should impl the hash trait.
- adjust some tests.

change hash trait

---

builtin/linked_hash_map.mbt
builtin/linked_hash_map_wbtest.mbt
builtin/traits.mbt
deque/deque.mbt
hashmap/hashmap.mbti
hashmap/utils.mbt
hashset/hashset.mbt
immut/array/array.mbt
immut/array/array_test.mbt
immut/hashmap/HAMT.mbt
immut/hashmap/HAMT_test.mbt
immut/hashset/HAMT.mbt
immut/hashset/HAMT_test.mbt
immut/sorted_map/sorted_map.mbti
immut/sorted_map/utils.mbt
immut/sorted_set/immutable_set.mbt
immut/sorted_set/immutable_set_test.mbt
immut/sorted_set/sorted_set.mbti
json/json_test.mbt
json/parse_test.mbt
queue/queue.mbt
queue/queue_test.mbt
sorted_map/sorted_map.mbti
sorted_map/utils.mbt
sorted_set/set.mbt
sorted_set/set_test.mbt

This PR:
- add missing `Show` impl to `sorted_map` and `immut/sorted_map`
- unify the convention of `Show` impl for collections to `@pkg.of([ ... ])`
- fix some bugs in `Show` impls, for example, the `Show` impl for linked hashmap in `builtin` is missing a left brace
- improve various `Show` impls by simplifying the code and avoiding intermediate allocation

fix/improve/add missing `Show` impl

---

coverage/coverage.mbt

The `fn Trait::method(...)` syntax for implementing traits explicitly is deprecated in favor of the `impl Trait for Type with method(...)` syntax, and may be removed soon. This PR cleanup usage of the old syntax in core

cleanup old extension method syntax in core

---

array/array.mbt
array/array.mbti
array/array_test.mbt
array/fixedarray.mbt
immut/array/array.mbt
immut/array/array.mbti
immut/array/array_test.mbt

close #582
- core/array
- mark `Array::new_with_index` `FixedArray::new(Int, ()->T)` `FixedArray::new_with_index` deprecated
- add `FixedArray::makei` to align with other collections
- core/immut/array
- remove `empty()` `new[A](Int,A)` `new_with_index[A](Int, (Int)->A)`
- add `make[A](Int,A)` `makei[A](Int, (Int)->A)` `new[A]()`

make new/make function consistent

---

hashmap/pattern_test.mbt
immut/hashmap/pattern_test.mbt

The semantic of map pattern will receive a breaking change recently, the semantic of  `{ "key": value }` is changed to match only cases where `"key"` exists, and `value` matches the actual content of `"key"`. The old semantic of matching no matter `"key"` exists or not becomes `"key"? : value`.
This PR adapt usage of map pattern in core to the new semantic.

port to new map pattern semantic

---

builtin/linked_hash_map_test.mbt

Desugaring of array spread `[ a, ..xs, b ]` requires `iter` method and `push_iter` method of `Array`, which are in the `array` package, not `builtin`. So using array spread in `builtin` is not stable w.r.t. location of API & desugaring of array spread.
This PR removes unnecessary usage of array spread in builtin package.

get rid of array spread in builtin

---

builtin/hasher.mbt

Currently, such types have different behavior with the default:
1. Bool
2. Byte
3. Int
4. Char
5. Double
6. Unit

Remove impl Hash for String with hash which is the same as the default

---

builtin/iter.mbt
builtin/iter_test.mbt

- avoid some unncessary closure in [Iter::new]
- reduce the indentation level of code by removing some unnecessary use of matrix function
- deprecate the [Iter::tap] method: we now have native cascade operator

various misc improvements on the [Iter] data type:

---

builtin/builtin.mbti
builtin/hasher.mbt
builtin/tuple_hash.mbt

add `Hash` implementation to builtin numeric types, `Bytes`, `Bool`, `Unit`, `Option`, `Result` and tuples

add [Hash] implementation for some builtin types

---

builtin/builtin.mbti
builtin/console.mbt
builtin/show.mbt
builtin/string_test.mbt

Currently, `Show::to_string` instance for `String` returns the string itself. Escaping functionality of `String` is implemented in `Show::output`, but `Show::output` is not intended for direct use. This PR adds a `String::escape` method, which returns a valid MoonBit syntax representation of a string.
While testing the API I fix a small bug in `Show::output` implementation for `String`. It fail to escape some non-printable characters.

add method [String::escape] that escapes a string using MoonBit syntax

---

builtin/bigint.mbt
builtin/builtin.mbti

Do not deprecate lsl lsr for bigint 

---

option/option.mbt
option/option.mbti
result/result.mbt
result/result.mbti

Soon, only `Error` types will be allowed to be raised. For polymorphic error handling functions, their error type parameter must be annotated with the `Error` bound.
This PR prepare core for this upcoming language change, add [Error] bound to polymorphic error handling APIs, and adapt codes that raises non-error type.

make sure only error type can be raised

---

array/array_test.mbt
builtin/builtin.mbti
builtin/hasher.mbt
builtin/hasher_test.mbt
builtin/iter_test.mbt
builtin/json.mbt
builtin/linked_hash_map_wbtest.mbt
builtin/tuple_hash.mbt
bytes/xxhash.mbt
double/double.mbt
double/log.mbt
double/ryu.mbt
double/ryu_test.mbt
hashmap/hashmap_test.mbt
immut/hashmap/HAMT_test.mbt
immut/hashmap/bucket.mbt
immut/hashset/bucket.mbt
immut/priority_queue/priority_queue_test.mbt
immut/sorted_map/map.mbt
immut/sorted_map/map_test.mbt
immut/sorted_set/generic.mbt
json/json.mbti
json/json_test.mbt
json/types.mbt
option/option.mbt
random/random.mbt
rational/rational.mbt
strconv/decimal.mbt
string/string.mbt
string/string_test.mbt

Move the `@json.JsonValue` type to builtin package, so that:
- it can be referenced more easily with `Json` directly
- builtin types can have a `.to_json` method
Note that we don't want to pull all the json parsing and processing stuff into builtin, just the type definition. To make this work some compiler special treatment is needed, so that `@json` can define methods for the `Json` type. So this PR need compiler adoption before merging.
A type alias is placed in the `@json` package, so this PR is backward compatible. All existing code that make use of `@json.JsonValue` will continue to work.

move json type to builtin

---

builtin/builtin.mbti
builtin/linked_hash_map.mbt
builtin/show.mbt
builtin/traits.mbt
builtin/tuple_show.mbt
hashmap/utils.mbt
immut/hashmap/HAMT.mbt
sorted_map/utils.mbt

- add `Logger::write_object` method to trait object type `Logger`
- using this method, many `Show` implementation can be simplified using cascade method call

simplify code with method for trait object & cascade operator

---

builtin/builtin.mbti
builtin/json.mbt
json/to_json_test.mbt

- add `to_json` method to builtin types
- add `ToJson` trait, so that the compiler can automatically `derive(ToJson)` in the future

add [ToJson] trait & [to_json] method for builtin types

---

builtin/builtin.mbti
builtin/iter.mbt
builtin/iter_test.mbt

Introduces `map_while`, an iterator that maps elements and continues while a predicate returns `Some(_)`, stopping at the first `None`. 
This method simplifies the process by removing the need to call `Option::unwrap`.

feat: add `Iter::map_while`

---

builtin/builtin.mbti
builtin/int64.js.mbt
builtin/int64.wasm-gc.mbt
builtin/int64.wasm.mbt
builtin/intrinsics_test.mbt

~~In the intrinsic test, wasm/wasmgc and js yields different result. And the correct one should be 1.0~~
~~Coule this be a issue in wasm or ryu?~~

feat: add u64 to f64 intrinsic

---

bool/bool.mbt
bool/bool.mbti
bool/bool_test.mbt
int/int.mbt
int/int.mbti
int/int_test.mbt
int64/int64.mbt
int64/int64.mbti
int64/int64_test.mbt
rational/rational.mbt

- add `max` `min` constants to `int` `int64` packages, mark `max_value()` `min_value()` functions deprecated
- remove unused Boolean trait and methods of Num trait

clean up functions in bool, int, int64 packages

---

builtin/show.mbt
bytes/bytes_test.mbt

#291
- Change the behavior of Show trait implementation for Bytes
> We should add bytes literal syntax, e.g, b"xx.." and use make Byte::to_string confirm to the format
Now it will print something like `b"\x00\x00..."` when inspecting a Bytes.
- This pr does not change any API.

refine behavior of Show::to_string(Bytes)

---

string/string.mbt
string/string.mbti
string/string_test.mbt

I have added a `reverse()` method to `String`. 
I think the reverse() method has some good points. First, it makes the String class more useful and easier to work with. It makes reversing a string simple, which is needed often in programming.   
I have tested it in my computer. I can run correctly.
And you can using it like this:
```
fn main {
let x: String = "hello world";
println(x.reverse())
}
```
It will display `dlrow olleh`

add: a new method String::rev()

---

double/double.mbt
double/double.mbti
double/exp_test.mbt
double/log.mbt
json/json_test.mbt
math/trigonometric.mbt
math/trigonometric_test.mbt
rational/rational_test.mbt
strconv/double.mbt
strconv/number.mbt

Fix #885
- add double constants, rename `min_normal` to `min_positive`, and let `min` equal to `-max`.
- deprecate some functions that return constants.

add double constants

---

array/array_test.mbt
builtin/array.mbt
builtin/array_test.mbt
builtin/builtin.mbti
deque/deque.mbt
deque/deque.mbti
deque/deque_test.mbt
immut/list/list.mbt
immut/list/list.mbti
immut/list/list_test.mbt
immut/priority_queue/priority_queue.mbt
immut/priority_queue/priority_queue.mbti
immut/priority_queue/priority_queue_test.mbt
priority_queue/priority_queue.mbt
priority_queue/priority_queue.mbti
priority_queue/priority_queue_test.mbt
queue/queue.mbt
queue/queue.mbti
queue/queue_test.mbt
sorted_map/map.mbt
sorted_set/set.mbt

- Mark `x_exn` functions as deprecated (e.g., `pop_exn`, `peek_exn`, `nth_exn`, `head_exn`), and add new `unsafe_x` functions.
- `immut/list`
- Correct the behaviors of the `take` and `drop` functions in `immut/list`.
The result of `@list.of([1,2,3]).take(5)` should be `@list.of([1,2,3])`, but it currently causes a program abort when the index is out of bounds. The `drop` function also has this issue.
- Change the return type of `maximum`, `minimum`, and `zip` to `Option[...]`.

rename functions `x_exn` to `unsafe_x`

---

builtin/bigint.mbt
builtin/bigint_wbtest.mbt

- `neg` didn't take into account of zero
- `from_int` broke invariant that `limbs[i]` < `radix`

fix: bigint bugs

---

builtin/bigint.mbt
builtin/builtin.mbti
builtin/console.mbt
builtin/hasher.mbt
builtin/intrinsics.mbt
builtin/intrinsics_test.mbt
double/exp.wasm-gc.mbt
double/internal/ryu/ryu.mbt
random/internal/random_source/random_source_chacha.mbt
random/random.mbt
random/splitmix/random.mbt
uint/uint.mbt

the latter is more descriptive, deprecate the former
cc @Yoorkin @qazxcdswe123

Change UInt::to_int to  UInt::reinterpret_as_int

---

builtin/bigint.mbt
builtin/bigint_wbtest.mbt

Div is not correct when having two numbers of the same `len` because the normalization step was not performed correctly.

fix: bigint bug

---

builtin/bigint.mbt
builtin/bigint_wbtest.mbt
builtin/builtin.mbti

Based on #935 
- Add `pow` which may perform `mod` at the same time
- Add `from_octets` and `to_octets` to convert from/to octet string (`Bytes`), which can be useful in many scenarios

feat: add utils for bigint

---

builtin/builtin.mbti
builtin/iter.mbt
builtin/iter2.mbt
builtin/iter_test.mbt

I've implemented `to_string` and `to_array` functions and the `Show` trait for `Iter2`.

Add to_array and to_string funtions for Iter2

---

string/string.mbt
string/string.mbti
string/string_test.mbt

This PR adds 2 string methods that I have been copy pasting in a few projects. It would be nice if moonbit core library supports them out of the box. 
1. pad_left - given a total_width and a padding_char, pads the left of the string.
2. pad_right - given a total_width and a padding_char, pads the right of the string.
With regards to implementation details, I have used the buffer approach rather than the string concatenation approach. However, I can be convinced to use the string concatenation approach since string allocations are minimal for our use case.

Add String.pad_left and String.pad_right

---

string/string.mbt
string/string.mbti
string/string_test.mbt

Follow up of #1002
- **tweak names to align js calling convention**
- **use pad/trim_start/end, deprecate pad/trim_left,right**
- **the string position is incorrect for such unicodes**
- **info**
cc @bikallem

tweak pad_start/end and deprecate pad_left/right

---

builtin/json.mbt
json/from_json.mbt
json/from_json_test.mbt
json/to_json_test.mbt

mainly for `Option[Option[T]]`
> for T? inside record, e.g,
struct Hello[T] {
x : T?
y : Int
}
when x is None, it does not show up in JSON, when x is Some(val), only val shows up
This needs to be changed in compiler

fix: proper option fromjson

---

array/array.mbt
array/array.mbti
array/array_test.mbt
builtin/builtin.mbti
string/string.mbt
string/string.mbti
string/string_test.mbt

- add `concat`, `from_array` methods for String
- remove `Array::join`
The behavior of Array::join is not the same as javascript, because the `Show` trait is used to logging or debugging, the output result is always remains "as is".  e.g.  in moonbit,`["abc","def"].join() == "\"abc\"\"def\""`. So I prefer to remove this API and use `String::join` instead.
fix #989

add `concat`, `from_array` methods for String

---

builtin/builtin.mbti
builtin/hasher.mbt

There are duplicated `impl` of `Hash::hash_combine` for types `Bytes`, `Int64`, `Double`, `Bool` and `Unit`, in builtin package and their own package. This PR removes duplicated `impl` in builtin package.
The compiler should be responsible for report error on such duplicated `impl`, so there is also a compiler bug involved here that should be fixed.

remove duplicated `impl` in builtin and other packages

---

immut/list/list.mbt
immut/list/list.mbti
immut/list/list_test.mbt

This PR adds the `@list.rev_concat()` function (namely `List.rev_append` from OCaml), making it possible to do the `ls.rev().rev_concat(rs)` trick in Moonbit.
Also, `@list.rev()` is now considered as a special case of `@list.rev_concat()`.

add `rev_concat()` for `immut/list`

---

.github/workflows/check.yml

There was a bug in `moon_cove_report` where the commandline interface
differs with the actual parser implementation. Namely, additional string
arguments were ignored when parsing the args, while in the docs they
should represent input coverage source metadata. The fix made the parser
consistent with the interface, but broke the CI that mistakenly had an
additional `summary` arg in the commandline in here and other projects,
which was ignored in previous versions, but would trigger an error in
the current version.

ci: Fix coverage command after bugfix in `moon_cove_report`

---

builtin/builtin.mbti
math/algebraic_test.mbt
quickcheck/splitmix/random.mbt
strconv/number.mbt
strconv/strconv.mbti
strconv/string_slice.mbt

While improving MoonBit's unused warning, I found several struct field with unused mutability & some types that should be made private on core. This PR fixes these unused things

fix some unused mutability & make some type private

---

json/to_json_test.mbt

The optional field in the record is encoded differently in the bleeding edge, this PR commentted that test temporarily.
We will bring back once we updated cc @qazxcdswe123

bring back bleeding ci

---

NOTICE
float/float.mbti
float/log.mbt
float/log_test.mbt

This PR add log function to Float

add Float::log

---

NOTICE
float/exp.mbt
float/exp_test.mbt
float/float.mbti
float/moon.pkg.json

This PR adds `Float::exp`. The code is basically transcribed from the musl libc.
https://git.musl-libc.org/cgit/musl/tree/src/math/expf.c

add `Float::exp`

---

NOTICE
math/exp.mbt
math/log.mbt
math/math.mbti

This pull request focuses on deprecating several mathematical functions in the `Double` type and moving their implementations to the `math` module. Key changes include marking functions as deprecated, adding new implementations, and updating tests accordingly.
Deprecation and Implementation Changes:
* [`double/double.mbti`](diffhunk://#diff-b5e29dc0857a725de75305a745ae9b4ec1532ed9ab6b94de17e5477feb6523d8L20-R20): Marked `exp`, `log10`, `log2`, `min_normal`, and `nan` as deprecated. [[1]](diffhunk://#diff-b5e29dc0857a725de75305a745ae9b4ec1532ed9ab6b94de17e5477feb6523d8L20-R20) [[2]](diffhunk://#diff-b5e29dc0857a725de75305a745ae9b4ec1532ed9ab6b94de17e5477feb6523d8L30-R31)
* `double/exp_js.mbt` and `double/exp_nonjs.mbt`: Added deprecation alerts for `exp` and provided new implementations. …

Move `double` method to func in `math` 

---

builtin/array.mbt
builtin/array_test.mbt
builtin/builtin.mbti

For backward compatibility, this PR updates the documentation for `Array::dedup`, so that it shall not break any existing code that use this function. This PR also add another function (`Array::unique`) to implement the originally proposed functionality, i.e. de-duplication of consecutive repeated elements.
cc @Demonmasterlqx
close #1061 
| Language | Consecutive | Non-consecutive |
|----------|-------------|-----------------|
| C++      | [`unique`](https://en.cppreference.com/w/cpp/algorithm/unique) | N/A |
| Rust     | [`dedup`](https://docs.rs/itertools/latest/itertools/trait.Itertools.html#method.dedup) | [`unique`](https://docs.rs/itertools/latest/itertools/trait.Itertools.html#method.unique) |
| NumPy    | N/A | [`unique`](https://numpy.org/doc/2.0/reference/generated/numpy.unique.h …

add `Array::dedup_consecutive` for removing consecutive repeated elements in array

---

hashmap/hashmap_test.mbt
hashset/hashset_test.mbt

When experimenting with an improved version of unused warning in the MoonBit compiler, I discover some dead code in core. This PR removes these dead code

cleanup some dead code

---

builtin/deprecated.mbt
bytes/bytes_test.mbt
char/char.mbt
coverage/coverage.mbt
double/internal/ryu/ryu.mbt
immut/hashmap/bucket.mbt
immut/hashset/bucket.mbt
strconv/decimal.mbt
strconv/string_slice.mbt
string/string.mbt
test/test.mbt

This PR refactor all the usages of Buffer in core in favor of StringBuilder.
This PR is extracted from https://github.com/moonbitlang/core/pull/1084

refactor: use StringBuilder instead of Buffer

---

builtin/bigint.mbt
builtin/builtin.mbti
builtin/byte.mbt
builtin/int64_js.mbt
builtin/int64_nonjs.mbt
builtin/intrinsics.mbt
byte/byte.mbt
byte/byte.mbti

Per discussion with @bobzhang, we will only keep `op_shl` and `op_shr` for simplicity, and favor infix operator style `x >> y` over `x.op_shr(y)`.
After that, there is no need to bother with distinguishing API between logical right shift and arithmetic right shift for average user: all right shift operations perform division by powers of 2. For who want to use integer types as a bit vector, `UInt`/`UInt64` is recommended.
- deprecate functions like `lsl`, `lsr`, `asr`, `shl`, `shr` 
- remove `mod_u` and `div_u` in int64_js.mbt
previous PR #1089 #1088

clean up bitwise functions

---

builtin/array.mbt
builtin/arraycore_nonjs.mbt

This PR utilizes several new compiler intrinsics, `%array.{length,unsafe_get,get,unsafe_set,set}`. The unsafe variants have no bound check at all and may lead to arbitrary memory access, so they are kept private in `builtin`. The safe variants performs bound check on runtime and crashes on out of bound access. They will be inlined by the compiler in release mode for performance.
Since intrinsics are only utilized in release mode, so the use of unsafe operations won't make debug harder.
Previously many `Array` APIs in the core uses `arr.buffer()[index]` for unsafe get/set, but the `FixedArray` indexing still performs bound check at runtime. So these uses are replaced by `unsafe_get`/`unsafe_set` to maximize performance

add [Array::unsafe_get] and [Array::unsafe_set] & array intrinsic

---

builtin/builtin.mbti
builtin/console.mbt

We will support the Js-string-builtin proposal, so the legacy Js-string is removed.

deprecate Js_string

---

builtin/builtin.mbti
builtin/intrinsics.mbt
builtin/intrinsics_test.mbt

feat: add UInt::reinterpret_as_float()

---

immut/list/list.mbt
immut/list/list.mbti
immut/list/list_test.mbt
immut/list/moon.pkg.json
immut/sorted_map/moon.pkg.json
immut/sorted_map/sorted_map.mbti
immut/sorted_map/utils.mbt
immut/sorted_map/utils_test.mbt
immut/sorted_set/generic.mbt
immut/sorted_set/immutable_set.mbt
immut/sorted_set/immutable_set_test.mbt
immut/sorted_set/moon.pkg.json
immut/sorted_set/sorted_set.mbti
immut/sorted_set/types.mbt

This pull request introduces JSON (de)serialization functionality to various immutable data structures (`list`, `sorted_map`, and `sorted_set`). The changes include implementing the `(From|To)Json` traits for these structures, adding corresponding methods, and updating the test cases to validate the new functionality.
As previously discussed with @bobzhang.

feat: implement `(From|To)Json` for more `@immut/*.T` types

---

immut/list/list.mbt
immut/list/list.mbti
immut/list/list_test.mbt
immut/list/panic_test.mbt

This reverts commit b458397a37084b20792bc0c24ddb95c0d397550a.
Reintroduced `last` that returns `Option`

Revert "Defer last option breaking (#1114)"

---

char/moon.pkg.json
deque/moon.pkg.json
double/internal/ryu/moon.pkg.json
double/moon.pkg.json
error/moon.pkg.json
hashmap/moon.pkg.json
immut/array/moon.pkg.json
immut/hashset/moon.pkg.json
immut/list/moon.pkg.json
immut/priority_queue/moon.pkg.json
immut/sorted_map/moon.pkg.json
int64/moon.pkg.json
json/moon.pkg.json
option/moon.pkg.json
queue/moon.pkg.json
random/moon.pkg.json
rational/moon.pkg.json
ref/moon.pkg.json
result/moon.pkg.json
sorted_set/moon.pkg.json
strconv/moon.pkg.json
string/moon.pkg.json

This is not complete though. For example, when the type `Char` is used, the package `moonbitlang/core/char` will be considered used. But it's not true when all the things we need about the type `Char` can be found in `moonbitlang/core/builtin`.

remove unused import

---

immut/list/list.mbt
immut/list/list.mbti
immut/list/list_test.mbt

Mirrors OCaml's [`List.rev_map`](https://www.ocaml.org/manual/5.2/api/List.html#VALrev_map), which is a more efficient version of `List.map` (by being tail-recursive) at the cost of getting a reversed list.
The blog post [_OCaml List rev_map vs map_](https://www.thekerneltrip.com/ocaml/ocaml-list-map-vs-revmap/) gives a pretty accurate description of the rationale of this method.

feat: add `rev_map()` to `@immut/list`

---

builtin/builtin.mbti
builtin/iter.mbt
builtin/iter_test.mbt

Iter::map_option serves the same functionality as Array::map_option.

add Iter::map_option

---

builtin/bigint_deprecated.mbt
builtin/bigint_js.mbt
builtin/bigint_js_wbtest.mbt
builtin/bigint_nonjs.mbt
builtin/bigint_nonjs_wbtest.mbt
builtin/bigint_wbtest.mbt
builtin/moon.pkg.json

This MR split `bigint.mbt` into three files:
- `bigint_js.mbt`: Added js platform specific implementation 
- `bigint_nonjs.mbt`: Make previous implementation non-js platform specific 
- `bigint_deprecated.mbt`: Extracted from previous implementation and it is shared
This MR split `bigint_wbtest.mbt` into three parts:
- `bigint_wbtest.mbt`: Previous white-box tests
- `bigint_js_wbtest.mbt`: Redefine `check_len` function used in `bigint_wbtest.mbt` to make it do nothing
- `bigint_nonjs_wbtest.mbt`: Previous `check_len` function implementation and other tests depends on previous internal representation of BigInt.

align BigInt to JavaScript native bigint

---

immut/list/list.mbt
immut/list/list.mbti
immut/list/list_test.mbt

Mirrors OCaml's [`List.filter_map`](https://www.ocaml.org/manual/5.2/api/List.html#VALfilter_map).
* [`immut/list/list.mbt`](diffhunk://#diff-1b6611b3a18e093ea1e9aed64259213abe10161afbb5a32e5a62cfbbdbd945d2R502-R521): Added the `filter_map` function, which maps over the list and keeps all values for which the mapped result is `Some(value)`.
* [`immut/list/list.mbti`](diffhunk://#diff-9cf1552c7c627c956818a0169def34402ea101ed06b61603dd11125486637c52R34): Declared the `filter_map` function in the list type implementation.
* [`immut/list/list_test.mbt`](diffhunk://#diff-721bf2f9e4d9e52cab5b73c33c8a03e50af765acac1072730cc5c9ca2831c99fR208-R220): Added test cases for the `filter_map` function to validate its behavior with both non-empty and empty lists.

feat: add `filter_map()` to `@immut/list`

---

array/array_test.mbt
builtin/array.mbt

As title
There's a check around the second `UninitializedArray::unsafe_blit` because when index equals length, `src + src_offset` is an illegal address (although it works too without check).

fix: array.split_at shouldn't fail when index = length

---

array/fixedarray_sort.mbt
array/fixedarray_sort_by.mbt
array/sort.mbt
array/sort_by.mbt
rational/rational_test.mbt
sorted_set/set.mbt

The bleeding compiler recently adds feature for detecting optional arguments that are never/always supplied. Several warnings are reported on core, this PR fixes the unused optional argument issues.
One notable case is a `inspect_double_array` function in `rational/rational_test.mbt`. This function is a wrapper over `inspect`, and has an optional argument `~content : String = ""` just like inspect. The problem is, this optional argument will be automatically filled by `moon test -u`, so its default value will only be used when the test is initially added. After the test result is promoted, the default value become unused.
This PR removes the `inspect_double_array` wrapper to fix the warning. `inspect` itself is public so no warning will be reported on it.

fix some unused/never supplied optional argument

---

builtin/arraycore_js.mbt
builtin/arraycore_nonjs.mbt
builtin/builtin.mbti
builtin/intrinsics.mbt
builtin/uninitialized_array.mbt
deque/deque.mbt
deque/types.mbt

This pull request includes significant changes to the handling of uninitialized arrays in various files. The primary update involves the consolidation and redefinition of the `UninitializedArray` type and its associated functions.
* [`builtin/uninitialized_array.mbt`](diffhunk://#diff-e53e092c10c27e9466d1027ae9efd6a7333529a3cb4b90ab6180bea0d97ad416R1-R64): Introduced a new file that defines the `UninitializedArray` type and its associated functions, including `make`, `op_get`, `op_set`, `length`, and `unsafe_blit`.
* [`builtin/arraycore_js.mbt`](diffhunk://#diff-2531d56d432314b54a5a0a6b7e0552381bdde29b2ebcbb117f28c2fc12400c9aL15-L32): Removed the previous definitions of `UninitializedArray` and its associated functions.
* [`builtin/arraycore_nonjs.mbt`](diffhunk://#diff-b5f7899b1eaf5a490bd …

factor out UninitializedArray, avoid code duplication in three places

---

hashmap/moon.pkg.json
immut/hashset/moon.pkg.json

trailing comma is not support in standrad json, which cause publish failed

minor: remove trailing comma in pkg.json

---

builtin/autoloc.mbt
builtin/builtin.mbti

`ArgsLoc` only had a `to_string` method and did not implement `Show`

add [Show] implementation for [ArgsLoc]

---

coverage/coverage.mbt

Yesterday's compiler release introduces abstract visibility to traits, allowing traits to be sealed. The default visibility of traits now changes from private to abstract, just like types. So private traits should be marked as `priv` explicitly to adapt to this semantic change. This PR fixes this for core.

add `priv` mark to private traits

---

builtin/builtin.mbti
builtin/linked_hash_map.mbt
builtin/linked_hash_map_wbtest.mbt

fix: Json::op_equal returns false when the keys of 2 maps have different order

---

buffer/buffer.mbt
buffer/buffer.mbti
buffer/buffer_test.mbt

As required in the Markdown parser implementation.

add `length()` and `is_empty()` to `Buffer`

---

array/fixedarray.mbt
array/slice.mbt

This pull request includes improvements to the iteration logic in the `FixedArray` and `FixedArraySlice` classes. The most important changes involve updating the loop syntax for better readability and performance.
Improvements to iteration logic:
* [`array/fixedarray.mbt`](diffhunk://#diff-2284abe8d2ad886166df021851de56aa4239a390fcc582304cf2a08426f6ae2dL174-R174): Modified the `rev_eachi` method to use the `0..<len` loop syntax instead of `i = 0; i < len; i = i + 1`.
* [`array/slice.mbt`](diffhunk://#diff-f88e9e9c6253e182f3528354996c8d1c94fe3bfe113d746fa29dd2b16d80278cL44-R47): Updated the `rev_inplace` method to use the `0..<mid_len` loop syntax and refactored the calculation of `mid_len` and `j` for better readability.

refactor: simplify loop syntax in rev_eachi and rev_inplace functions

---

buffer/buffer.mbt
buffer/buffer.mbti
builtin/buffer.mbt
builtin/builtin.mbti
builtin/bytes.mbt
builtin/bytes_test.mbt
builtin/panic_test.mbt
builtin/show.mbt
builtin/string.mbt
builtin/stringbuilder_buffer.mbt
string/string_test.mbt

- add `to_unchecked_string(~offset,~length)` to Bytes 
- add `to_unchecked_string` to Buffer
- deprecate `Bytes::to_string` `Bytes::sub_string` `Buffer::to_string`

add to_unchecked_string, deprecate old APIs

---

builtin/builtin.mbti
builtin/linked_hash_set.mbt
builtin/linked_hash_set_test.mbt
hashset/hashset.mbt
hashset/hashset.mbti
hashset/hashset_test.mbt
immut/sorted_map/map.mbt
immut/sorted_map/map_test.mbt
immut/sorted_map/sorted_map.mbti
immut/sorted_map/utils.mbt
immut/sorted_map/utils_test.mbt

#1113
In `x_map` and `x_set`, there are two names for inserting a new element into collections: `add` and `insert`. This PR renames them to `add` and deprecates the old APIs.

rename `insert` in x_map and x_set to `add`

---

immut/sorted_set/immutable_set.mbt
immut/sorted_set/immutable_set_test.mbt
immut/sorted_set/sorted_set.mbti
sorted_set/set.mbt
sorted_set/set_test.mbt
sorted_set/sorted_set.mbti

#1113
- rename `diff` to `difference`
- rename `inter`/`intersect` to `intersection`
- deprecate old APIs

rename set operations to `intersection`, `difference`

---

builtin/builtin.mbti
builtin/linked_hash_set.mbt
builtin/linked_hash_set_test.mbt

This pull request introduces new methods to the `Set` type in the `builtin` module and updates existing methods to improve functionality. The changes primarily focus on adding and removing elements with checks and enhancing the test coverage.
* Added `add_and_check` method to `Set` for inserting a key and returning a boolean indicating success (`builtin/builtin.mbti`, `builtin/linked_hash_set.mbt`). [[1]](diffhunk://#diff-979a8cf0c39b3e1340630ddd48d1ed130df1eb2f6f8d94b9eb1b8613a9415875R323) [[2]](diffhunk://#diff-5cfaceb7277acdfdf25ddb09f41f85d52e6fa7c221c3e8eb6fced672d66fcd44L86-R87)
* Added `remove_and_check` method to `Set` for removing a key and returning a boolean indicating success (`builtin/builtin.mbti`, `builtin/linked_hash_set.mbt`). …

add add_and_check, remove_and_check

---

hashmap/hashmap.mbt
hashset/hashset.mbt
math/algebraic_test.mbt
test/test.mbt
test/test.mbti

We want to make `is` an reserved word in the future, but currently package `@test` has a API called `is` for asserting the physical equality of two objects. This PR deprecates this API and rename it to `@test.same_object`.

deprecate `@test.is` so that we can add `is` as a reserved word

---

buffer/buffer.mbt
buffer/buffer.mbti

There is a bug in formatter and type checker, the `pub(all)` visibility is invalid for `typealias`. cc @Guest0x0 @Young-Flash

add typealias to buffer

---

buffer/buffer.mbt
buffer/moon.pkg.json
builtin/builtin.mbti
builtin/bytes.mbt
builtin/bytes_test.mbt
bytes/bytes.mbt
bytes/bytes.mbti

This refactor is a preparation for making `Bytes` immutable. It basically changes the use of `Bytes` in the type `Buffer` to `FixedArray[Byte]`, and added `Bytes::cast_from_fixedarray` and `cast_to_fixedarray` to convert between `Bytes` and `FixedArray[Byte]`. Currently, these casts need to allocate, and we plan to implement these casts as primitives in the compiler to avoid the allocation eventually.

refactor buffer to use `FixedArray[Byte]` instead of `Bytes`

---

buffer/buffer.mbt
builtin/builtin.mbti
builtin/bytes.mbt
builtin/bytes_test.mbt
builtin/moon.pkg.json
builtin/panic_test.mbt

~~deprecate `Bytes` method `set_utf16_char`~~ in future request
deprecate `FixedArray[Byte]` ambiguous method `set_utf16_char`
new `FixedArray[Byte]` method `set_utf8_char`, `set_utf16le_char` and `set_utf16be_char`

add `FixedArray[Byte]` method `set_utf_char`

---

array/fixedarray_sort.mbt
array/fixedarray_sort_by.mbt
array/sort.mbt
array/sort_by.mbt

We should store the pred pivot element before updating arr.
And, there is a test case added which will trigger this bug.

fix(array): quick_sort store wrong pred pivot element

---

builtin/array_block.mbt
builtin/arraycore_js.mbt
builtin/arraycore_nonjs.mbt

This PR completes #1267 to allow the destination array to grow in the following case:
Before blit:
```
src array: [ 0  1  2  3  4 ]
src range:      ^--------^
dst array: [ 0  0  0  0  0 ]
dst range:               ^--------^
```
after blit:
```
dst array: [ 0  0  0  1  2  3  4]
```
If the start position of the dst range does not overlap with the dst array, it will panic:
```
dst array: [ 0  0  0  0  0 ]
dst range:                               ^--------^
```

enhance Array::blit_to to allow grow destination array

---

buffer/buffer.mbt
buffer/buffer.mbti
builtin/builtin.mbti
builtin/bytes.mbt
builtin/bytes_test.mbt
builtin/panic_test.mbt
builtin/show.mbt
builtin/string.mbt
builtin/stringbuilder_buffer.mbt
string/string.mbt

This PR:
1) deprecated `Bytes::blit_from_string` and `Bytes::set_utf16_char`
2) refactored stringbuilder_buffer.mbt to use `FixedArray[Byte]` instead of `Bytes`
3) Added `FixedArray::reinterpreted_as_bytes` and `Bytes::reinterpreted_as_fixedarray` for non-copy conversion between the two types.

deprecate `Bytes::blit_from_string` and `Bytes::set_utf16_char`

---

builtin/builtin.mbti
builtin/stringbuilder_buffer.mbt
builtin/stringbuilder_concat.mbt
builtin/stringbuilder_test.mbt

Mirrored from the corresponding `@buffer.T` API, as required by https://github.com/moonbit-community/cmark.

feat(builtin): add `StringBuilder::is_empty()`

---

immut/sorted_map/map.mbt
immut/sorted_map/map_test.mbt
immut/sorted_map/sorted_map.mbti
immut/sorted_map/traits_impl.mbt
immut/sorted_map/utils.mbt
immut/sorted_map/utils_test.mbt

#1295 
We have already chosen the naming convention for collection creation: use `new` instead of `empty`.

deprecate `immut/sorted_map.empty`

---

builtin/arrayview.mbt
builtin/builtin.mbti
builtin/iter.mbt

Currently moonc compiler uses 0 as the default start value implicitly. Later, we want to change the compiler to use the user-supplied default value.

add default start value for op_as_view

---

array/array.mbt
array/array_js.mbt
array/array_nonjs.mbt
array/moon.pkg.json

This PR make `Array::copy` implementation platform specific to get native speed under js target.

Use native array copy under js target

---

builtin/arrayview.mbt
builtin/arrayview_test.mbt
builtin/builtin.mbti

This PR is for discussion purposes.
It relates to #1013 and #1275.
I believe that it is _MUCH_ more flexible for the `map*` functions to return an `Array` (instead of an `ArrayView`).
Then, code that was performing a map on an entire array could easily insert a `[1:]` and now map all but the first entry without modifying any other code.
Additionally, it is much easier to turn an `Array` into an `ArrayView` than to go the other direction.

Implement map* and filter for ArrayView

---

math/trigonometric_test.mbt

```
coverage of `math/trigonometric.mbt`: 74.0% -> 98.6%
```

test: improve coverage for `math/trigonometric.mbt`

---

array/array.mbti
array/view.mbt
array/view_test.mbt

- #1013
This PR implements some usual methods for ArrayView.

feat(array): Impl eachi, all, any, contains for ArrayView

---

double/round_wasm.mbt
float/round_wasm.mbt

The compiler will no longer support the unnamed index in inline-wasm.

fix unnamed index in inline-wasm

---

json/moon.pkg.json

We are about to change default value for "test-import-all" to true for blackbox tests. That will cause the blackbox tests @json package fail to type check so I just explicitly set "test-import-all" to false beforehand.

explicitly disable test-import-all for json

---

array/view_test.mbt

```
coverage of `array/view.mbt`: 91.7% -> 100%
```

test: improve coverage for `array/view.mbt`

---

array/fixedarray_sort_by.mbt

```
coverage of `array/fixedarray_sort_by.mbt`: 88.5% -> 94.2%
```

test: improve coverage for `array/fixedarray_sort_by.mbt`

---

math/trigonometric.mbt
math/trigonometric_test.mbt

`atan(inf)` should be `1.5707963267948966`, not `Infinity`
`atan(-inf)` should be `-1.5707963267948966`, not `-Infinity`

Fix Atan output when Atan's input is `inf`

---

array/view_test.mbt
builtin/arrayview.mbt
builtin/builtin.mbti

impl Eq/Compare traits for ArrayView

---

builtin/array_block.mbt

```
coverage of `builtin/array_block.mbt`: 80.0% -> 100%
```

test: improve coverage for `builtin/array_block.mbt`

---

hashmap/hashmap.mbt

Avoid rehash on grow which maybe expensive.

hashmap: avoid rehash on grow

---

deque/deque.mbt
deque/deque.mbti
deque/deque_test.mbt

**Disclaimer:** The coverage improving part of this PR was generated by an LLM agent as part of an experiment.
New methods added:
* [`deque/deque.mbt`](diffhunk://#diff-38dbdcf314e0c64bb6564c48b049a68e997854ae69fdac00e490ce1d8b5906abR41-R56): Implemented the `copy` method, which creates a new copy of the deque.
* [`deque/deque.mbt`](diffhunk://#diff-38dbdcf314e0c64bb6564c48b049a68e997854ae69fdac00e490ce1d8b5906abL545-R607): Added the `iter2` method, which iterates over the deque with index and element pairs.
* [`deque/deque.mbti`](diffhunk://#diff-737e400600b9637258470836512a543fcf682ffc779b855d5aa15c741d4a6006R12-R20): Updated the `impl T` block to include the `copy` and `iter2` methods.
Optimizations:
* [`deque/deque.mbt`](https://github.com/moonbitlang/core/pull/1354/commits/f8203aeba93 …

feat(deque): add `@deque.iter2()` and `@deque.copy()`

---

math/trigonometric.mbt
math/trigonometric_test.mbt

There are some problems:
`sin(inf)` should be `NaN`, not `Infinity`
`sin(-inf)` should be `NaN`, not `-Infinity`
`cos(inf)` should be `NaN`, not `Infinity`
`cos(-inf)` should be `NaN`, not `-Infinity`
`tan(inf)` should be `NaN`, not `Infinity`
`tan(-inf)` should be `NaN`, not `-Infinity`
`asin(inf)` should be `NaN`, not `Infinity`
`asin(-inf)` should be `NaN`, not `-Infinity`
`acos(inf)` should be `NaN`, not `Infinity`
`acos(-inf)` should be `NaN`, not `-Infinity`
Verify it in python (Not only python, I get same resutlt in C, rust, and the like):
```python
>>> import numpy as np
>>> import warnings
>>> warnings.simplefilter("ignore") # ignore warnings because numpy will throw warnings when output contains `nan`
>>> numbers_contain_inf = np.array([-np.inf, np.inf, 0.0, 1.0])
>>> …
```

Fix trigonometric function's output when input is inf

---

deque/deque.mbt

Continuation of https://github.com/moonbitlang/core/pull/1354.
Improvements to iteration methods:
* `pub fn each[A](self : T[A], f : (A) -> Unit) -> Unit`: Updated the method to use a direct iteration over the collection instead of indexing.
* `pub fn eachi[A](self : T[A], f : (Int, A) -> Unit) -> Unit`: Updated the method to use a direct iteration with index over the collection instead of indexing.

perf(deque): use `@deque.iter[2]()` for `@deque.each[i]()`

---

array/deprecated.mbt
buffer/deprecated.mbt
builtin/array.mbt
builtin/arraycore_js.mbt
builtin/arraycore_nonjs.mbt
builtin/bigint_deprecated.mbt
builtin/byte.mbt
builtin/bytes.mbt
builtin/console.mbt
builtin/int64_js.mbt
builtin/int64_nonjs.mbt
builtin/intrinsics.mbt
builtin/iter.mbt
builtin/iter_upto.mbt
builtin/linked_hash_set.mbt
deque/deque.mbt
double/double.mbt
hashset/hashset.mbt
immut/array/array.mbt
immut/list/list.mbt
immut/priority_queue/priority_queue.mbt
immut/sorted_map/depercated.mbt
immut/sorted_map/utils.mbt
immut/sorted_set/immutable_set.mbt
priority_queue/priority_queue.mbt
queue/queue.mbt
sorted_set/set.mbt
string/deprecated.mbt
test/test.mbt

chore: skip coverage check for all deprecated `pub fn`s

---

deque/deque_test.mbt

test(deque): add more tests

---

builtin/builtin.mbti
builtin/iter.mbt
builtin/iter_test.mbt

The `tap` should be used to perform side effects during the iteration of one item instead of rerunning the iteration.

fix(iter): tap

---

deque/deque.mbt
deque/deque.mbti
deque/deque_test.mbt

This pull request includes changes to the `deque` module to improve iteration methods and add tests for reverse iteration. The most important changes include refactoring existing iteration methods to use new reverse iteration methods and adding tests to ensure the correctness of these new methods.
Refactoring iteration methods:
* [`deque/deque.mbt`](diffhunk://#diff-38dbdcf314e0c64bb6564c48b049a68e997854ae69fdac00e490ce1d8b5906abL434-R435): Refactored `rev_each` and `rev_eachi` methods to use the new `rev_iter` and `rev_iter2` methods respectively. [[1]](diffhunk://#diff-38dbdcf314e0c64bb6564c48b049a68e997854ae69fdac00e490ce1d8b5906abL434-R435) [[2]](diffhunk://#diff-38dbdcf314e0c64bb6564c48b049a68e997854ae69fdac00e490ce1d8b5906abL450-R451)
* …

perf(deque): use `@deque.rev_iter[2]()` for `@deque.rev_each[i]()`

---

NOTICE
double/mod_nonjs.mbt
double/mod_test.mbt

Closes #1303
Rewrite `op_mod` for Double using MUSL implementation ([src/math/fmod.c](https://git.musl-libc.org/cgit/musl/tree/src/math/fmod.c)). The origin license of the file is in commit [b69f695](https://git.musl-libc.org/cgit/musl/commit/src/math/fmod.c?id=b69f695acedd4ce2798ef9ea28d834ceccc789bd).
More tests are provided.

fix(double): op_mod for subnormal double (#1303)

---

builtin/char.mbt

```
coverage of `builtin/char.mbt`: 0.00% -> 100.00%
```

test: improve coverage for `builtin/char.mbt`

---

array/sort.mbt

It looks like this cannot be achieved with black box tests, so the agent has repeatedly abandoned on this task... Anyway, the file coverage is now 100%.

test: improve coverage for `array/sort.mbt`

---

builtin/option_test.mbt

```
coverage of `builtin/option.mbt`: 70.0% -> 100%
```

test: improve coverage for `builtin/option.mbt`

---

builtin/builtin.mbti
builtin/uninitialized_array.mbt
deque/deque.mbt
deque/deque.mbti
deque/deque_test.mbt

This is a preparation PR for `@deque.truncate()` as required in cmark.
The specific API in question mirrors Rust's [`VecDeque::as_slices()`](https://doc.rust-lang.org/std/collections/struct.VecDeque.html#method.as_slices).

feat(deque): add `@deque.as_views()`

---

deque/deque.mbt
deque/deque.mbti
deque/deque_test.mbt

This is a preparation PR for `@deque.filter_map_inplace()` as required in cmark.
The specific API in question mirrors Rust's [`VecDeque::truncate()`](https://doc.rust-lang.org/std/collections/struct.VecDeque.html#method.truncate).

feat(deque): add `@deque.truncate()`

---

deque/deque.mbt
deque/deque.mbti
deque/deque_test.mbt

This is the implementation PR for `@deque.filter_map_inplace()` as required in cmark.
Mirrors Rust's [`VecDeque::retain_mut()`](https://doc.rust-lang.org/std/collections/vec_deque/struct.VecDeque.html#method.retain_mut).

feat(deque): add `@deque.filter_map_inplace()`

---

bool/bool.mbt

Add documentations to bool package.

[doc] bool

---

builtin/stringbuilder_buffer.mbt

Converted to draft for now since I think there a potential issue with integer overflow. We should have something like maximum array/string size.

add a fastpath for `grow_if_necessary` in stringbuilder_buffer

---

uint64/uint64.mbt

Disclaimer: This PR was generated by an LLM agent as part of an experiment.
```
coverage of `uint64/uint64.mbt`: 0.00% -> 100%
```

test: improve coverage for `uint64/uint64.mbt`

---

buffer/buffer.mbt

```
PS C:\illu\repo\moonbit\core>  moon test --doc
Warning: [2000]
╭─[C:\illu\repo\moonbit\core\buffer\buffer.mbt:33:20]
│
33 │ /// assert_eq!(buf.to_unchecked_string(), "Test")
│                    ─────────┬─────────
│                             ╰─────────── Warning (Alert deprecated): Use `Buffer::contents` to read the contents of the buffer
```

remove deprecated API when moon test --doc

---

float/float.mbt
float/float.mbti
float/float_test.mbt

add some float utils functions

---

builtin/char.mbt
string/string.mbti
string/utils.mbt
string/view.mbt
string/view_test.mbt

Basic usage:
```
let str = "Hello🤣🤣🤣"
guard let Some(start) = CharOffset::offset_by(str, 1)
guard let Some(end) = CharOffset::offset_by(str, 6)
let view = str[start:end]
inspect!(view, content="ello🤣")
```
To create a `CharsView` from a `String`, we need to use the `CharOffset` as indices. `CharOffset` is an opaque type that represents a position in the utf-16 String. It can be constructed via `CharOffset::offset_by(str: String, offset: int)` where the offset is the number of characters skipped between the start of the string and the returning position. It can also be constructed via `CharOffset::unsafe_from_int(index: Int)`.
This is to avoid confusion with indexing `String` using indices, i.e. indices indicate utf-16 code unit offset when accessing `String` whereas when viewing `String` …

add `StringView`

---

sorted_set/set.mbt

improve each for sorted_set and refactor eachi

---

builtin/builtin.mbti
builtin/json.mbt
json/from_json.mbt
json/from_json_test.mbt
json/json.mbti
json/to_json_test.mbt

For `FromJson` and `ToJson`, we only guarantee the roundtrip property.
So for `UInt64` and `Int64`, we'll be using `String` as representation, and for `UInt` and `Int`, we'll be using `Number` as representation.

feat: add from/to json for uint/uint64

---

sorted_map/map.mbt
sorted_map/map_test.mbt
sorted_map/sorted_map.mbti
sorted_set/set.mbt
sorted_set/set_test.mbt
sorted_set/sorted_set.mbti

Added .range() method to sorted_map and sorted_set, and privode the test cases

#1264 Add .range() method to sorted_map and sorted_set

---

deque/deque.mbt
deque/deque.mbti
deque/deque_test.mbt

... so that the naming is shorter and more consistent WRT `.retain()`.
* [`deque/deque.mbt`](diffhunk://#diff-38dbdcf314e0c64bb6564c48b049a68e997854ae69fdac00e490ce1d8b5906abL929-R935): Renamed `filter_map_inplace` to `retain_map` and updated the corresponding test example.
* [`deque/deque.mbt`](diffhunk://#diff-38dbdcf314e0c64bb6564c48b049a68e997854ae69fdac00e490ce1d8b5906abR974-R983): Added a deprecation notice to `filter_map_inplace` and made it call `retain_map`.
* [`deque/deque.mbti`](diffhunk://#diff-737e400600b9637258470836512a543fcf682ffc779b855d5aa15c741d4a6006L16-R16): Marked `filter_map_inplace` as deprecated and added the new `retain_map` function signature. [[1]](diffhunk://#diff-737e400600b9637258470836512a543fcf682ffc779b855d5aa15c741d4a6006L16-R16) …

feat(deque): rename `@deque.filter_map_inplace()` to `.retain_map()`

---

string/string.mbti
string/view.mbt
string/view_test.mbt

Several changes:
* Given `str` with `n` code points, previously `String::index(str, i)` returns `Some` if `0 <= i < n`. This PR changes this behavior so that it return `Some` if `0 <= i <= n`. This is because the result `StringIndex` is used for taking StringView where index is allowed to be the length of string.
* Added `String::index_by_rev` to search for an index backwards
* Enhanced `StringView::op_as_view` so that it can take negative index, and when the index is negative, it uses `String::index_by_rev` to create the new view.

Support using negative index to take StringView

---

string/string.mbti
string/view.mbt
string/view_test.mbt

Because the `length` method for `StringView` has `O(n)` time complexity, we provide two auxiliary methods `length_eq` and `length_ge` which are fast when the target length is small.

provide length_eq and length_ge for StringView

---

builtin/builtin.mbti
builtin/bytes.mbt
builtin/intrinsics.mbt

This PR also removed the deprecated bytes methods that use `Bytes::op_set`.

deprecate Bytes::op_set

---

builtin/array.mbt
builtin/arraycore_nonjs.mbt
double/exp_js.mbt

Fix incorrect documentation, including:
1. Missing instrinsics.
2. Extra code fence
3. Incorrect alert message.

fix: incorrect doc from docs PRs

---

string/string.mbti
string/view.mbt
string/view_test.mbt

This PR adds `rev_get` method for `StringView`. This is useful for implementing pattern match on `StringView`.

add rev_get for StringView

---

double/log.mbt

`neg_infinity.ln()` should return `not_a_number`, not `neg_infinity`.
See the following python code:
```python
>>> import numpy as np
>>> import warnings # set ignore runtimewarning
>>> warnings.filterwarnings("ignore", category=RuntimeWarning)
>>> np.log([-np.inf])
array([nan])
```
In javaScript, run the following code:
```javascript
console.log(Math.log(-Infinity))
```
we could get `NaN`

neg_infinity.ln() should return nan, not -inf

---

builtin/builtin.mbti
builtin/show.mbt
builtin/show_test.mbt
immut/list/list.mbt
immut/list/list.mbti
result/result.mbt
result/result.mbti

Since MoonBit allows calling `impl` with dot syntax now, it is no longer necessary to define `to_string` method wrappers to support `.to_string()` usage. This PR remove such unnecessary `to_string` wrapper methods.
One of the removed methods, `Result::to_string` in `@result`, actually has wrong behavior, forgetting to escape its arguments when necessary. This PR fixes the issue.
I also added tests for the `Show` impls.

remove some unnecessary/wrong [to_string] methods

---

builtin/bigint_js.mbt
builtin/bigint_nonjs.mbt
builtin/int64_js.mbt

This is a continuation of #1472. #1472 ensures there is no name clash between methods defined as `fn f(self : T, ..)` and regular functions. In the proposed semantic of #1472, all methods in `@builtin` should be qualified, because we don't want users to call these methods directly, unqualified using the `f(...)` syntax. However, several methods in `@builtin` are still unqualified in #1472, so this PR make them qualified.

make all methods defined in builtin qualified

---

double/log.mbt

The original `log10` implementation:
```moonbit
// current version
pub fn log10(self : Double) -> Double {
ln(self) / ln10
}
```
has precision issues. For example, `log10(1000)` yields `2.9999999999999996` instead of the expected `3`.
In this PR, I've implemented a more accurate algorithm and added additional test cases:
```moonbit
pub fn log10(self : Double) -> Double {
if self < 0.0 {
return not_a_number
} else if self.is_nan() || self.is_inf() {
return self
} else if self == 0.0 {
return neg_infinity
}
let ivln10 = 4.34294481903251816668e-01
let log10_2hi = 3.01029995663611771306e-01
let log10_2lo = 3.69423907715893078616e-13
let (f, e) = frexp(self)
let (f, e) = if e >= 1 {
(f * 2.0, (e - 1).to_double())
} else {
(f, e.to_double())
}
let z = e * log10_2lo + ivln10 * f.ln()
z + e * …
```

A better log10 implementation

---

array/array.mbt
builtin/array.mbt

- Updated `Array::make` to use a more concise range-based loop.
- Enhanced `Array::op_equal` and `Array::compare` methods for better clarity and efficiency by replacing traditional loops with guard statements.

Refactor array methods for improved readability and performance

---

strconv/decimal.mbt

```
coverage of `strconv/decimal.mbt`: 79.0% -> 81.5%
```

test: improve coverage for `strconv/decimal.mbt`

---

builtin/builtin.mbti
builtin/intrinsics.mbt
builtin/string.mbt
builtin/string_test.mbt
string/string.mbt
string/string.mbti
string/string_test.mbt
string/utils.mbt
string/view.mbt

Part of #1452
This PR adds the following APIs for String in builtin for general purpose usage:
```
charcode_at(String, Int) -> Int
charcode_length(String) -> Int
codepoint_at(String, Int) -> Char
codepoint_length(String) -> Int
unsafe_charcode_at(String, Int) -> Int // charcode_at without bound checking
```
And adds the following APIs for implementing pattern matching on string:
```
length_eq(String, Int) -> Bool
length_ge(String, Int) -> Bool
rev_get(String, Int) -> Char
```
The next step is to change the behavior of `op_get` and `length` to `codepoint_at` and `codepoint_length`, and fix the various misuses.
One subtlety is that the `codepoint_at` here has different behavior that `code_point_at` in JavaScript. Here the index is the count of code points, whereas for JavaScript, the index …

implement unicode safe api for String

---

builtin/assert.mbt
builtin/autoloc.mbt
builtin/bigint_nonjs.mbt
builtin/byte.mbt
builtin/bytes.mbt
builtin/bytes_block.mbt
builtin/bytesview.mbt

This PR add documentations to publich APIs in @builtin package, completing upto files starts with `b`.

Add documentations to some more builtin files

---

builtin/iter2_test.mbt

```
coverage of `builtin/iter2.mbt`: 70.0% -> 100%
```

test: improve coverage for `builtin/iter2.mbt`

---

builtin/fixedarray_block_test.mbt

```
coverage of `builtin/fixedarray_block.mbt`: 22.2% -> 44.4%
```

test: improve coverage for `builtin/fixedarray_block.mbt`

---

builtin/json_test.mbt

```
coverage of `builtin/json.mbt`: 22.0% -> 97.6%
```

test: improve coverage for `builtin/json.mbt`

---

builtin/tuple_eq_test.mbt

```
coverage of `builtin/tuple_eq.mbt`: 6.67% -> 100%
```

test: improve coverage for `builtin/tuple_eq.mbt`

---

uint/uint_test.mbt

```
coverage of `uint/uint.mbt`: 40.0% -> 100%
```

test: improve coverage for `uint/uint.mbt`

---

builtin/bytesview_test.mbt

```
coverage of `builtin/bytesview.mbt`: 53.1% -> 100%
```

test: improve coverage for `builtin/bytesview.mbt`

---

builtin/string_test.mbt

```
coverage of `builtin/string.mbt`: 44.7% -> 94.7%
```

test: improve coverage for `builtin/string.mbt`

---

builtin/assert_test.mbt

```
coverage of `builtin/assert.mbt`: 36.4% -> 63.6%
```

test: improve coverage for `builtin/assert.mbt`

---

quickcheck/arbitrary_test.mbt

```
coverage of `quickcheck/arbitrary.mbt`: 55.3% -> 63.2%
```

test: improve coverage for `quickcheck/arbitrary.mbt`

---

char/char.mbt
char/char.mbti
char/char_test.mbt

Add parts of methods for Char.

---

int64/int64_test.mbt

```
coverage of `int64/int64.mbt`: 57.1% -> 85.7%
```

test: improve coverage for `int64/int64.mbt`

---

strconv/uint.mbt

```
coverage of `strconv/uint.mbt`: 58.3% -> 62.5%
```

test: improve coverage for `strconv/uint.mbt`

---

int/int_test.mbt

```
coverage of `int/int.mbt`: 60.0% -> 100%
```

test: improve coverage for `int/int.mbt`

---

builtin/console.mbt

```
coverage of `builtin/console.mbt`: 66.7% -> 100%
```

test: improve coverage for `builtin/console.mbt`

---

char/char.mbt
char/char.mbti
char/char_test.mbt

The user should validate the input as throwing error has little sense in this case:
```moonbit
let radix = ...
try {
is_digit!('a', radix)
} catch {
_ => error handling
}
```
Should just be
```moonbit
let radix = ...
if radix >= 2 && radix <= 36 {
is_digit('a', radix)
} else {
...
}
```
Throwing error will cause performance penalty and necessary error handling

chore: adjust api and remove error

---

coverage/coverage.mbt

chore: ignore `@coverage.end` for coverage checks

---

.github/workflows/check.yml

This should help mitigate our CI bottleneck caused by the shortage of macOS runners.

ci: use `ubuntu-latest` for coverage checks

---

builtin/bigint_nonjs.mbt
sorted_set/set.mbt
sorted_set/sorted_set.mbti

#1461 
Basically, just change
```moonbit
pub fn deep_clone[V](self : T[V]) -> T[V] {
*some code*
}
```
To
```moonbit
/// @alert deprecated "Use `copy` instead"
/// @coverage.skip
pub fn deep_clone[V](self : T[V]) -> T[V] {
copy(self)
}
pub fn copy[V](self : T[V]) -> T[V] {
*some code*
}
```

chore: rename `deep_clone` into `copy`

---

builtin/array.mbt

The doc test of `Array::capacity(...)` is not consistent across different backend.
cc @Guest0x0

remove array capacity doc test

---

builtin/hasher_test.mbt

```
coverage of `builtin/hasher.mbt`: 69.4% -> 75.0%
```

test: improve coverage for `builtin/hasher.mbt`

---

ref/ref_test.mbt

```
coverage of `ref/ref.mbt`: 71.4% -> 85.7%
```

test: improve coverage for `ref/ref.mbt`

---

unit/unit_test.mbt

```
coverage of `unit/unit.mbt`: 66.7% -> 100%
```

test: improve coverage for `unit/unit.mbt`

---

.github/workflows/check.yml

Similar to #1549, this should help mitigate our CI bottleneck caused by the shortage of macOS runners.

ci: disable `dedup_wasm` checks on macOS runners

---

strconv/decimal.mbt
strconv/moon.pkg.json

This PR refactors `@strconv.parse_decimal` by using pattern matching on `StringView` to avoid misuses of string indexing.

refactor parse decimal

---

immut/hashmap/HAMT_test.mbt

```
coverage of `immut/hashmap/HAMT.mbt`: 72.7% -> 80.3%
```

test: improve coverage for `immut/hashmap/HAMT.mbt`

---

strconv/double_test.mbt

```
coverage of `strconv/double.mbt`: 74.1% -> 81.5%
```

test: improve coverage for `strconv/double.mbt`

---

json/lex_misc_test.mbt

```
coverage of `json/lex_misc.mbt`: 72.5% -> 82.5%
```

test: improve coverage for `json/lex_misc.mbt`

---

float/float_test.mbt

```
coverage of `float/float.mbt`: 72.7% -> 100%
```

test: improve coverage for `float/float.mbt`

---

builtin/intrinsics_test.mbt

```
coverage of `builtin/intrinsics.mbt`: 75.0% -> 87.5%
```

test: improve coverage for `builtin/intrinsics.mbt`

---

quickcheck/splitmix/random_test.mbt

```
coverage of `quickcheck/splitmix/random.mbt`: 76.2% -> 95.2%
```

test: improve coverage for `quickcheck/splitmix/random.mbt`

---

builtin/show_test.mbt

```
coverage of `builtin/show.mbt`: 79.3% -> 89.7%
```

test: improve coverage for `builtin/show.mbt`

---

json/lex_string_test.mbt

```
coverage of `json/lex_string.mbt`: 76.5% -> 82.4%
```

test: improve coverage for `json/lex_string.mbt`

---

builtin/linked_hash_set_test.mbt

```
coverage of `builtin/linked_hash_set.mbt`: 78.5% -> 89.7%
```

test: improve coverage for `builtin/linked_hash_set.mbt`

---

math/trigonometric.mbt
math/trigonometric_test.mbt

It is reported in https://taolun.moonbitlang.com/t/topic/1128, that the result of `atan2(-0, -1)` is wrong.
According to IEEE754, atan2(±0, x) is ±π for x < 0.
The root cause of the issue is that the old copysign just checks if y < 0 and does not distinguish ±0.
This PR fixes this by checking the sign bit instead.

fix wrong atan2 result on -0.0

---

immut/array/array_mix_wbtest.mbt
immut/array/array_wbtest.mbt
immut/array/moon.pkg.json
immut/array/utils_wbtest.mbt

Use LCG instead of chacha8
Use from_array instead of from_iter
This should make the test time half as before

refactor: improve test speed

---

double/trig_nonjs_test.mbt

```
coverage of `double/trig_nonjs.mbt`: 78.9% -> 86.4%
```

test: improve coverage for `double/trig_nonjs.mbt`

---

strconv/decimal.mbt
strconv/double.mbt
strconv/strconv.mbti

This type should not be public as explained in: https://github.com/moonbitlang/core/issues/1390

Deprecate @strconv.Decimal and its public APIs

---

sorted_map/map.mbt
sorted_map/map_test.mbt
sorted_map/sorted_map.mbti

I think deprecate old API is impossible
- #1590

deprecate: inconsistent api @sorted_map.of

---

test/test.mbt
test/test.mbti

We add `is` as a reserved keyword in bleeding compiler. This PR remove the already deprecated `@test.is` function so that the bleeding check on CI will pass.

fix!: remove @test.is

---

builtin/assert.mbt

fix: remove redundant loc in assert_xx function

---

builtin/char.mbt
builtin/console.mbt
builtin/failure.mbt
builtin/fixedarray.mbt
builtin/fixedarray_block.mbt
builtin/hasher.mbt
builtin/int64_nonjs.mbt
builtin/intrinsics.mbt

This PR add documentation to:
- `char.mbt`
- `console.mbt`
- `failure.mbt`
- `fixedarray.mbt`
- `fixedarray_block.mbt`
- `hasher.mbt`
- `int64_nonjs.mbt`
- `intrinsics.mbt`
Note: adding this PR cause context to exceed 128K when generating docs for the builtin package.

docs: add docs for char to intrinsics

---

builtin/builtin.mbti
builtin/iter.mbt
builtin/iter_test.mbt

add Iter[String]::join

---

builtin/fixedarray_test.mbt

```
coverage of `builtin/fixedarray.mbt`: 80.0% -> 100%
```

test: improve coverage for `builtin/fixedarray.mbt`

---

immut/hashset/HAMT_test.mbt

```
coverage of `immut/hashset/HAMT.mbt`: 81.4% -> 84.3%
```

test: improve coverage for `immut/hashset/HAMT.mbt`

---

string/view_test.mbt

```
coverage of `string/view.mbt`: 81.9% -> 92.2%
```

test: improve coverage for `string/view.mbt`

---

result/result_test.mbt

```
coverage of `result/result.mbt`: 81.8% -> 90.9%
```

test: improve coverage for `result/result.mbt`

---

double/double_test.mbt

```
coverage of `double/double.mbt`: 76.2% -> 95.2%
```

test: improve coverage for `double/double.mbt`

---

strconv/number_test.mbt

```
coverage of `strconv/number.mbt`: 82.3% -> 85.5%
```

test: improve coverage for `strconv/number.mbt`

---

builtin/traits_test.mbt

```
coverage of `builtin/traits.mbt`: 77.8% -> 88.9%
```

test: improve coverage for `builtin/traits.mbt`

---

env/env_native.mbt
env/moon.pkg.json

cc @Young-Flash any idea why this was not caught by the CI?

remove unused package

---

immut/sorted_set/generic_test.mbt

```
coverage of `immut/sorted_set/generic.mbt`: 83.9% -> 100%
```

test: improve coverage for `immut/sorted_set/generic.mbt`

---

json/lex_number_test.mbt

```
coverage of `json/lex_number.mbt`: 85.4% -> 93.8%
```

test: improve coverage for `json/lex_number.mbt`

---

builtin/builtin.mbti
builtin/to_string.mbt

This PR introduces the new feature described in #1500 .  
**Closes #1500 .**  
In JavaScript, the `toString` method allows converting numbers to strings. By default, `toString()` returns the decimal format, while `toString(16)` returns the hexadecimal format.  
However, directly modifying `to_string` in MoonBit can lead to issues. For example:  
```moonbit
let x = 1
println("x = \{x}")
// ^ This calls `x.to_string()`, which requires `to_string` keeping type `(Int) -> String`.
```
To address this, I've added a new function `to_string_by_radix`. If there's a better name for this function, I'm open to suggestions!

to_string_by_radix method for standard integers

---

builtin/json.mbt
builtin/json_test.mbt
json/json_test.mbt
json/to_json_test.mbt

Closes #1684.
There are no differences between `@json`'s `String` data model and MoonBit's native `String` data model, so there are no conversions/escapes to be done. The only place where conversions/escapes are needed is when printing the resulting `Json` as a string, i.e. in `@json.stringify()`. As such, `escape_json_string()` is redundant.

fix(builtin/json): fix `String::to_json()`-`@json.from_json()` round trip

---

builtin/tuple_hash_test.mbt

```
coverage of builtin/tuple_hash.mbt: 0% -> 100%
```

test: improve coverage for `builtin/tuple_hash.mbt`

---

builtin/console.mbt

This PR doesn't affect the current behavior. moon will do some extra work to provide smooth migrations.

add base16 encoding in inspect

---

array/array_js.mbt
builtin/arraycore_js.mbt
builtin/autoloc.mbt
builtin/bigint_js.mbt
builtin/builtin.mbti
builtin/intrinsics.mbt
env/env_wasm.mbt
string/string_test.mbt

This compiler migrate core to adapt compiler changes from the latest release.
The most significant change in the syntax of declaring external FFI type. Previously the syntax is `type T`, and in the future the syntax will be migrated to the more explicit `extern type T`. Currently the old syntax will be warned, and the formatter will automatically change `type T` to `extern type T`, so run `moon fmt` is adequate for migration.
The `type T` syntax, whose visual intuition is abstract type rather than external type, may be reused in the future for other purpose.
There is one more minor formatter style change. A space will be added after `..` in string pattern, such as `[ .."literal" ]`.

migrate core to adapt new compiler change

---

env/env_native.mbt

To be consistent other backends

fix: convert result to milliseconds in env.now() for native backend

---

string/string.mbt
string/string_test.mbt

The previous implementation was incorrect when the substring is empty. It returned 0 instead of the `from` parameter. This PR fixes this bug and refactored the code to make it more clear.

fix @string.index_of and refactor

---

builtin/output.mbt
builtin/show.mbt
builtin/to_string.mbt

improve: show output impl

---

immut/list/list.mbt
immut/list/list.mbti
immut/list/list_test.mbt

The original implementation reverses the order. This PR fixes the order, and provides an efficient `from_iter_rev` for the use case where order is irrelevant.

fix the order of elements in `from_iter`

---

builtin/iter.mbt
builtin/string.mbt
builtin/string_test.mbt

unqualified methods (declared with `fn f(self : T, ..)`) will be included in the toplevel scope of the package. If the package is `@builtin`, it means everyone can call the method unqualified, which is probably undesirable. So `@builtin` should not contain unqualified method.
This PR fixes several unqualified methods in `@builtin` and make them qualified (`T::method_name`)

fix: builtin package should not contain unqualified method

---

builtin/guard_feature_test.mbt

Introduces a new test file demonstrating the use of guard in pattern matching for simplifying arithmetic expressions. The test showcases simplification rules like handling zero and identity elements, and verifies the simplification of equivalent subexpressions.

test: Add guard feature test for expression simplification

---

builtin/builtin.mbti
builtin/iter.mbt
builtin/iter_test.mbt

I'm making some String methods deprecated. We currently have `codepoint_at(i)` to get the i-th codepoint in a string and this should be changed to `str.iter().nth(i)`.

feat(iter): add `nth`

---

immut/list/deprecated.mbt
strconv/decimal.mbt

`parse_decimal` was deprecated, not need detailed documentation

fix: warning when run moon test --doc

---

priority_queue/priority_queue.mbt
priority_queue/priority_queue_test.mbt

This PR just rewrites the `merges` using loop to avoid stack overflow

make `merges` priority queue stack safe

---

array/fixedarray_sort.mbt
array/fixedarray_sort_by.mbt
array/sort.mbt
array/sort_by.mbt
hashmap/utils.mbt
hashset/hashset.mbt
immut/array/tree.mbt
immut/array/tree_utils.mbt
immut/hashset/HAMT.mbt
immut/list/list.mbt
immut/priority_queue/priority_queue.mbt
immut/sorted_map/traits_impl.mbt
immut/sorted_set/immutable_set.mbt
json/from_json.mbt
json/json.mbt
option/option.mbt
result/result.mbt
sorted_set/set.mbt
strconv/int.mbt
strconv/uint.mbt

This PR rewrite match with wildcard pattern to is pattern, thus avoid fragile pattern matching warnings. And result's better readability.

refactor: rewrite match with wildcard pattern to is pattern

---

builtin/builtin.mbti
builtin/operators.mbt

We plan to migrate the operator overloading mechanism from using methods to using traits. This would give:
- give better type inference for operators
- better documentation for operator overloading, the intent of overloading operators would become explicit
- allows user-defined traits to include builtin types' operators via super trait
This PR is a starter for this migration, it adds trait definitions for each overload-able MoonBit operator. Note that this PR alone has no effect yet, compiler changes are necessary too, which would hopefully be released next week.
After the compiler migrates operator overloading to traits, current user code that uses method for operator overloading will not receive hard break, because currently we still allow implementing traits with methods. But a warning …

add trait definition for operators overloading

---

builtin/bigint_nonjs.mbt
builtin/builtin.mbti
builtin/bytes.mbt
builtin/hasher.mbt
builtin/intrinsics.mbt
builtin/output.mbt
builtin/show.mbt
builtin/string.mbt
coverage/coverage.mbt
json/lex_misc.mbt
json/utils.mbt
strconv/decimal.mbt
strconv/string_slice.mbt
string/string.mbt
string/view.mbt

Breaking API change:
* `String::op_get` returns `Int` instead of `Char` to reflect that it reads the codeunit instead of the unicode codepoint
New API: 
* `String::unsafe_charcode_at` to avoid bound check
This PR also deprecates the following obsolete methods:
* `String::get()`
* `String::charcode_length()`

Breaking change: indexing string returns `Int` instead of `Char`

---

builtin/builtin.mbti
builtin/char.mbt
builtin/char_test.mbt
strconv/decimal.mbt
strconv/int.mbt
strconv/uint.mbt

We plan to migrate operator overloading from using methods to using traits. The trait for the `-` operator has the following signature:
```moonbit
trait Sub {
op_sub(Self, Self) -> Self
}
```
However, the `Char::op_sub` operator is incompatible with this trait: it has type `(Char, Char) -> Int`. So this PR deprecates the `Char::op_sub` operator.
The typical usage of this operator is to calculate offset between characters, and most of the times the second operand is a char literal, such as `c - 'a'`. In this case, the program can be transformed to `c.to_int() - 'a'`. Thanks to recently introduced overloading of char literal to type `Int`, the second operand need no change.

deprecate [Char::op_sub]

---

builtin/builtin.mbti
builtin/console.mbt
builtin/string.mbt
builtin/string_test.mbt

The index `i` in `str.codepoint_at(i)` will be changed from unicode index to utf16 index.

deprecated `codepoint_at` and provide `unsafe_codepoint_at`

---

prelude/moon.pkg.json
prelude/prelude.mbt
prelude/prelude.mbti

Currently, `@builtin` serves two purpose in core:
1. hold fundamental definitions, such as arithmetic operators on builtin types, to resolve cyclic definition between other core packages
2. serve as a prelude package. The content of `@builtin` can be used directly, unqualified
But these two purposes are contradictory: as a place to hold fundamental definitions, we want `@builtin` to be as small as possible. Meanwhile, due to `@builtin`'s role as a prelude package, we have put heavy things such as linked hash map into `@builtin`.
So, we intend to split `@builtin` into two packages:
- `@builtin` will hold fundamental definitions, and should be as small as possible
- a new package `@prelude` will be added, and its content can be used directly unqualified. `@prelude` should not contain any …

separate builtin package and prelude package

---

array/array.mbti
array/fixedarray.mbt
builtin/array.mbt
builtin/bigint_js.mbt
builtin/bigint_nonjs.mbt
builtin/builtin.mbti
builtin/byte.mbt
builtin/int64_js.mbt
builtin/int64_nonjs.mbt
builtin/intrinsics.mbt
builtin/iter.mbt
bytes/bytes.mbt
bytes/bytes.mbti
double/double.mbti
double/mod_js.mbt
double/mod_nonjs.mbt
float/float.mbti
float/mod.mbt
immut/array/array.mbt
immut/array/array.mbti
immut/list/list.mbt
immut/list/list.mbti
immut/sorted_set/immutable_set.mbt
immut/sorted_set/sorted_set.mbti
int16/int16.mbt
int16/int16.mbti
rational/rational.mbt
rational/rational.mbti
uint16/uint16.mbt
uint16/uint16.mbti

This PR migrate overloaded operators to use traits in `builtin/operators.mbt`. Since trait implementations can be called via dot syntax directly, this change is compatible with current version of MoonBit, and allows seamless migration to new operator overloading semantic based on traits.
The only exception that cannot be migrated is `Char::op_sub`, whose return type is `Int` rather than `Char`. This operator is already deprecated in #1806, and will be removed in the future.

migrate operator overloading to using traits

---

builtin/builtin.mbti
builtin/console.mbt
builtin/string.mbt
builtin/string_test.mbt
strconv/decimal.mbt
string/deprecated.mbt
string/string.mbt
string/string.mbti
string/string_test.mbt
string/view.mbt
string/view_test.mbt

Deprecated APIs:
* `@string.View::{op_get, rev_get}`. Use `view.iter().nth(n)` or `view.rev_iter().nth()` instead
* `String::rev_get`. Use `str.rev_iter().nth()` instead. It's symmetric version `String::codepoint_at` has already been deprecated.
Renamed APIs:
* `{String, @string.View}::length_{eq, ge}` -> `{String, @string.View}::char_length_{eq, ge}`. Old API deprecated, and new API added.
* `String::unsafe_codepoint_at` -> `String::unsafe_char_at`. This is a newly added public API so I renamed it directly instead of deprecating it.
New APIs:
* `@string.View.rev_iter`
* `String::char_at`

refactor(@string.View): API update

---

array/array.mbti
array/fixedarray.mbt
builtin/builtin.mbti
builtin/fixedarray.mbt

`Eq` is a super trait of `Compare`. However, the implementation of `Eq` for `FixedArray` is in `@array`, while the implementation of `Compare` for `FixedArray` is in `@builtin`. This would result in an incomplete implementation of `Compare` within `@builtin`. Previously, this problem is unnoticed due to a compiler bug.
This PR moves `impl Compare for FixedArray` to `@moonbitlang/core/array` to resolve the incomplete implementation issue.

move `Compare` impl of `FixedArray` to its own package

---

cmp/cmp.mbt
cmp/cmp.mbti
cmp/cmp_test.mbt
cmp/moon.pkg.json

Mirrors Rust's [max_by_key](https://doc.rust-lang.org/std/cmp/fn.max_by_key.html#) and [min_by_key](https://doc.rust-lang.org/std/cmp/fn.min_by_key.html#) functions.

feat: add `@cmp.(max|min)imum_by_key`

---

builtin/bigint_nonjs.mbt
builtin/builtin.mbti
builtin/bytes.mbt

This commit removes the deprecated `deep_clone` method from the `BigInt` implementation and replaces it with a new `copy` method. Additionally, it updates the `Bytes` module by removing deprecated methods `sub_string` and `to_string`, promoting the use of `to_unchecked_string` instead. These changes aim to streamline the API and encourage the adoption of newer, more efficient methods.

refactor: remove deprecated functions and introduce new `copy` method for `BigInt`

---

prelude/prelude.mbt
prelude/prelude.mbti

some new traits were added to `@builtin` since the introduction of `@prelude`. This PR add alias for these new traits into `@prelude`

synchronize `@prelude` with `@builtin`

---

buffer/buffer.mbt
bytes/bytes.mbti
bytes/moon.pkg.json
bytes/view.mbt
bytes/view_test.mbt

This PR adds the following two methods to `@bytes.View`:
1. `bytes`: Returns the underlying `Bytes`.
2. `start`: Returns the start index of this view.
These two functions can be helpful when passing MoonBit `@bytes.View` to the C side without creating a new `Bytes` object.
For example, the declaration of the `write` syscall on Unix is as follows:
```c
ssize_t write(int fd, const void *buf, size_t n_byte);
```
If we could retrieve the underlying bytes from `@bytes.View`, we can obtain a pointer to
the start of the `@bytes.View` on the C side:
```c
int moonbit_write_wrapper(int fd, const void *bytes, int start, int length) {
const void *buf = bytes + start;
return write(fd, buf, length);
}
```
And we can bind to such function on MoonBit side as:
```moonbit
extern "c" fn write_wrapper(fd : …
```

feat: add @bytes.View::{bytes,start}

---

int64/README.mbt.md

docs(int64): add `README`

---

test/moon.pkg.json

fix: enable monotonic clock on llvm backend

---

immut/priority_queue/moon.pkg.json
immut/priority_queue/priority_queue.mbt
immut/priority_queue/types.mbt

This PR refactors `@immut/priority_queue.Node` to eliminates wrapper overhead:
```diff
- Branch(A, left~ : T[A], right~ : T[A])
+ Branch(A, left~ : Node[A], right~ : Node[A])
```

refactor: improve @immut/priority_queue

---

strconv/int.mbt

This PR fixes a problem where the constant definitions in `strconv/int.mbt` (e.g. `int_max`)  are inconsistent with those in `strconv/uint` (e.g. `UINT_MAX`)

fix: inconsistent constant

---

string/string.mbti
string/view.mbt
string/view_test.mbt

Part of #1914. This PR only adds methods to View, and does not change other public APIs.

feat(stringview): add missing methods for stringview

---

builtin/builtin.mbti
builtin/linked_hash_map.mbt
builtin/linked_hash_map_test.mbt
sorted_map/README.mbt.md

- **refactor(linked_hash_map): replace match with guard for entry retrieval**
- **update(sorted_map): enhance README with error handling examples and improve key access explanations**
- **feat(linked_hash_map): add `contains_kv` method to check for key-value pairs and improve `contains` implementation**

add contains_kv API to prepare more efficient pattern match compilation

---

immut/array/array.mbt
immut/array/array_wbtest.mbt
immut/array/utils_wbtest.mbt

avoid use closure
And this implementation will be a bit simpler than the previous new_by_leaves, and can also be reused by from_iter
- #1583

refactor: @immut/array.make and @immut/array.makei

---

immut/array/array.mbt
immut/array/array_test.mbt

> That is exactly what Clojure’s persistent vector does, and it is done through balanced, ordered trees.
persistent vector is implemented using balanced tree and share Path during update/insert/remove, using Array as buffer avoids creating a lot of @immut/array[T].
- #1583

improve @immut/array::from_iter

---

double/moon.pkg.json

For tests in the core, coders shall explicitly import the packages used in the test driver, except for `@builtin`.
The driver for tests with arguments used `@test`, which has been imported. Since `moon` introduced the benchmark mechanism in the same driver, an additional `@bench` import is required.
It's also required to allow warning `29` (unused package) as only newer `moon` will actually use this package in its driver.
This is related to https://github.com/moonbitlang/moon/pull/751.
This PR should be merged immediately before next pre-release to minimalize the duration of disabling PR unused package warnings ~~broken stable CI~~. Only after this PR merged, can PR https://github.com/moonbitlang/moon/pull/751 pass its own CI and then been merged. Merge …

fix: import `@bench` when using tests with arguments

---

immut/hashmap/HAMT.mbt
immut/hashmap/HAMT_test.mbt
immut/hashmap/hashmap.mbti
immut/sorted_map/README.mbt.md
immut/sorted_map/map_test.mbt
immut/sorted_map/sorted_map.mbti
immut/sorted_map/utils.mbt

We will unify the APIs to: 
- `get` : return `V?`
- `op_get` : return `V` directly
The `lookup` of `immut/hashmap` was just introduced so there's no need for deprecation phase.

refactor(immut/map): unify lookup to get

---

bytes/bytes_pattern_test.mbt

The `StringBuilder::write_char` is unicode-aware, there's no need UTF16 handling.
The previous implementation accidentally pass tests, but might lead users to misunderstand the `StringBuilder::write_char`.

fix(bytes_pattern_test): remove unnecessary utf16 logic

---

string/methods.mbt
string/string.mbt
string/string.mbti

I missed the `contains` function when migrate String's APIs to use the `View` type for parameters. This PR changes the parameter's type of `contains` to `View` and add this method for `View`.

feat(stringview): add contains method

---

bench/bench.mbt
bench/bench.mbti
bench/types.mbt

Some optimizations may eliminate the calculation that doesn't have side effects. #1974 
A special function can be used to block such an optimization.
In other PLs or libraries,
- [`black_box`](https://doc.rust-lang.org/beta/std/hint/fn.black_box.html) in Rust,
- [`DoNotOptimize`](https://github.com/google/benchmark/blob/c19058b4e5ebab2f3cfe79c5267c28e1654e6c6a/test/donotoptimize_test.cc) in Google Benchmark
- [`runtime.Keep`](https://github.com/golang/go/issues/61179) it's a proposal for Go. Partially replaced by `runtime.KeepAlive` with a poor semantics.
Example:
from
```moonbit
test "batch_bench" (it : @bench.T) {
it.bench(name="fast_fib", fn() { fast_fib(20) |> ignore })
it.bench(name="native_fib", fn() { naive_fib(20) |> ignore })
}
```
to
```moonbit
test "batch_bench" (it : @bench.T) …
```

feat: `@bench.T::keep`

---

builtin/linked_hash_map.mbt
builtin/linked_hash_map_wbtest.mbt

Removed the dedicated `ListNode` wrapper and simplified linked-list pointers directly in `Entry`:  
```diff
priv struct Entry[K, V] {
-  mut idx : Int
+  mut prev : Int?
+  mut next : Entry[K, V]?
mut psl : Int
hash : Int
key : K
}
- priv struct ListNode[K, V] {
-  mut prev : Entry[K, V]?
-  mut next : Entry[K, V]?
- }
```
1. Eliminates the separate `ListNode`, reducing memory overhead.
2. Iteration no longer requires accessing `self.entries` (all links are self-contained in Entry).
3. Preserves the existing cycle prevention mechanism
* In `shift_back`: Requires additional operations to update the `prev` of the next node, introducing potential reduction in cache locality during these operations

perf(linked_hash_map): optimize link list structure

---

builtin/linked_hash_map.mbt
builtin/linked_hash_map_wbtest.mbt

Reference: #2002 
use `prev = -1` for None to improve performance a little bit more

refactor(linked_hash_map): change type of prev and tail to Int

---

list/list.mbt
list/list.mbti
list/list_test.mbt
list/moon.pkg.json
list/panic_test.mbt
list/types.mbt
string/moon.pkg.json
string/string_test.mbt

Reference : #1941 
This PR rewrites the `immut/list` in a stack safe manner by using 'tail modulo constructor' pattern.
Notice that this introduces a few **breaking changes** compared to `immut/list`'s original implementation for API consistency with other packages:
- the argument ordering of the high order function parameter of `rev_foldi` `rev_fold` `scan_right` is changed so that the accumulator always come before the visited argument: `(i, accumulator, element) -> result` or `(accumulator, element) -> result`
- the semantic of the index of `rev_foldi` is changed: it used to be the index of the visited element in the list, and now it is the index of the visiting order.

refactor: add new stack safe list implementation

---

builtin/builtin.mbti
builtin/intrinsics.mbt
builtin/intrinsics_test.mbt
builtin/iter_test.mbt

- **add Int::to_char safe API**
- **add Int::unsafe_to_char**

add Int::(unsafe)_to_char

---

builtin/builtin.mbti
builtin/iter.mbt
builtin/iter_test.mbt

Related #1866
Note that we may want a labelled argument `offset` or something similar in the future to avoid computing the addition every time.

feat(iter): add mapi

---

tuple/README.mbt.md
tuple/tuple.mbt
tuple/tuple.mbti

Closes #1787
The reason for deprecation is:
1. it can be replaced with matrix functions
2. the order of parameters is not nature
We may or may not add back the version where the parameters are swapped.

chore(tuple): deprecate `map_xxx` for tuple

---

strconv/int.mbt
strconv/int_test.mbt

Fixes #2006 
This PR simplifies the logic:
- if base is not defined, detect the base with prefix
- otherwise, remove prefix for 2/8/16-based if there were one
Thus this breaks some exisiting behaviour. For example:
`0x01` with `base=3` was considered `bad base` because `0x` does not match `3`. Now it is considered `bad syntax` because `x` exceeds the character set allowed for base `3`.

fix(strconv): adjust the logic for validating base

---

list/list.mbt

reader not need to check this function whether is tail recursion

refactor(@list.fold): use loop for code readbility

---

builtin/builtin.mbti
builtin/iter.mbt
builtin/iter_test.mbt

implement Iter::group_by

---

string/string.mbt

Clarify the time complexity of `String::char_at`

doc(string): add doc for String::char_at

---

builtin/array.mbt
builtin/array_block.mbt
builtin/arraycore_js.mbt
builtin/arraycore_nonjs.mbt
builtin/arrayview.mbt
builtin/builtin.mbti
builtin/bytes.mbt
builtin/intrinsics.mbt
builtin/linked_hash_map.mbt
builtin/option.mbt
builtin/show.mbt
builtin/string.mbt

remove all  `@alert` pragmas, use `#internal` attribute instead

refactor: use internal attribute for safety messages

---

string/methods.mbt
string/string_test.mbt

fix(string): split and then join should be identity

---

builtin/builtin.mbti
builtin/linked_hash_map.mbt
hashmap/hashmap.mbt
hashmap/hashmap.mbti
immut/hashmap/HAMT.mbt
immut/hashmap/hashmap.mbti
immut/sorted_map/sorted_map.mbti
immut/sorted_map/utils.mbt
json/json.mbt
sorted_map/map.mbt
sorted_map/sorted_map.mbti

In the future, we will have `op_get` return `V` instead of `V?` and `get` return `V?`.
For other functions, if there are a 'unsafe' implementation and a 'safe', the unsafe one will be named as `unsafe_xxx`. Otherwise it will just named as it is.
cc @Yoorkin the `json.mbt` emitted two same warnings

refactor(map): deprecate op-get for future migration

---

array/array.mbt
array/array_test.mbt

Based on the comment: https://github.com/moonbitlang/core/commit/0783012aa805c255788bfa2b38fe196d7edb8ef1#r156454436
Notice that this changes the behavior when the user modifies the Array after creating the zip.

feat: improve array zip_to_iter2 to be fault tolerant

---

builtin/array.mbt
builtin/arraycore_js.mbt
builtin/arraycore_nonjs.mbt
builtin/arrayview.mbt
builtin/bytes.mbt
builtin/intrinsics.mbt
builtin/json_test.mbt
builtin/linked_hash_map.mbt
builtin/option.mbt
builtin/string.mbt
bytes/view.mbt
deque/deque.mbt
deque/moon.pkg.json
hashmap/hashmap.mbt
hashset/hashset.mbt
immut/array/array.mbt
immut/array/moon.pkg.json
immut/list/list.mbt
immut/priority_queue/priority_queue.mbt
immut/sorted_set/immutable_set.mbt
list/list.mbt
prelude/moon.pkg.json
prelude/prelude.mbt
prelude/prelude.mbti
priority_queue/priority_queue.mbt
queue/queue.mbt
random/random.mbt
string/deprecated.mbt

- Remove unused alert and internal attributes
Note that any member with the `#internal` attribute will emit warnings for the user (in another module).
- fix deprecated annotations
There are some changes in `@prelude` package. @Guest0x0

remove unused alert and internal attribute

---

builtin/iter_test.mbt
deque/deque_test.mbt

We plan to deprecate the behavior of using constructor with payload as function directly, in favor of the partial application syntax. Reasons:
- if we allow constructor as function, there will be an inconsistency between constructor with payload (function) and constructor without payload (constants)
- if we forbid constructor as function, code readers can visually tell whether a constructor is constant directly
- constructors allow type-directed resolution, allowing constructor as function makes this part of typing logic complicated
- for cases where constructors are indeed used as first class function directly, the partial application syntax provides a good alternative
This PR removes usage of constructor as first class function directly in core, to adapt the upcoming compiler update.

fix constructor as function

---

builtin/builtin.mbti
builtin/console.mbt
builtin/intrinsics.mbt
bytes/bytes_pattern_test.mbt
double/internal/ryu/ryu.mbt

`moon test --enable-coverage` panic again
```
git/core$moon test --enable-coverage
thread 'main' panicked at /Users/runner/.cargo/git/checkouts/n2-e90a381ad9753ef2/3e74c79/src/work.rs:756:17:
BUG: no work to do and runner not running
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
cc @Young-Flash

feat: add Byte::to_char method for byte to character conversion

---

immut/list/list.mbt
list/list.mbt

perf: use array as buffer

---

immut/sorted_set/generic.mbt
immut/sorted_set/immutable_set.mbt
immut/sorted_set/immutable_set_test.mbt
immut/sorted_set/types.mbt
list/README.mbt.md
sorted_set/types.mbt

`core` is module, a module contains many packages in moonbit.

docs: fix typos

---

byte/byte.mbt
byte/byte.mbti
byte/byte_test.mbt

Byte is widely used in files, protocols, and data structures. Counting the number of 1-bits in a byte is a common requirement in many scenarios where bitwise operations or bit statistics are needed, and similar functions are also available in the standard libraries of other programming languages.
[Rust count_ones](https://doc.rust-lang.org/std/primitive.u8.html#method.count_ones)
[C++ popcount](https://en.cppreference.com/w/cpp/numeric/popcount)

feat(Byte): add count_ones method

---

json/from_json.mbt
json/json.mbti
json/json_path.mbt
list/list.mbt
list/list.mbti
list/list_test.mbt

- **use loop with stack**
- **fix: reorder parameters in `fold_with_key` function signature for consistency**
- **add more tests coverage for list**
- **feat: implement ToJson trait for JsonDecodeError and JsonPath**

add json_path to json and more tests for list

---

array/view.mbt

```moonbit
test (b : @bench.T) {
let a = (1).until(1000).to_array()[:]
fn old() {
b.keep(a.to_array())
}
fn new() {
b.keep(a.to_array2())
}
b.bench(name="old", old)
b.bench(name="new", new)
}
```
run `moon bench -p moonbitlang/core/mytest -f 1.mbt -i 0 --target all`:
```
name time (mean ± σ)         range (min … max) 
old   11.39 µs ±   1.31 µs     9.63 µs …  13.55 µs  in 10 ×   8578 runs
new    6.70 µs ±   0.71 µs     6.02 µs …   7.73 µs  in 10 ×  11768 runs
Total tests: 1, passed: 1, failed: 0. [js]
bench moonbitlang/core/mytest/1.mbt::0
name time (mean ± σ)         range (min … max) 
old    6.40 µs ±   1.16 µs     4.99 µs …   7.96 µs  in 10 ×  19649 runs
new    1.90 µs ±   0.18 µs     1.68 µs …   2.25 µs  in 10 ×  49227 runs
Total tests: 1, passed: 1, failed: 0. [wasm-gc]
bench …
```

perf(arrayview): use `for` in `to_array`

---

builtin/array_block.mbt

if `dst_offset + len > dst.length()`, dest array can automatically grow.
Warning: if `dst_offset > dst_length()`, use `unsafe_grow_to_length` would create uninitialized element.

fix: docs in Array::blit_to

---

immut/sorted_map/utils.mbt
immut/sorted_set/generic.mbt
sorted_map/map.mbt
sorted_set/set.mbt

```moonbit
test (b : @bench.T) {
let a : @sorted_set.T[Int] = @quickcheck.samples(1000).last().unwrap()
fn old() {
b.keep(a.iter().count())
}
fn new() {
b.keep(a.iter_new().count())
}
b.bench(name="old", old)
b.bench(name="new", new)
}
```
---
in `sorted_set`:
```
// bench moonbitlang/core/mytest/1.mbt::0
// name time (mean ± σ)         range (min … max)
// old   19.39 µs ±   1.62 µs    17.67 µs …  22.35 µs  in 10 ×   5262 runs
// new    9.70 µs ±   0.91 µs     8.48 µs …  11.02 µs  in 10 ×  10418 runs
// Total tests: 1, passed: 1, failed: 0. [wasm]
// bench moonbitlang/core/mytest/1.mbt::0
// name time (mean ± σ)         range (min … max)
// old   10.85 µs ±   0.61 µs     9.86 µs …  11.94 µs  in 10 ×  10485 runs
// new    5.26 µs ±   0.51 µs     4.32 µs …   6.02 µs  in 10 ×  21438 runs
// …
```

perf(sorted_map/set): use tail call and reduce closure allocation in `iter`

---

array/array.mbt
array/array_test.mbt
string/string.mbt
string/string.mbti
string/string_test.mbt

refactor: deprecate `@string.concat`

---

builtin/builtin.mbti
builtin/iter.mbt
builtin/iter_test.mbt

refactor: deprecated Iter::apend and Iter::prepend

---

abort/abort.mbt

/cc @Young-Flash `moon fmt` omitted the package.

fix: move type arguments after fn keyword in abort

---

builtin/arrayview.mbt
strconv/int.mbt
string/view.mbt

* Added #builtin.valtype mainly for documentation purpose
* Deprecated `@string.StringView` in favor of `@string.View`

add proper attribute to view types

---

bigint/bigint.mbt
bigint/bigint.mbti
bigint/bigint_js.mbt
bigint/bigint_nonjs.mbt
bigint/bigint_nonjs_wbtest.mbt
bigint/bigint_test.mbt

This PR implements some utilities for comparing bigints with int/int64. These utilities can be used to implement more efficient pattern matching for bigint in the compiler.

feat(bigint): add compare_int and compare_int64

---

array/array_test.mbt
immut/priority_queue/priority_queue_test.mbt
math/prime_test.mbt
priority_queue/priority_queue_test.mbt
random/README.mbt.md
random/random.mbt
random/random.mbti
random/random_test.mbt

refactor: introduce Source trait for random generator

---

immut/hashmap/HAMT.mbt
immut/hashmap/HAMT_test.mbt
immut/hashmap/hashmap.mbti
immut/sorted_map/README.mbt.md
immut/sorted_map/map_test.mbt
immut/sorted_map/sorted_map.mbti
immut/sorted_map/utils.mbt

+ Rename `elems()` to `values()` for consistency with `Map`.  
+ `(key, value)` pairs are called elements, but the second item is specifically called value
+ Other languages (e.g., Rust/JS/Python) also use `values()`
​​Note:​​
This PR is based on #2123 - If you want to merge this, please merge #2123 first

Rename `elems` to `values` in immut/sorted_map and hash_map

---

builtin/builtin.mbti
builtin/iter.mbt
builtin/iter_test.mbt

Closes #1319 
The naming is chosen as such because:
- we have `mapi` `eachi` where the `i` signifies the fact that an index is added as parameter
- we can't write `for i, v in [].iter()` anyway, so there's no ambiguity.
Update: we will use `iter2` to return `Iter2[Int, T]` to align with existing behaviors. As of `Iter[(K, V)]`, users can just use a pattern matching `let (k, v) = elem`.

feat(iter): add iter2

---

quickcheck/arbitrary.mbt

MoonBit currently allows calling `impl` of foreign type with dot syntax/`TypeName::`, but only inside current package. This behavior was added to allow locally extend dot syntax of foreign type, but is not refactor safe (if upstream add a method of the same name, behavior of downstream code will silently change), so we decided to deprecate and remove this feature in the future.
This PR removes usage of this behavior in core.

remove use of local impl as method

---

test/test.mbt
test/test.mbti

It is defined for the initial benchmark utility. Later, we migrated to using `@bench.T` and forgot to remove this function.
We shall deprecate it first.

misc: deprecate`@test.bench`

---

error/error.mbt
error/error.mbti
error/error_test.mbt
error/moon.pkg.json

the latest release of MoonBit introduces primitive for converting `Error` to json. This PR introduces this primitive to core

impl ToJson for Error

---

builtin/array.mbt
builtin/fixedarray.mbt
builtin/string.mbt
deque/deque.mbt
list/list.mbt
option/option.mbt
queue/queue.mbt
random/random.mbt
tuple/tuple.mbt

- Added test blocks for documentation examples in the `array`, `fixedarray`, `string`, `deque`, `list`, `option`, `queue`, `random`, and `tuple` modules to ensure examples are validated.
- Improved clarity and consistency in documentation by including tests for functions like `rev_each`, `fill`, `charcode_at`, `front`, `from_array`, `when`, `shuffle`, and others.
- Ensured that all new tests reflect the expected behavior and outputs as described in the documentation.

Update documentation tests across various modules

---

string/methods.mbt

```moonbit
///|
test (it : @bench.T) {
let str = String::make(10000, 'a') + "b" + "😀"
it.bench(name="contains_char_v1/bmp", fn() {
it.keep(contains_char_v1(str, 'b'))
})
it.bench(name="contains_char_v2/bmp", fn() {
it.keep(contains_char_v2(str, 'b'))
})
it.bench(name="contains_char_v1/surrogate", fn() {
it.keep(contains_char_v1(str, '😀'))
})
it.bench(name="contains_char_v2/surrogate", fn() {
it.keep(contains_char_v2(str, '😀'))
})
}
///|
pub fn contains_char_v1(haystack : @string.View, needle : Char) -> Bool {
haystack.iter().any(fn(ch) { ch == needle })
}
///|
pub fn contains_char_v2(haystack : @string.View, needle : Char) -> Bool {
let len = haystack.length()
// Empty
if len == 0 {
return false
}
let needle = needle.to_int()
if needle <= 0xFFFF {
// Search BMP
for i in 0..<len {
if …
```

improve `contains_char`

---

builtin/iter_test.mbt

- Introduced a new test case for the `iter2` method in the `iter_test.mbt` file to validate its behavior.
- Included assertions to check that the indices and values match during iteration.
- Added a TODO comment to address a known issue in the next release.

Add test for `Iter::iter2` functionality

---

array/array.mbt
array/array.mbti
array/array_test.mbt

Based on #2187  
- unzip: Splits an array of tuples into two arrays of the tuple’s components.
- map_unzip: Applies a function to each element and splits the result into two arrays.
- map_unzip3: Applies a function to each element and splits the result into three arrays.
- All methods are generic and support tuple elements of any types.
- All new APIs are covered by comprehensive unit tests.
- No existing functionality is changed.
let arr = [(1, "a"), (2, "b")]
let (nums, strs) = arr.unzip()          // [1, 2], ["a", "b"]
let arr2 = [1, 2, 3]
let (x, y) = arr2.map_unzip(fn(v) { (v, v * 10) }) // [1,2,3], [10,20,30]
- Fully backward compatible.
- Only adds new API.
- All existing and new tests pass.

feat(array): add unzip and tests  (closes #2187)

---

ref/ref.mbt
ref/ref.mbti
ref/ref_test.mbt

Note: `Ref::pretect` requires special modifications.

Refactor: Update the functions in @ref to handle error polymorphism

---

bigint/bigint_nonjs.mbt
builtin/double_to_int.mbt
builtin/double_to_int64_native.mbt
builtin/double_to_int_wasm.mbt
builtin/int64_nonjs.mbt
builtin/intrinsics.mbt

Skip some of the doc tests that behavior inconsistently across backends / OS, notably native backend on Windows.

internal: skip inconsistent test case

---

builtin/builtin.mbti
builtin/iter.mbt
immut/array/array.mbt
immut/array/array.mbti
immut/array/tree.mbt
immut/hashmap/HAMT.mbt
immut/hashmap/bucket.mbt
immut/hashmap/hashmap.mbti
immut/hashset/HAMT.mbt
immut/hashset/bucket.mbt
immut/hashset/hashset.mbti
immut/internal/sparse_array/sparse_array.mbt
immut/internal/sparse_array/sparse_array.mbti
immut/list/list.mbt
immut/list/list.mbti
immut/sorted_map/map.mbt
immut/sorted_map/sorted_map.mbti
immut/sorted_set/immutable_set.mbt
immut/sorted_set/sorted_set.mbti

This PR enhances error handling across various functions in the codebase, allowing for proper error propagation in higher-order functions.
- **Immutable Array**
- `each`
- `eachi`
- `makei`
- `fold`
- `fold_left` and `fold_right`
- `rev_fold`
- `map`
- **Immutable HashMap**
- `each`
- `filter`
- `fold` and `fold_with_key`
- `intersection_with`
- `map` and `map_with_key`
- `union_with` (updated to propagate errors from merging function)
- **Immutable HashSet**
- `each`
- **Legacy Immutable List**
- `all`
- `any`
- `drop_while`
- `each` and `eachi`
- `filter`
- `find` and `findi`
- `flat_map`
- `fold` and `foldi` and `rev_fold` and `rev_foldi`
- `fold_left` and `fold_lefti`
- `fold_right` and `fold_righti`
- `mapi` and `rev_map`
- `scan_left` and `scan_right`
- `unfold`
- **Immutable Sorted …

Add Error Polymorphism to High-Order Functions in `@immut` Modules

---

CONTRIBUTING.md

define both method and function syntac has been deprecated.

fix: example in CONTRIBUTING.md

---

bigint/bigint_nonjs.mbt
bigint/bigint_nonjs_wbtest.mbt
json/internal_types.mbt
random/random.mbt
set/linked_hash_set.mbt

This PR removes some unused `derive`, using the to-be-released unused warning support for trait implementations. One problematic case is `derive` implementations that are only used in whitebox tests, they will be reported as unused. There are two workaround to this:
- turn the `derive` into a manual implementation in `_wbtest.mbt`
- add a inline test for the `derive`

fix unused `derive`

---

random/internal/random_source/moon.pkg.json
random/internal/random_source/random_source.mbti
random/internal/random_source/random_source_chacha.mbt
random/random.mbt

This PR is part of #2333
1. Flatten the structural. Remove `struct ChaCha8 { state : State }` and rename `State` to `ChaCha8`.
2. Improve api in ChaCha8::next. Return an `UInt64?` instead of `(UInt64, Bool)`.
3. Simplify.

chore(random_source)

---

random/internal/random_source/random_source.mbti
random/internal/random_source/random_source_chacha.mbt

1. Using `FixedArray[UInt]` for `buffer` and `seed` to avoid copy.
2. Simplify.
3. replace magic numbers with constants.
- In ChaCha8, a chunk = 64bit. buffer is 32 chunk, and seed is 4 chunk.

perform(random_source): using FixedArray[UInt] for buffer and seed to avoid copy

---

string/view.mbt

`@string.View::char_at` is an O(1) method. This PR fixed the documentation.

doc(string/view): fix documentation

---

builtin/array.mbt

The definition of `self.clear()` is just `self.unsafe_truncate_to_length(0)`.

chore(array): truncate

---

hashmap/hashmap.mbt
hashset/hashset.mbt
immut/priority_queue/priority_queue.mbt
immut/priority_queue/priority_queue.mbti
immut/sorted_map/map.mbt
immut/sorted_set/deprecated.mbt
immut/sorted_set/immutable_set.mbt
immut/sorted_set/sorted_set.mbti
set/linked_hash_set.mbt
sorted_map/map.mbt
sorted_set/set.mbt
sorted_set/sorted_set.mbti

This PR removes unused trait bound in core, using unused warning for trait bounds, which is currently under development in MoonBit compiler.

remove unused trait bound

---

list/README.mbt.md
list/deprecated.mbt
list/list.mbt
list/list.mbti
list/list_test.mbt

we need to align type signature with `@list.head`
**current API**
```moonbit
pub fn[A] tail(self : T[A]) -> T[A]
```
**expected API**
```moonbit
pub fn[A] tail(self : T[A]) -> T[A]?
```

fix(list): deprecate @list.tail

---

strconv/decimal.mbt
strconv/double.mbt
strconv/double_test.mbt
strconv/traits.mbt

Replace
```mbt
test {
try exp catch { _ => panic() }
}
```
to
```mbt
test {
exp
}

simplify error handling in parse tests

---

builtin/builtin.mbti
builtin/uninitialized_array.mbt
deque/deque.mbt
deque/deque.mbti
deque/deque_test.mbt

fix(deque): implement drain and flatten properly

---

rational/rational.mbt
rational/rational_test.mbt

1. Fixed invariant violations in the `arbitrary` impl
2. Optimized implementation using invariants
3. Removed duplicate tests

rational: fix invariants, simplify implementation, clean up tests

---

deque/deque.mbt
deque/deque.mbti
deque/deque_test.mbt

This PR adds `binary_search_by` and `binary_search` methods to the Deque implementation, providing efficient O(log n) searching capability for sorted deques.
- Added `binary_search_by` method that accepts a comparator function
- Added `binary_search` convenience method for types implementing `Compare`
- Implemented proper ring buffer index handling
- Added comprehensive unit tests covering:
- Empty deque cases
- Single and multiple element deques
- Wrapped around buffer cases
- Duplicate elements
- Custom comparators

Add binary_search_by and binary_search methods to Deque

---

builtin/builtin.mbti
builtin/json.mbt
json/from_json.mbt
json/internal_types.mbt
json/json.mbt
json/json_encode_decode_test.mbt
json/json_test.mbt
json/lex_main.mbt
json/lex_number.mbt
json/lex_number_test.mbt
json/parse.mbt
json/types.mbt

Closes #1366
This implementation will introduce new field in `Json::Number` to hold the representation of the Json number that can't be put into a `Double`.
The current implementation will decide during parsing, to use the `repr : String?` to hold the representations, if:
- it's an integer (not written with exponential or decimal point) that can't be safely represented by the `Double`
- it's a double that failed parsing
The corresponding value will be +/- inf, which aligns with the behavior of `Json.parse` in JS.
The implementation of `Eq` will compare only the number part and ignore the representation part.

refactor: handle any json number

---

int16/int16.mbt
int16/int16.mbti
int16/int16_test.mbt
int16/moon.pkg.json

This behavior is consistent with Rust's `as`, which first expands to the corresponding bit and then reinterprets it with binary complement.
https://doc.rust-lang.org/reference/expressions/operator-expr.html#numeric-cast

feat(int16): add integer conversion

---

builtin/array.mbt
builtin/array_test.mbt
builtin/builtin.mbti

- Adds new `retain_map` method to `Array` type
- Combines filtering and mapping in a single in-place operation
- Matches behavior of similar functions in other languages (Rust's `retain_mut`, Swift's `removeAll(where:)` with mapping)

feat(Array): add retain_map for in-place filter+map operations

---

builtin/arrayview.mbt
builtin/uninitialized_array.mbt
bytes/view.mbt
string/deprecated.mbt
string/view.mbt

This PR changes the definition of `@array.View` and `@string.View` to abstract types that have been implemented in the compiler in a hard-coded way.

refactor: use view primitives

---

hashmap/hashmap.mbt
hashmap/moon.pkg.json
int/int.mbt
int/int.mbti
set/grow_heuristic.mbt
set/linked_hash_set.mbt
set/moon.pkg.json

This PR adds a `next_power_of_two` fn to the `Int`, which is is particularly useful in systems programming and performance-sensitive applications. Two common use cases are:
1. Memory Allocation Alignment
2. HashMap Capacity Management
This PR also removed duplicate fn `power_2_above` in the codebase by utilizing this new fn

feat: add next_power_of_two fn

---

string/methods.mbt

the rationale is that counting char_length is not enough, we need do more complex graphime clustering.
Quote from AI
>Bottom Line
I'd follow JavaScript's semantics because:
It maintains consistency with your UTF-16-based API
It's predictable and performant
Most real padding use cases don't involve emojis
You can always add character-aware variants later if needed
The current design mixing UTF-16 offsets with character counting creates more confusion than the occasional visual incorrectness with emojis.
cc @Yu-zh

align String::pad_start with JS semantics (not counting char length)

---

builtin/builtin.mbti
builtin/deprecated.mbt
builtin/int.mbt
builtin/string.mbt
string/methods.mbt
string/string.mbt
string/utils.mbt
string/view.mbt

- Add Int::is_leading_surrogate() and Int::is_trailing_surrogate() methods
- Replace all function calls with method calls throughout the codebase
- Remove duplicate function definitions from builtin/string.mbt and string/utils.mbt
- Clean up unused surrogate range constants
This provides a more consistent API by making these UTF-16 surrogate checks
available as methods on the Int type itself.

refactor: migrate is_leading_surrogate/is_trailing_surrogate to Int methods

---

array/blit.mbt
builtin/bytes.mbt

Performance: use intrinsic for `blit` between `FixedArray` and `Bytes` / `BytesView`, and simplify the implementation

perf: improve blit_from_bytes(view)

---

deque/deque.mbt

The simplifications include:
1. Using a guard clause for the empty deque check, which makes the code flatter
2. Replacing the counter variable with a cleaner range-based for loop
3. Removing unnecessary variable assignments and comments

chore: simplify deque rev_inplace implementation

---

string/methods.mbt
string/string.mbti

- Add View::strip_prefix() and View::strip_suffix() methods
- Add View::to_array() and View::to_bytes() methods
- Add missing String::strip_prefix() method
- Improve View::to_bytes() to work directly with view range
- Update method documentation with better examples
- Regenerate string.mbti with new method signatures
This achieves full API symmetry between String and StringView types,
allowing developers to use the same operations on both types without
losing functionality when working with string views.

feat(string): Add missing View methods for API consistency

---

builtin/bytes.mbt

The boundary check in `FixedArray::blit_from_string` was incorrect, it allowed operations that would later cause array bounds violations. However, I haven't found how to create a unit test that can verify the guard condition: a guard statement without a return value will panic the whole program, but unit tests don't seem to have a way to assert what the panic is.

fix: blit_from_string bound check bug

---

bytes/bytes_test.mbt

The bleeding version of `match .. using regex` now supports matching `String` directly, so if the matched object is a string literal, the semantic will change from matching `Bytes` to matching `String`. If `moonbitlang/core/string` is not imported (this can only happen in core itself, most users should not worry about this), the compiler will crash. This PR migrate tests to use `b"..."` literal, so that they are compatible with future support for matching `String` with regex.

make using regex test compatible with future `String` support

---

string/deprecated.mbt
string/methods.mbt
string/string.mbti

- Marked `starts_with` and `ends_with` methods as deprecated, suggesting the use of `strip_prefix` and `strip_suffix` instead.
- Updated documentation to reflect changes and provide examples for the new methods.
- Added aliases for deprecated methods to maintain backward compatibility.

Deprecate string methods and introduce aliases

---

json/from_to_json_test.mbt

```
Error: [0011] Error (warning): Partial match, some hints:
True
Null
False
error: failed when checking
```

fom_json flat trigger warnings

---

builtin/json.mbt
builtin/json_test.mbt
json/from_json.mbt
json/json_test.mbt
json/to_json_test.mbt

Currently, `nan` `+inf` and `-inf` are converted to `null` in the `impl ToJson for Double`. While this corresponds to the behavior of JavaScript, this creates an issue when we want to use `@json.inspect` upon such values.
As a result, we are serializing them to string, which can be recovered from the corresponding `FromJson`.

refactor: serialize nan/inf to string

---

array/fixedarray.mbt
builtin/array.mbt
builtin/bytes.mbt
builtin/hasher.mbt
builtin/traits.mbt
bytes/view.mbt
deque/deque.mbt
immut/array/array.mbt
immut/list/list.mbt
immut/priority_queue/priority_queue.mbt
string/string.mbt
string/view.mbt

This PR updates comments for
1. Hash, making it clear that the current inconsistency between `hash` and `hash_combine` is fine. The TODO notice is removed.
2. Compare, making it clear that we are using [shortlex order](https://en.wikipedia.org/wiki/Shortlex_order) instead of pure lexicographical order.

doc: update comments

---

immut/sorted_map/README.mbt.md
immut/sorted_map/map_test.mbt
immut/sorted_map/sorted_map.mbti
immut/sorted_map/utils.mbt
sorted_map/README.mbt.md
sorted_map/deprecated.mbt
sorted_map/map.mbt
sorted_map/map_test.mbt
sorted_map/sorted_map.mbti

change return type of `@sorted_map.{keys, values}` to `Iter`

---

builtin/builtin.mbti
builtin/linked_hash_map.mbt
builtin/linked_hash_map_wbtest.mbt
hashmap/deprecated.mbt
hashmap/hashmap.mbt
hashmap/hashmap.mbti
hashmap/hashmap_test.mbt
immut/sorted_map/sorted_map.mbti
immut/sorted_map/utils.mbt
immut/sorted_map/utils_test.mbt
sorted_map/deprecated.mbt
sorted_map/map.mbt
sorted_map/map_test.mbt
sorted_map/sorted_map.mbti

refactor(map): align op_get with array

---

builtin/builtin.mbti
builtin/json.mbt
deque/deque.mbt
json/README.mbt.md
json/from_json_test.mbt
json/json_test.mbt
json/json_traverse_test.mbt
json/parse.mbt
json/parse_test.mbt
prelude/prelude.mbt
prelude/prelude.mbti

Note CI fails, because `derive(ToJson)` used `Json::null()` which is not really needed.
CI run `moon check --deny-warn` caught this error, while `moon check` skip this error, due to missing location, 
`moon check --render-no-loc warn` would find this location
cc @lynzrand 
As a temporary workaround, I would keep Json::null for a while

introduce null

---

buffer/buffer.mbti
buffer/sleb128.mbt
buffer/sleb128_test.mbt
buffer/uleb128.mbt

This PR unifies the `Signed` and `Unsigned` and leave only one `Leb128` trait for writing numbers to buffer.

refactor: adapt buffer api

---

array/array.mbt
array/pkg.generated.mbti
builtin/array.mbt
builtin/pkg.generated.mbti

This PR optimizes `makei` in two aspects:
* add `#locals` attribute so that it can be more aggressively inlined
* use `Array::make_uninit` to allocate so that one iteration can be saved for scalar element type.
Out FFT benchmark before this optimization:
With this optimization:

refactor(array): optimize makei

---

immut/priority_queue/priority_queue.mbt
priority_queue/priority_queue.mbt

This PR
1. Inline `binary_search` for `deque` for better performance
2. Use `sort` then `rev_inplace` for `@priority_queue.to_array` for better performance (both immutable version and mutable version)
3. Use a stack to avoid overflow for `@priority_queue.to_array` (both immutable version and mutable version)
Bench: 
```moonbit
///|
test (bench : @bench.T) {
let queue : T[Int] = @quickcheck.samples(10000) |> from_array
bench.bench(name="to_array", fn() { bench.keep(queue.to_array()) })
bench.bench(name="to_array_new", fn() { bench.keep(queue.to_array_new()) })
}
```
Result:
```
bench username/hello/lib/hello.mbt::0
name         time (mean ± σ)         range (min … max) 
to_array        2.35 ms ±   7.29 µs     2.34 ms …   2.36 ms  in 10 ×     43 runs
to_array_new    1.88 ms ±   4.74 µs …
```

perf: inline funcs

---

bytes/bytes_test.mbt

We are changing the syntax of native regex. This experimental syntax will soon be unavailable.

temporarily remove match using regex test

---

bigint/bigint_js.mbt
builtin/int64_js.mbt

The `deny-warn` is disabled so this warning got slip in cc @bobzhang

chore: update shr for js backend

---

json/from_json.mbt
json/from_json_test.mbt

In current main branch, decoding JSON numbers outside the 32‑bit bounds silently truncated:
- Int: values > INT_MAX became INT_MAX, < INT_MIN became INT_MIN
- UInt: negatives became 0, > UINT_MAX became UINT_MAX
This could hide data corruption and make overflow undetectable. 
**Behavioral Difference (Breaking):**
- Code relying on previous clamping / wrap semantics will now receive JsonDecodeError.
- Negative JSON numbers for UInt now produce overflow (not “expected number”) to distinguish representation vs range errors.
**Rationale**
Fail‑fast on invalid data is safer and matches typical JSON decoding expectations in other ecosystems (Rust serde, Go encoding/json, etc.).

fix: resolve json parse int/uint overflow issue

---

builtin/iter.mbt
builtin/iter_test.mbt

In the current implementation, `Iter#take` take an extra element out of the iter. This may lead to extra overhead, expensive resource initialization or race condition in state-shared iterators.
```moonbit
fn[T] Iter::take_fix(self : Iter[T], n : Int) -> Iter[T] {
Iter::new(yield_ => {
// [..take(10,seq), next] would continue
// even if seq has less than 10 elements
// but `for x in [..take(10,seq), next ] { break }` would stop
//
let mut i = 0
let mut r = IterContinue
self.just_run(a => {
i = i + 1
guard yield_(a) == IterContinue else { 
r = IterEnd
return IterEnd 
}
guard i < n else { return IterEnd }
IterContinue
})
r
})
}
///|
test "hot take" {
struct s {
mut i : Int
}
let s = s::{ i: 0 }
let iter = Iter::new(c => while s.i < 5 {
s.i = s.i + 1
guard c(s.i) is IterContinue else { return …
```

fix(builtin): Iter#take take one more element from iter

---

result/pkg.generated.mbti
result/result.mbt

`Result::fold` is inconsistent with other `fold` function such as `Array::fold` and `Iter::fold`.
```moonbit
pub fn[T, E, V] fold(self : Result[T, E], ok : (T) -> V, err : (E) -> V) -> V
```
here is corrected MoonBit version
```moonbit
fn [A,E,B] Result::fold_(self : Result[A,E], init~ : B, f : (B,A) -> B) -> B {
match self {
Ok(value) => f(init, value)
Err(_) => init
}
}
```
Haskell `Either` instance of `Foldable` is similar to this.
here is an example usage for `Either` foldl in Haskell
```haskell
foldl (\acc x -> acc + x) 10 (Right 5)
-- Result: 15
```

deprecate: `Result::fold`

---

result/pkg.generated.mbti
result/result.mbt

**Problem:** The `Result` type was missing three helper functions that exist in `Option`, creating an inconsistency in the API:
* unwrap_or
* unwrap_or_else
* unwrap_or_default
**Solution:** This PR adds the three missing methods to align the `Result` API with `Option`:
* fn[T,E] Result::unwrap_or(Result[T,E], T) -> T - Returns the contained Ok value or the provided default
* fn[T,E] Result::unwrap_or_else(Result[T,E], () -> T raise?) -> T raise? - Returns the contained Ok value or calls the provided closure (lazily evaluated)
* fn[T : Default,E] Result::unwrap_or_default(Result[T,E]) -> T - Returns the contained Ok value or T::default()
**Justification:** Since `Option[T]` and `Result[T, Unit]` are equivalent, having consistent APIs between these types improves developer experience and …

Add missing unwrap methods to Result type for API alignment with Option

---

deque/deque.mbt
deque/deque_test.mbt
deque/pkg.generated.mbti

Issue: #2706
Add functions:
insert, remove

Aligning deque api insert and remove

---

test/pkg.generated.mbti
test/test.mbt

I found that `@test.T::name` is useful for snapshot testing scenarios:
```mbt
/// a local method
fn @test.T::run(self : Self) -> Unit raise {
let input = @fs.read_from_file(base_path + self.name + ".input")
let result = process(input)
self.writeln(result)
self.snapshot(self.name + ".output")
}
test "file1" (t : @test.T) { t.run() }
test "file2" (t : @test.T) { t.run() }
test "file3" (t : @test.T) { t.run() }
```
Following this pattern, it's convenient to add snapshot tests for new input files. Since `@test.T` will likely become an abstract type in the future, let's introduce a `@test.T::name()` method to keep this practice available.

fix: add `@test.T::name()` method

---

builtin/arrayview.mbt
builtin/arrayview_test.mbt
builtin/pkg.generated.mbti

This PR implements taking view from FixedArray.
Solves #1626

Taking view from Fixedarray

---

quickcheck/README.mbt.md
quickcheck/arbitrary_test.mbt
quickcheck/splitmix/random.mbt

- It would generate zero `seed` and `gamma`, which affects randomness

fix(splitmix): remove derived Default for RandomState

---

priority_queue/priority_queue.mbt
priority_queue/types.mbt

Use option struct instead of enum to implement Node. Changed the type of meld from `(Node[A]?, Node[A]?) -> Node[A]?` to `(Node[A], Node[A]) -> Node[A]` to reduce branching.

perf(priority_queue): better option handling

---

immut/sorted_set/external_iterator.mbt
immut/sorted_set/generic.mbt

This PR refactors the `Compare` trait implementation for `SortedSet` to compare sets by **size first**, then by elements lexicographically if sizes are equal.
- Compared sets element-by-element lexicographically
- Example: `{1,2}` vs `{3}` → compared as `[1,2]` vs `[3]` → result: `{1,2} < {3}` (because when first set has more elements, it was considered "greater")
- Compares by **size first**, then by elements if sizes are equal
- Example: `{1,2}` vs `{3}` → size(2) > size(1) → result: `{1,2} > {3}`
- Only compares elements lexicographically when sizes are equal
1. **More intuitive**: Larger sets are naturally "greater than" smaller sets
2. **Performance**: Size comparison is O(1), avoids unnecessary element iteration for different-sized sets
3. **Consistency**: Matches common set …

refactor(immut/sorted_set): Change Compare to compare by size first [BREAKING]

---

builtin/pkg.generated.mbti
builtin/stringbuilder.mbt
builtin/stringbuilder_buffer.mbt
builtin/stringbuilder_test.mbt

This PR adds write_stringview method to StringBuilder for efficient StringView writing without intermediate string allocations.
Key changes:
- New method: StringBuilder::write_stringview(StringView)
- Fixed length calculation bug (end - start, not just end)
- Added comprehensive tests with edge cases
- Added documentation with examples
Performance benefits:
- No intermediate string allocation
- Direct write from viewed portion
- More efficient for string slicing
Testing:
- All 5638 tests pass
- Covers basic writes, multiple writes, empty views, full views, ASCII/Unicode
API addition:
- StringBuilder::write_stringview(StringView) -> Unit
See commit message for full details.

feat(builtin): Add StringBuilder::write_stringview method
