moonbitlang/core

- array/array.mbt
- assertion/assertion.mbt
- bool/bool.mbt
- bytes/bytes.mbt
- char/char.mbt
- double/double.mbt
- int/int.mbt
- int64/int64.mbt
- list/list.mbt
- option/option.mbt
- ref/ref.mbt
- result/result.mbt
- string/string.mbt
- unit/unit.mbt
Fix https://github.com/moonbitlang/core/issues/30
> fix wrong license headers

- list/list.mbt
More useful list operations.
- mapi
- take
- take_while
- drop
- drop_while
- all
- any
- nth_option
- scan
- lookup
> feat: add more list operations

- list/list.mbt
This PR adds `remove` and `remove_at` operations for List.
> feat: add remove and remove_at to List

- list/list.mbt
> feat: useful list transformations

- array/array.mbt
- vec/vec.mbt
- feat: fold and iters for array/vector
- use labeled argument
> feat iter fold

- vec/vec.mbt
> fix: bound check for array

- CONTRIBUTING.md
- README.md
add some description for naming convention.
> update README and CONTRIBUTING

- queue/README.md
- queue/moon.pkg.json
- queue/queue.mbt
Queue based on ~cyclic~ cons list.
> Add new data structure: queue

- array/array.mbt
- vec/vec.mbt
Basically synchronizes the functions that Array and Vec can share.
> feat: new functions to array and comment completion

- .devcontainer/devcontainer.json
- .devcontainer/moonbit-cli/devcontainer-feature.json
- .devcontainer/moonbit-cli/install.sh
- .github/dependabot.yml
Add dev container so that we can review the branch in codespaces
> dev: add dev container

- vec/vec.mbt
here we write `buf.expect()?` and run `moon test -u` it will populate the data automatically, this works great
> expect test show by example

- priority_queue/README.md
- priority_queue/priority_queue.mbt
- priority_queue/types.mbt
> perf: remove min-mode for priority queue

- stack/README.md
> Add README to stack

- queue/queue.mbt
- queue/types.mbt
> tidy up queue

- stack/README.md
- stack/stack.mbt
> Align Stack method names and functionalities with Queue

- list/list.mbt
- stack/stack.mbt
- Fix fold function initialization in Stack module
- no recursive function
> various tweaks

- vec/types.mbt
- vec/vec.mbt
- split types into a separate file
- clean
- clean up and add todos
> tidy up vec (ongoing)

- .github/workflows/check.yml
@bzy-debug can we make bleeding more forgiving, allow it to fail?
> test core on mac bleeding, allow fail

- tuple/README.md
- tuple/moon.pkg.json
- tuple/tuple.mbt
This PR adds functions for binary tuple. But I could not define them as methods because Tuple2 is a foreign type here.
> Tuple utils and document

- .github/workflows/check.yml
enable it after we fix the permission issues cc @lynzrand
> Comment out coverage-check-bleeding workflow

- array/array.mbt
- bytes/moon.pkg.json
- vec/vec.mbt
> feat: add to_list for array/vector

- deque/deque.mbt
- deque/moon.pkg.json
> fix: fix op_get for deque

- priority_queue/priority_queue.mbt
/// Creates a new ~empty~ priority queue from an array.
> chore: correct doc comment of `PriorityQueue::from_array`

- array/array.mbt
- vec/vec.mbt
> feat: concat(op_add) for array/vec

- .github/workflows/check.yml
- .github/workflows/coverage-report-upload.yml
Uses the two-workflow workaround for coverage issue.
Related: #207 (but not closing just yet!)
> Try fixing coverage CI's API error 

- .github/workflows/coverage-report-upload.yml
> Fix coverage CI settings

- immutable_priority_queue/README.md
- immutable_priority_queue/moon.pkg.json
- immutable_priority_queue/priority_queue.mbt
- immutable_priority_queue/types.mbt
#236 
cc @Lampese 
I added a few tweaks, see my last few commits, notably make types immutable
> Immutable pq 

- map/map.mbt
- map/map.mbti
This is needed for writing tests for json
> impl Eq, Debug for map

- result/result.mbti
> add missing result mbti

- char/char.mbt
- char/char.mbti
> Add char util about surrogate

- array/array.mbt
Hi all,
This patch mainly adds many test cases in order to cover the border and improve the test coverage. In my opinion, each test of array should cover the empty array, the array with only one element and the array with more than one elements. This patch also moves some code to their appropriate positions and polishes some comments.
The following commands passed locally. Thanks for taking the time to review.
```
moon check
moon test
moon fmt
moon bundle
```
Best Regards,
-- Guoxiong
> Add test cases about array

- immutable_hashmap/HAMT.mbt
- immutable_hashmap/bitset.mbt
- immutable_hashmap/bucket.mbt
- immutable_hashmap/moon.pkg.json
- immutable_hashmap/sparse_array.mbt
- tweak
- refactor test
- make to singleton
- option used in test
- tweak
> tweak hamt

- _typos.toml
> ci: ignore typos in string literals

- string/moon.pkg.json
- string/string.mbt
- string/string.mbti
> add as_iter method for string

- int/int_test.mbt
- int/moon.pkg.json
> test test_import

- .github/workflows/check.yml
Fix https://github.com/moonbitlang/core/issues/339
> fix license header check too slow

- immutable_set/immutable_set.mbt
- immutable_set/immutable_set_test.mbt
- immutable_set/moon.pkg.json
- immutable_set/types.mbt
> Refactor immutable set to use labeled enum

- immutable_set/generic.mbt
- immutable_set/immutable_set.mbti
- immutable_set/moon.pkg.json
- refactor immutable set
- add some tests
- add @set.as_iter an example, note the efficiency could be improved later
> add @set.as_iter as an example

- .github/workflows/check.yml
- array/moon.pkg.json
- array/sort.mbt
- array/sort_by.mbt
- array/utils.mbt
- no deps on math
- restore moon info
Note we should make `max` and `min` a builtin function(with intrinsics) support
> less dep for array

- vec/moon.pkg.json
- vec/sort.mbt
- vec/sort_by.mbt
- vec/sort_by_test.mbt
- vec/sort_test.mbt
- vec/vec.mbt
- vec/vec.mbti
- vec/vec_test.mbt
- vec/view.mbt
- vec/view_test.mbt
- Move all tests into the test file.
- Add some tests.
- Add `as_iter` method.
> Improve the test coverage of `vec` package and add `as_iter`

- tuple/moon.pkg.json
- tuple/tuple.mbt
- tuple/tuple_show.mbt
- tuple/tuple_test.mbt
- Move all tests to a test file.
- Move `assertion` to test_import.
- Add some tests.
> Improve test coverage of `tuple`

- bytes/bytes_test.mbt
- bytes/moon.pkg.json
- Move all tests to a test file.
- Move assertion to test_import.
- Add some tests.
> Improve test coverage of `bytes`

- time/util.mbt
this crash the wasm-gc backend
> fix a bad condition

- vec/vec.mbt
- vec/vec.mbti
- vec/vec_test.mbt
The behavior of map/mapi is not normal in Vec, they are not immutable.
At the same time, I would like to inquire whether the map implemented by this inplace should be implemented?
> tweak Vec.map/mapi

- immutable_hashmap/HAMT.mbt
- immutable_hashmap/HAMT_test.mbt
- immutable_hashmap/bucket.mbt
- immutable_hashmap/immutable_hashmap.mbti
- immutable_hashmap/moon.pkg.json
> add HAMT::as_iter

- linked_hashmap/impl.mbt
- linked_hashmap/impl_test.mbt
- linked_hashmap/linked_hashmap.mbti
- linked_hashmap/types.mbt
> Remove hasher for linked hash map

- hashset/hashset.mbt
- hashset/hashset.mbti
- hashset/hashset_test.mbt
- hashset/types.mbt
> Remove hasher for hash set

- list/list.mbt
- list/list_test.mbt
- list/moon.pkg.json
- Use `inspect`
- Move test cases to isolated file `list_test.mbt`
- Improve coverage
> Improve list test cases

- int64/int64.mbt
fix the breakage introduced by the byte change https://github.com/moonbitlang/core/pull/405
See also #414.
> fix int64 byte

- json/internal_types.mbt
- json/json.mbt
- json/json.mbti
- json/json_test.mbt
- json/lex_main.mbt
- json/lex_misc.mbt
- json/lex_number.mbt
- json/lex_string.mbt
- json/moon.pkg.json
- json/parse.mbt
- json/parse_error_test.mbt
- json/parse_test.mbt
- json/types.mbt
- json/utils.mbt
Closes #435 
Ports from moonbitlang/x/json5, modify the parser and tests according to the [rfc7159](https://www.rfc-editor.org/rfc/rfc7159.html) standard.
> Add json parser

- array/moon.pkg.json
- bigint/moon.pkg.json
- bytes/moon.pkg.json
- hashmap/moon.pkg.json
- hashset/moon.pkg.json
- immutable_hashmap/moon.pkg.json
- int/moon.pkg.json
- iter/moon.pkg.json
- linked_hashmap/moon.pkg.json
- map/moon.pkg.json
- tuple/moon.pkg.json
> internal: change snake_case to kebab-case

- hashmap/hashmap.mbti
- hashmap/hashmap_test.mbt
- hashmap/moon.pkg.json
- hashmap/utils.mbt
- Add to_array method
- Use Array.fill in clear method
> Tweak HashMap

- linked_hashmap/impl_test.mbt
- linked_hashmap/linked_hashmap.mbti
- linked_hashmap/moon.pkg.json
- linked_hashmap/utils.mbt
- Add to_array method
- Use Array.fill in clear method
> Tweak LinkedHashMap

- .github/workflows/check.yml
@Young-Flash can you help finish the integration of --deny-warn
> no warn on core

- hashmap/README.md
- hashset/README.md
- linked_hashmap/README.md
follow up of: https://github.com/moonbitlang/core/pull/393
> remove hasher in docs

- priority_queue/moon.pkg.json
- priority_queue/priority_queue.mbt
- priority_queue/priority_queue_test.mbt
- priority_queue/types.mbt
> Refactor PriorityQueue with mutable labeled enum

- linked_hashmap/impl.mbt
- linked_hashmap/moon.pkg.json
- linked_hashmap/pattern_test.mbt
- add a test for pattern
- remove option dependency
> remove option deps for linked hashmap

- linked_hashmap/impl.mbt
- linked_hashmap/impl_test.mbt
- linked_hashmap/types.mbt
- linked_hashmap/utils.mbt
cc @yj-qin 
use FixedArray for hashmap
> tweak hashmap layout

- hashmap/hashmap.mbt
- hashmap/hashmap_test.mbt
- hashmap/types.mbt
- hashmap/utils.mbt
- Remove the `Empty` enum of  the `Entry`
- Use `FixedArray`
> Refactor HashMap

- hashmap/hashmap.mbt
- hashmap/hashmap_test.mbt
TODO:
new(size_hint:Int=..)
make sure the size is always positive and to the power of 2, so the logic can be simpliied
> add todo notes and remove abs which is not needed

- hashmap/hashmap.mbt
- hashmap/hashmap.mbti
- hashmap/hashmap_test.mbt
- hashmap/types.mbt
1. add a labeld argument for capacity_hint, make sure the size is always 2^n and positive so the boundary can be simplified
> simplify hashmap

- builtin/builtin.mbti
- builtin/linkedhashmap.mbt
- builtin/linkedhashmap_test.mbt
- Provide a capacity hint parameter
- Simplify some methods
> Simplify LinkedHashMap

- builtin/linkedhashmap.mbt
- builtin/linkedhashmap_test.mbt
- hashmap/hashmap.mbt
- tweak
- clean up power_2_above
> clean up power_2_above

- builtin/LinkedHashMap.md
- builtin/builtin.mbti
- builtin/linkedhashmap.mbt
- builtin/linkedhashmap_test.mbt
> rename LinkedHashMap into Map

- builtin/traits.mbt
> fix compare trait comment

- array/array.mbt
- array/array.mbti
- array/array_test.mbt
- array/moon.pkg.json
close: #488 
Not sure if an API like this is what you want, and I also think we should provide a default rand function for the user so I added the rand package and make the `rand` argument optional.
> feat: Add shuffle function to Array

- immut/hashset/HAMT.mbt
- immut/hashset/HAMT_test.mbt
- immut/hashset/bitset.mbt
- immut/hashset/bitset_test.mbt
- immut/hashset/bucket.mbt
- immut/hashset/bucket_test.mbt
- immut/hashset/hashset.mbti
- immut/hashset/moon.pkg.json
- immut/hashset/sparse_array.mbt
- immut/hashset/sparse_array_test.mbt
Closes #498 
This PR adds a immutable hash set that based on a HAMT. Basically just a copy from the immutable hash map.
> Add immut/hashset

- devec/devec.mbt
- devec/devec.mbti
> Fix incorrect map behavior in devec

- coverage/coverage.mbt
- coverage/coverage_test.mbt
> split test off

- array/array_test.mbt
- array/fixedarray.mbt
- array/fixedarray_sort.mbt
- array/sort.mbt
- array/sort_by.mbt
- builtin/array.mbt
- hashset/hashset.mbt
- hashset/hashset.mbti
- hashset/hashset_test.mbt
- hashset/test/moon.pkg.json
- hashset/test/test.mbt
- hashset/test/test.mbti
- hashset/types.mbt
- immut/array/array.mbt
- immut/sorted_map/map.mbt
- remove usage of Array::
- tweak
- add missing APIs for hashset
> hongbo/get rid of T

- json/lex_main.mbt
- json/lex_misc.mbt
- json/lex_number.mbt
- json/lex_string.mbt
- json/parse.mbt
- json/parse_error_test.mbt
- json/parse_test.mbt
> Fix json parser should have failed

- builtin/linked_hash_map.mbt
- builtin/linked_hash_map_test.mbt
- I changed the name of files to adopt snake_case
- I cannot achieve 100% coverage, there is only one line left, but the effective number of lines of code has been completely covered. The remaining line is 438 lines, which can be clearly argued that it will never run.
> 100% LinkedListMap coverage

- builtin/intrinsics.mbt
> align abort with panic

- strconv/decimal.mbt
- strconv/double.mbt
- strconv/traits.mbt
because the meaning of `!!` is about to be changed
> not use !! temporarily

- sorted_map/map.mbt
- sorted_map/map_test.mbt
Fix the wrong behavior when adding duplicate key.
> Fix sorted map

- .github/workflows/check.yml
different repos may have different CLAs
> tweak CLA check

- sorted_map/map.mbt
- sorted_map/map_test.mbt
- sorted_map/types.mbt
- sorted_map/utils.mbt
> refactor sorted map

- builtin/buffer_test.mbt
- builtin/test/byte_test.mbt
- coverage/coverage_test.mbt
> use Buffer::new instead of Buffer::make

- array/array.mbt
- array/array.mbti
- array/array_test.mbt
- builtin/array.mbt
- builtin/array_test.mbt
- builtin/buffer.mbt
- builtin/builtin.mbti
This is part 1 of https://github.com/moonbitlang/core/pull/538
The join was not added by me BTW
> change join

- array/array.mbti
- array/array_test.mbt
- array/fixedarray.mbt
- builtin/array.mbt
- builtin/array_test.mbt
- builtin/builtin.mbti
- deque/deque.mbt
- deque/deque.mbti
- deque/test/test.mbt
We will add a rev api later so that
```
a.rev_eachi(f) ===  a.rev().eachi(f)
```
cc @qazxcdswe123 @Yoorkin
> rename eachi_rev into rev_eachi

- rational/rational.mbt
- rational/rational.mbti
- rational/rational_test.mbt
> migrate rational API to use the new error handling mechanism instead of Result

- strconv/strconv.mbti
- strconv/traits.mbt
> fix: re-pub FromStr

- strconv/double.mbt
- strconv/number.mbt
> remove unneeded lsl

- ref/ref.mbt
- ref/ref.mbti
- ref/ref_test.mbt
> add @ref.new, mark @ref.ref deprecated

- builtin/arrayview.mbt
- builtin/arrayview_test.mbt
- builtin/builtin.mbti
> add ArrayView::iter

- strconv/decimal.mbt
- take advantage of cascade operator
- tweak
> take advantage of cascade operator

- array/array_test.mbt
- random/random.mbt
- random/random_test.mbt
> revert random to mt19937

- json/json_bbtest.mbt
- json/json_test.mbt
- json/moon.pkg.json
two issues I found:
1. Editor result is inconsistent with `moon check`, no errors in the editor but errors in `moon check`
2. `moon check` and `moon test` does not work
> test black box test

- builtin/builtin.mbti
- builtin/iter.mbt
- builtin/linked_hash_map.mbt
- builtin/linked_hash_map_bbtest.mbt
- builtin/moon.pkg.json
- add iter method for Iter
- add keys, values support
- add test
> add Hashmap keys, values method

- builtin/builtin.mbti
- builtin/hasher.mbt
- builtin/moon.pkg.json
- int/int.mbt
- int/int.mbti
- string/string.mbt
- string/string.mbti
> move String::hash and Int::hash to builtin

- immut/array/array.mbt
- immut/array/array.mbti
- immut/array/types.mbt
- immut/hashmap/HAMT.mbt
- immut/hashmap/hashmap.mbti
- immut/hashset/HAMT.mbt
- immut/hashset/hashset.mbti
- immut/list/list.mbt
- immut/list/list.mbti
- immut/list/list_test.mbt
- immut/priority_queue/moon.pkg.json
- immut/priority_queue/priority_queue.mbt
- immut/priority_queue/priority_queue.mbti
- immut/priority_queue/priority_queue_test.mbt
- immut/priority_queue/types.mbt
- immut/sorted_map/map.mbt
- immut/sorted_map/map_test.mbt
- immut/sorted_map/sorted_map.mbti
- immut/sorted_map/types.mbt
- immut/sorted_map/utils.mbt
- immut/sorted_map/utils_test.mbt
- immut/sorted_set/generic.mbt
- immut/sorted_set/immutable_set.mbt
- immut/sorted_set/immutable_set_test.mbt
- immut/sorted_set/sorted_set.mbti
- immut/sorted_set/types.mbt
#692
rename types in:
- immut/array
- immut/hashmap
- immut/hashset
- immut/list
- immut/priority_queue
- immut/sorted_map
- immut/sorted_set
> rename types to T in packages immut/x

- priority_queue/priority_queue.mbt
- priority_queue/priority_queue.mbti
- priority_queue/priority_queue_test.mbt
- priority_queue/types.mbt
- queue/queue.mbt
- queue/queue.mbti
- queue/queue_test.mbt
- queue/types.mbt
- rational/rational.mbt
- rational/rational.mbti
> rename queue.Queue to queue.T

- array/array.mbti
- array/array_test.mbt
- array/view.mbt
- array/view_test.mbt
I do find each useful for ArrayView as memtioned in https://github.com/moonbitlang/core/issues/669
And I noticed there was a rename for FixedArray::iter related functions, but the tests were not renamed. Fixed in the PR as well
> feat: add each for arrayview

- builtin/debug.mbt
- immut/array/array.mbt
- immut/array/array.mbti
- immut/array/array_test.mbt
- immut/array/operation.mbt
- make `immutable_set` and `immutable_push` private
- make `is_empty` and `length` as method of `T`
- move inline tests to blackbox test
> refactor immut/array

- json/json.mbt
- json/json.mbti
- add method `JsonValue::to_json`
> add JsonValue.to_json for json interpolation

- builtin/builtin.mbti
- builtin/intrinsics.mbt
- builtin/intrinsics_test.mbt
- uint/uint_test.mbt
There already exists a `UInt::to_byte` in `moonbitlang/core/uint`
> remove duplicated UInt::to_byte

- .github/workflows/check.yml
- coverage/coverage.mbt
- coverage/coverage.mbti
> reenable coverage check

- double/ryu.mbt
> feat: convert ryu to use uint

- builtin/intrinsics.mbt
- byte/byte.mbt
- byte/byte.mbti
- byte/byte_test.mbt
- byte/moon.pkg.json
close: https://github.com/moonbitlang/core/issues/678
> feat: add byte pkg

- builtin/builtin.mbti
- builtin/linked_hash_map.mbt
- builtin/linked_hash_map_test.mbt
- builtin/moon.pkg.json
add missing method `Map::from_iter`.
related #744
> add Map::from_iter

- .github/workflows/check.yml
> ci: enable deny warn for moon check

- builtin/buffer.mbt
- builtin/buffer_test.mbt
- builtin/builtin.mbti
> add Buffer::write_bytes

- json/json.mbt
- json/json_test.mbt
> fix `json.stringify` escape

- builtin/builtin.mbti
- builtin/iter.mbt
- **add some docs**
- **simplify iter::take**
- **simplify Iter::take**
> simplify Iter::take

- builtin/json.mbt
- json/json_test.mbt
- json/to_json_test.mbt
> fix: escape json for string input

- builtin/bigint.mbt
- builtin/bigint_test.mbt
close https://github.com/moonbitlang/core/issues/860
> fix: bigint op_sub edge case 0 fix

- array/sort.mbt
- array/sort_by.mbt
- builtin/arrayview_test.mbt
- priority_queue/priority_queue_test.mbt
- **update priority test**
- **use the array view sugar**
- **use array view syntax**
> simplify the code base using x[a:b] sugar

- immut/list/list.mbt
- immut/list/list.mbti
- immut/list/list_test.mbt
- add `immut/list.flat_map` to replace `concat_map`
> add flat_map to list, deprecate concat_map

- NOTICE
- double/double.mbti
- double/exp.js.mbt
- double/exp.wasm-gc.mbt
- double/exp.wasm.mbt
- double/exp_test.mbt
rt
copied from: https://github.com/v8/v8/blob/c99a877ce5488deabf5af80146a38f73270c54c4/src/base/ieee754.cc
close #861
> implement exp

- json/from_json.mbt
- json/from_json_test.mbt
- json/json.mbti
- json/json_path.mbt
use mutable field to improve the performance of `from_json`.
#876
> perf: improve from_json

- json/json.mbt
- json/json_test.mbt
> fix(json): correct integer stringify

- builtin/builtin.mbti
- builtin/iter.mbt
- builtin/iter_test.mbt
- builtin/moon.pkg.json
Added `inclusive` function for later `..=` and `..<`
> feat: add inclusive for iter until

- builtin/arrayview.mbt
- builtin/builtin.mbti
Make last argument of `op_as_view` optional.
> use optional argument in `op_as_view`

- json/json.mbt
- json/json.mbti
- json/json_test.mbt
> fix(json): not escape forward slash when stringify

- math/math.mbti
- math/trigonometric.mbt
> feat: make @math.pi pub

- builtin/array.mbt
- builtin/array_test.mbt
- builtin/builtin.mbti
The functionality added:
- binary_search
- binary_search_by
See code for more.
> add binary_search functionality for Array

- builtin/array.mbt
unclear why changes are lost 
https://github.com/moonbitlang/core/pull/891#issuecomment-2308864108
cc @guuzaa
> rewrite in functional style

- array/array_test.mbt
- builtin/array.mbt
- builtin/array_test.mbt
- builtin/builtin.mbti
cc @guuzaa it seems that I can not do modifications directly in your branch, I appended a commit to keep the old API for a while and some minor clean up
> Refactoring Array

- builtin/bigint.mbt
- builtin/bigint_wbtest.mbt
> feat: change radix of bigint to 2^32

- builtin/bigint.mbt
- builtin/builtin.mbti
- builtin/intrinsics.mbt
- builtin/intrinsics_test.mbt
- byte/byte.mbt
- double/exp.wasm-gc.mbt
- double/internal/ryu/ryu.mbt
- quickcheck/arbitrary.mbt
- random/internal/random_source/random_source_chacha.mbt
- random/random.mbt
- strconv/number.mbt
- **change Int::to_uint -> Int::reinterpret_as_uint**
- **promote**
cc @Yoorkin @qazxcdswe123
> change Int::to_uint -> Int::reinterpret_as_uint

- queue/queue.mbt
- queue/queue_test.mbt
1. Fix some errors in the document of queue
2. Add more black box tests
> Fix some errors in the document of queue

- json/from_json.mbt
- json/json.mbti
- json/json_path.mbt
> feat: allow modifying key and index

- builtin/iter2.mbt
more efficient Iter2::to_array and to_string
cc @guuzaa
> more efficient iter2 method

- json/json_path.mbt
> simplify jsonpath

- string/string.mbt
- string/string.mbti
- string/string_test.mbt
> feat: string iter2

- builtin/builtin.mbti
- builtin/json.mbt
- json/from_json.mbt
- json/from_json_test.mbt
- json/json.mbti
- json/moon.pkg.json
- json/to_json_test.mbt
Except for `bytes` and `byte`
Related: #976
> implement ToJson/FromJson traits for types defined in core

- builtin/json.mbt
- json/derive_json_test.mbt
- json/from_json.mbt
- **tweak tojson/fromjson**
- **more tests**
- **fmt**
> hongbo/tweak tojson/fromjson and add derive fromjson test

- array/array.mbt
- array/array.mbti
- array/fixedarray.mbt
- builtin/array.mbt
- builtin/builtin.mbti
- builtin/fixedarray.mbt
- builtin/iter.mbt
- builtin/show.mbt
- deque/deque.mbt
- **move Array::iter/iter2 from array package into builtin**
- **improve `impl Show for Iter` and use for deque**
- **add Iter::contains**
> simplify impl Show for T as long as T is already iterable

- builtin/array.mbt
- builtin/array_test.mbt
- builtin/builtin.mbti
> feat: compare for Array

- json/json.mbt
- json/json.mbti
- json/json_test.mbt
- string/string.mbt
- string/string.mbti
- string/string_test.mbt
#1001 rebased
for the compiler bug, I created an internal issue
> Feat json indent (rebased)

- builtin/builtin.mbti
- builtin/iter.mbt
- builtin/iter_test.mbt
- ** simplify list & deque printer**
- **add Iter::peek**
> add Iter::peek

- builtin/builtin.mbti
- builtin/iter.mbt
- builtin/show.mbt
- builtin/traits.mbt
- deque/deque.mbt
- hashset/hashset.mbt
- immut/array/array.mbt
- immut/hashmap/HAMT.mbt
- immut/hashset/HAMT.mbt
- immut/list/list.mbt
- immut/priority_queue/priority_queue.mbt
- immut/sorted_map/utils.mbt
- immut/sorted_set/immutable_set.mbt
- priority_queue/priority_queue.mbt
- queue/queue.mbt
- sorted_map/utils.mbt
- sorted_set/set.mbt
todo: add two labeled parameters to reduce lots of function call
> simplify iter printing

- builtin/builtin.mbti
- builtin/tuple_show.mbt
- builtin/tuple_to_json.mbt
- json/from_json_test.mbt
- json/json.mbti
- json/to_json_test.mbt
- json/tuple_fromjson.mbt
> Implement Show and FromJson for tuple 8 to 16

- hashmap/README.md
- hashset/README.md
- immut/array/README.md
- immut/hashmap/README.md
- immut/list/README.md
- immut/priority_queue/README.md
- immut/sorted_map/README.md
- immut/sorted_set/README.md
- option/README.md
- priority_queue/README.md
- queue/README.md
- random/README.md
- rational/README.md
- rational/rational.mbt
- sorted_set/README.md
- strconv/README.md
- strconv/traits.mbt
- tuple/README.md
- update the outdated documentation
- use `@pkg` in examples
> update README files in packages

- json/json.mbt
- json/json.mbti
- json/json_inspect_test.mbt
- json/json_path.mbt
https://github.com/moonbitlang/core/issues/1012
- add @json.inspect
> add @json.inspect

- json/json.mbt
Fix https://github.com/moonbitlang/core/issues/1073
> set `escape_slash` to `false` in `@json.inspect`

- json/json.mbt
- json/json_test.mbt
Close https://github.com/moonbitlang/core/issues/1080
> change the default value of `escape_slash` to `false`

- builtin/builtin.mbti
- builtin/byte.mbt
- builtin/byte_test.mbt
useful when we have byte literal support
> feat: add byte + - >> << operator

- immut/list/list.mbt
- immut/list/list.mbti
- immut/list/list_test.mbt
- immut/list/panic_test.mbt
close: https://github.com/moonbitlang/core/issues/1098
> fix: last return option

- builtin/builtin.mbti
- builtin/hasher.mbt
- builtin/int64_js.mbt
- builtin/int64_nonjs.mbt
- builtin/intrinsics_test.mbt
- double/double.mbt
- double/double_test.mbt
- double/exp_nonjs.mbt
- double/internal/ryu/ryu.mbt
- double/log.mbt
- float/exp.mbt
> refactor: rename consistent

- builtin/builtin.mbti
- builtin/int64_js.mbt
- builtin/int64_nonjs.mbt
- builtin/int64_test.mbt
close https://github.com/moonbitlang/core/issues/1096
> feat: u64 to f64

- builtin/builtin.mbti
- builtin/linked_hash_map.mbt
- builtin/linked_hash_set.mbt
- builtin/linked_hash_set_wbtest.mbt
- hashmap/hashmap_test.mbt
> add linked hash set to builtin

- test/test.mbti
- test/types.mbt
> internal: use StringBuilder in @test.T

- math/math.mbti
- math/round.mbt
> math functions provided by mengzhuo

- builtin/builtin.mbti
- builtin/bytes.mbt
- builtin/intrinsics.mbt
- uint/uint.mbt
- uint/uint.mbti
1. move `UInt::to_byte` and `UInt::to_int64` to builtin
2. refactor `builtin/bytes.mbt` using the new func
> Move u32 to byte to intrinsic

- builtin/string.mbt
- builtin/stringbuilder_test.mbt
- bytes/bytes.mbt
- bytes/bytes_test.mbt
- **tweak the guard conditions**
- **tweak guards and add test**
- **add a todo note**
- **more tests for @bytes.of**
> add some tests for @bytes.of

- builtin/builtin.mbti
- builtin/json.mbt
- builtin/linked_hash_map.mbt
- bytes/bytes.mbt
- bytes/bytes.mbti
- float/float.mbt
- float/float.mbti
- uint/uint.mbt
- uint/uint.mbti
> impl Default for some types

- builtin/byte.mbt
caveats:
1. AI generated docs flushed `@alert` pragma
2. maybe file level UI should be in some other places instead of in each icon
cc @tonyfettes
> AI: doc pub func per file

- immut/sorted_set/immutable_set.mbt
- immut/sorted_set/sorted_set.mbti
> feat: impl Hash for immutable_set

- immut/hashmap/HAMT.mbt
- immut/hashmap/HAMT_test.mbt
- immut/hashmap/hashmap.mbti
> impl Eq and Hash for immut/hashmap

- builtin/builtin.mbti
- builtin/tuple_compare.mbt
Closes #1184 
TODO:
Add tests for these Eq/Hash/Compare impl of tuples
> add Compare trait impl for tuples

- buffer/buffer.mbt
- buffer/buffer.mbti
rename to `@buffer.T` to align with collection types like map, set
> rename `@buffer.Buffer` to `@buffer.T`

- builtin/builtin.mbti
- builtin/byte.mbt
- builtin/byte_test.mbt
> add Byte::op_mul, Byte::op_div

- random/moon.pkg.json
- random/random.mbt
- random/random_test.mbt
This PR fixes #1211
Histogram of 262144 samples:
> fix: call to_float() on both sides of the div

- array/array.mbti
- builtin/builtin.mbti
- immut/list/list.mbti
- immut/priority_queue/priority_queue.mbti
- immut/sorted_map/sorted_map.mbti
- immut/sorted_set/sorted_set.mbti
- json/json.mbti
- math/math.mbti
- option/option.mbti
- priority_queue/priority_queue.mbti
- quickcheck/splitmix/splitmix.mbti
- result/result.mbti
- sorted_map/sorted_map.mbti
- sorted_set/sorted_set.mbti
This PR updates the moon info distributed with the toolchain version:
```bash
$ moon version --all
moon 0.1.20241125 (6fe6396 2024-11-25)
moonc v0.1.20241125+34a5d819a
moonrun 0.1.20241125 (6fe6396 2024-11-25)
```
> update moon info

- quickcheck/arbitrary.mbt
- quickcheck/quickcheck.mbti
- quickcheck/splitmix/random.mbt
- quickcheck/splitmix/splitmix.mbti
> feat: implement arbitrary for primitive types

- double/double.mbti
- double/mod_js.mbt
- double/mod_nonjs.mbt
- double/mod_test.mbt
- double/moon.pkg.json
- float/float.mbti
- float/mod.mbt
- float/mod_test.mbt
> feat: op_mod for Float and Double

- builtin/arraycore_js.mbt
- builtin/arraycore_nonjs.mbt
- builtin/fixedarray_block.mbt
- **remove duplicated code**
- **doc: clarify `unsafe_blit_fixed` function description for FixedArray usage**
> remove duplicated code

- tuple/tuple_test.mbt
> Add test coverage for Compare/Hash impl of tuples

- array/array.mbt
- array/array.mbti
- **remove deprecated Array::new_with_index and join methods**
- **moon info**
> remove two deprecated functions

- immut/sorted_set/generic.mbt
- immut/sorted_set/immutable_set_test.mbt
- immut/sorted_set/sorted_set.mbti
This PR added a missing Compare impl for @immut/sorted_set. As it needed by moonyacc.
> add Compare impl for @immut/sorted_set

- builtin/builtin.mbti
- builtin/intrinsics.mbt
> deprecate op_compare in favor of compare

- immut/sorted_map/inorder_iterator.mbt
- immut/sorted_map/map.mbt
- immut/sorted_map/map_test.mbt
- immut/sorted_map/sorted_map.mbti
- immut/sorted_map/traits_impl.mbt
- immut/sorted_map/utils.mbt
This PR added Default, Compare impls for immut/sorted_map
> add Default, Compare impls for immut/sorted_map

- immut/sorted_set/immutable_set.mbt
- immut/sorted_set/sorted_set.mbti
- immut/sorted_set/types.mbt
> impl Default for immut/sorted_set

- immut/sorted_set/immutable_set.mbt
- immut/sorted_set/immutable_set_test.mbt
- immut/sorted_set/sorted_set.mbti
- immut/sorted_set/types.mbt
> track size in @immut/sorted_set like @immut/sorted_map

- hashmap/hashmap.mbti
- hashmap/hashmap_test.mbt
- hashmap/utils.mbt
- hashset/hashset.mbt
This PR added missing `@hashmap.T::iter2`
> add @hashmap.T::iter2

- string/string.mbt
> Docs: add docs for string iter behavior

- builtin/builtin.mbti
- builtin/hasher.mbt
- builtin/hasher_test.mbt
- float/float.mbt
- float/float_test.mbt
> implement hash for float

- array/sort.mbt
- deque/deque_test.mbt
- deque/moon.pkg.json
> Add more test for deque.

- deque/deque.mbt
Related to https://github.com/moonbitlang/core/pull/1410.
> fix(deque): set cells to `null` in `@deque.clear()`

- int64/int64.mbt
Add documentation to int64 package.
> [doc] int64

- deque/deque.mbt
- deque/deque.mbti
- deque/deque_test.mbt
Mirrors Rust's [`VecDeque::retain()`](https://doc.rust-lang.org/std/collections/vec_deque/struct.VecDeque.html#method.retain).
> feat(deque): add `@deque.retain()`

- .github/workflows/check.yml
- float/moon.pkg.json
... since this is no longer strictly JSON from a certain point on.
> fix(float): remove trailing comma in `moon.pkg.json`

- buffer/buffer.mbt
cc @Young-Flash when I run moon test --doc --update, it generates invalid output, see the commit for more details
> when I run `moon test --doc --update`, it generates invalid output

- sorted_set/set.mbt
> remove redundant comparisons for sorted_set

- sorted_set/set.mbt
- string/string.mbt
> improve to_array for sorted_set (use safe way)

- env/env_test.mbt
```
coverage of `env/env.mbt`: 50.0% -> 100%
```
> test: improve coverage for `env/env.mbt`

- builtin/fixedarray_test.mbt
```
coverage of `builtin/fixedarray.mbt`: 73.3% -> 80.0%
```
> test: improve coverage for `builtin/fixedarray.mbt`

- sorted_set/set.mbt
- sorted_set/set_test.mbt
- sorted_set/sorted_set.mbti
> deprecate: inconsistent api @sorted_set.of

- array/array.mbt
- array/array.mbti
- array/array_test.mbt
- array/moon.pkg.json
cc @gmlewis , is this what you expected?
> feat: Add join method for Array[String]

- builtin/builtin.mbti
- builtin/bytes.mbt
- builtin/bytes_test.mbt
> add Bytes::compare

- array/view.mbt
- deque/deque.mbt
- strconv/int.mbt
- **refactor: Simplify guard statements in iterators for improved readability**
- **refactor: Simplify guard statements in rev_iter and enhance test coverage in strconv**
> test new feature `expr is pat`

- builtin/intrinsics.mbt
The automatically generated doc messed up the intrinsics. This PR fixed this problem.
> fix intrinsic name

- random/random_test.mbt
```
coverage of `random/random.mbt`: 81.5% -> 100%
```
> test: improve coverage for `random/random.mbt`

- builtin/builtin.mbti
- builtin/bytesview.mbt
- builtin/bytesview_test.mbt
> implement Eq and Compare for BytesView

- json/json.mbt
- json/json_test.mbt
Note this PR also fixes the bleeding compiler by walk around changes in 26ce5fa
> test: Enhance JSON stringify test coverage with escape scenarios

- builtin/builtin.mbti
- builtin/intrinsics.mbt
- builtin/show.mbt
- builtin/show_test.mbt
- builtin/string.mbt
- builtin/string_test.mbt
- string/string.mbt
- string/string_test.mbt
- string/utils.mbt
- string/view.mbt
- string/view_test.mbt
- **move to_string from method to trait Show for Char**
- **update test**
- **the last test inspect does not get right**
> update Show::to_string  for char

- json/lex_main.mbt
- json/lex_misc.mbt
- json/parse_test.mbt
- json/utils.mbt
- **rename lex_assert_char into expect_char**
- **add a todo note that the error should report unicode error message**
- **add expect_ascii_char to improve performance**
- **tweak**
> add expect_ascii_char to improve performance

- sorted_set/set.mbt
- sorted_set/sorted_set.mbti
- sorted_set/types.mbt
Note this fix is generated by AI
> fix #1322 using Int instead of Int64

- builtin/tuple_to_json_test.mbt
- math/trigonometric_test.mbt
- quickcheck/arbitrary_test.mbt
> test: improve coverage for multiple files

- builtin/tuple_show_test.mbt
- builtin/tuple_to_json_test.mbt
**Disclaimer**: This PR was generated by an LLM agent as part of an experiment.
> test: improve coverage for tuple-related sources

- json/parse_error2_test.mbt
> update test does not work

- immut/list/deprecated.mbt
- immut/list/list.mbt
- immut/list/list.mbti
- immut/list/list_test.mbt
> equal is duplicated with Eq::op_equal

- builtin/builtin.mbti
- builtin/byte.mbt
- builtin/fixedarray.mbt
- builtin/int64_js.mbt
- builtin/int64_nonjs.mbt
- builtin/json.mbt
- builtin/linked_hash_map.mbt
- bytes/bytes.mbt
- bytes/bytes.mbti
- float/float.mbt
- float/float.mbti
- option/option.mbt
- option/option.mbti
- result/result.mbt
- result/result.mbti
- string/string.mbt
- string/string.mbti
- uint/uint.mbt
- uint/uint.mbti
- unit/unit.mbt
- unit/unit.mbti
- unit/unit_test.mbt
This PR is a continuation of #1706, some method based implementations are missed in #1706
> port method based trait implementation to explicit `impl`

- builtin/builtin.mbti
- builtin/linked_hash_set.mbt
- builtin/linked_hash_set_test.mbt
> fix incorrect op_equal for linked_hash_set

- builtin/array.mbt
https://github.com/moonbitlang/core/pull/1727#discussion_r1977415810
cc @Yu-zh
> improve: Array::flatten use unsafe_blit

- builtin/stringbuilder_buffer.mbt
- string/string.mbt
pass size_hint for StringBuilder::new
> improve: string concat

- builtin/hasher.mbt
> But the hasher should indeed use UInt instead of Int, so that part may still be an improvement (in terms of code readability)
https://github.com/moonbitlang/core/pull/1610#issuecomment-2649667288
> improve hasher impl code readability

- array/README.md
> docs(array): add `README`

- builtin/hasher.mbt
- hashmap/hashmap.mbt
> docs: add TODO in Int::hash

- builtin/builtin.mbti
- builtin/iter.mbt
- builtin/iter_test.mbt
> feat: add Iter::maximum and Iter::minimum

- immut/list/list.mbt
- immut/list/moon.pkg.json
> refactor: use loop to implement unzip/zip

- builtin/builtin.mbti
- builtin/iter.mbt
> feat: add flatten for Iter

- builtin/show.mbt
- Note this is not finished, it is a bookmark
> change StringBuilder storage from FixedArray[Byte] to FixedArray[UInt16]

- int16/int16.mbt
- int16/int16.mbti
- int16/int16_test.mbt
- uint16/uint16.mbt
- uint16/uint16.mbti
- uint16/uint16_test.mbt
This PR add bitwise operations to `Int16` and `UInt16`.
> 16 bit ops

- bool/README.mbt.md
**Disclaimer**: This PR was generated by an LLM agent as part of an experiment.
> docs(bool): add `README`

- buffer/README.mbt.md
**Disclaimer**: This PR was generated by an LLM agent as part of an experiment.
> docs(buffer): add `README`

- byte/README.mbt.md
**Disclaimer**: This PR was generated by an LLM agent as part of an experiment.
> docs(byte): add `README`

- float/README.mbt.md
> docs(float): add `README`

- double/README.mbt.md
> docs(double): add `README`

- bytes/README.mbt.md
> docs(bytes): add `README`

- test/test.mbt
> fix: remove redundent "FAILED: \{loc}"

- .gitignore
- immut/hashmap/HAMT.mbt
- immut/hashmap/HAMT_test.mbt
- immut/hashmap/hashmap.mbti
- immut/hashset/HAMT.mbt
- immut/hashset/HAMT_test.mbt
- immut/hashset/hashset.mbti
- immut/internal/sparse_array/bitset.mbt
- immut/internal/sparse_array/sparse_array.mbt
- immut/internal/sparse_array/sparse_array.mbti
- immut/internal/sparse_array/sparse_array_test.mbt
> Add @immut/hash{set,map}::union

- int/README.mbt.md
> docs(int): add `README`

- int16/README.mbt.md
> docs(int16): add `README`

- ref/README.mbt.md
> docs(ref): add `README`

- test/moon.pkg.json
> add prelude to test-import of package test

- json/README.mbt.md
> docs(json): add `README`

- math/README.mbt.md
> docs(math): add `README`

- builtin/stringbuilder.mbt
- builtin/stringbuilder_buffer.mbt
- builtin/stringbuilder_concat.mbt
> feat: Add doc comment for StringBuilder

- array/fixedarray.mbt
- array/view.mbt
- immut/priority_queue/priority_queue.mbt
- option/option.mbt
- priority_queue/priority_queue.mbt
- rational/rational.mbt
1. replace `if a < b { -1 } else if a > b { 1 } else { 0 }` with `a.compare(b)`
2. replace `arr.sort_by(fn(x, y) { if x < y { 1 } else { -1 } })` with `arr.sort_by(fn(x, y) { y.compare(x) })`
3. Simplify
> refactor: optimized `compare` method

- immut/sorted_set/immutable_set.mbt
- immut/sorted_set/immutable_set_test.mbt
- immut/sorted_set/sorted_set.mbti
- sorted_set/set.mbt
- sorted_set/set_test.mbt
- sorted_set/sorted_set.mbti
Closes #1911
symmetric_difference for @sorted_set and @immut/sorted_set
> add symmetric_difference to sorted_set and immut/sorted_set

- queue/queue.mbt
- queue/types.mbt
1. Replaced `Cell[A]` with `Cons[A]?` to leverage compiler optimizations for nullable types.  
2. Refactored some methods to avoid redundant operations
> refactor(queue): optimize data structure and improve method efficiency

- priority_queue/priority_queue.mbt
- priority_queue/priority_queue.mbti
- set/linked_hash_set.mbt
- set/set.mbti
- sorted_map/map.mbt
- sorted_map/sorted_map.mbti
- sorted_set/set.mbt
- sorted_set/sorted_set.mbti
Closes #1633 (unless I missed something)
> feat: add default impl for containers

- .github/workflows/check.yml
- .github/workflows/pre-release-check.yml
now `moon test` include md test
> ci: remove test md

- test/test.mbti
- test/types.mbt
> refactor: change visibility of struct T to abstract

- uint16/README.mbt.md
- uint64/README.mbt.md
- uint64/moon.pkg.json
> docs(uint{16,64}): add `README`

- immut/list/list.mbt
- immut/list/list_test.mbt
- immut/list/moon.pkg.json
> refactor: use loop to implement rev_fold to avoid stack overflow

- deque/deque_test.mbt
> test: improve coverage for `deque/deque.mbt`

- array/README.mbt.md
- bool/README.mbt.md
- buffer/README.mbt.md
- byte/README.mbt.md
- char/README.mbt.md
- string/DESIGN.mbt.md
Since this feature will not be supported in the future
> remove moonbit: true frontmatter

- bench/bench_test.mbt
> test(bench): improve coverage

- builtin/assert_test.mbt
- builtin/fixedarray_block_test.mbt
- builtin/iter_test.mbt
- builtin/show_test.mbt
- json/from_json_test.mbt
- **MOONAGENT: add test file**
- **fmt**
> MoonAgent: add test file

- bytes/bytes.mbt
- bytes/bytes.mbti
- bytes/bytes_test.mbt
- bytes/view.mbt
- bytes/view_test.mbt
> feat(Bytes): Add a new `get` method to `Bytes` and `BytesView` types

- priority_queue/priority_queue.mbt
make a pre-assigned size for priority_queue
>  refactor: priority_queue speed up by size pre-assigned

- string/methods.mbt
- string/moon.pkg.json
- string/string.mbti
> refactor APIs for StringView

- builtin/array.mbt
- immut/array/array.mbt
- immut/array/array.mbti
- immut/array/array_test.mbt
- immut/list/list.mbt
- immut/list/list.mbti
- immut/list/list_test.mbt
- immut/priority_queue/priority_queue.mbt
- immut/priority_queue/priority_queue.mbti
- immut/priority_queue/priority_queue_test.mbt
> Impl Compare for @immut/array, list and priority_queue

- list/list.mbt
use loop we not need comment here
> refactor(@list.any): imporve code readbility

- sorted_map/map.mbt
use capacity imporve @sorted_map.keys,values,to_array
> perf(@sorted_map):

- array/array.mbti
- array/view.mbt
- array/view_test.mbt
Simple implementation based on the filter method implementation
> Implement ViewArray::to_array

- builtin/array.mbt
- builtin/intrinsics.mbt
> Add the doc comments for Array::make and FixedArray::make

- hashset/hashset.mbt
- hashset/hashset.mbti
- hashset/hashset_test.mbt
> Add some methods to HashSet

- buffer/buffer.mbt
- immut/sorted_set/generic.mbt
- immut/sorted_set/sorted_set.mbti
- json/types.mbt
- math/math.mbti
- math/trigonometric.mbt
- quickcheck/splitmix/random.mbt
- quickcheck/splitmix/splitmix.mbti
- random/random.mbt
- random/random.mbti
- sorted_set/set.mbt
- sorted_set/sorted_set.mbti
- strconv/decimal.mbt
- strconv/strconv.mbti
there are still some out-dated docstring pragma left in core, this PR migrates them to attributes
> cleanup some outdated pragma

- array/array.mbti
- array/view.mbt
- array/view_test.mbt
> feat: impl Hash Arbitrary for ArrayView

- builtin/bigint_nonjs.mbt
- builtin/builtin.mbti
- builtin/bytes.mbt
- builtin/bytes_test.mbt
- builtin/console.mbt
- builtin/intrinsics.mbt
- builtin/iter_test.mbt
- builtin/output.mbt
- builtin/panic_test.mbt
- builtin/show.mbt
- builtin/string.mbt
- builtin/string_test.mbt
- bytes/bytes_pattern_test.mbt
- bytes/view.mbt
- char/char_test.mbt
- double/internal/ryu/ryu.mbt
- env/env_native.mbt
- env/env_wasm.mbt
- json/from_json.mbt
- json/json.mbt
- json/lex_misc.mbt
- json/lex_string.mbt
- json/utils.mbt
- quickcheck/arbitrary.mbt
- strconv/string_slice.mbt
- string/methods.mbt
- string/string.mbt
- string/utils.mbt
- string/view.mbt
- string/view_test.mbt
> refactor: migrate Char::from_int to Int::unsafe_to_char

- builtin/builtin.mbti
- builtin/json.mbt
- builtin/json_test.mbt
- int16/int16.mbt
- int16/int16.mbti
- int16/int16_test.mbt
- int16/moon.pkg.json
- uint16/moon.pkg.json
- uint16/uint16.mbt
- uint16/uint16.mbti
- uint16/uint16_test.mbt
> feat: impl ToJson for Byte,Int16,UInt16

- sorted_map/map.mbt
sorted_map is BST, don't worry too deep cause stack overflow.
> perf(@sorted_map.each) replace stack version with dfs version

- tuple/tuple_test.mbt
> test(tuple): improve coverage

- builtin/builtin.mbti
- builtin/byte.mbt
- builtin/byte_test.mbt
This PR adds missing `op_mod` implementation to `Byte`
> add modular operator to `Byte`

- array/blit.mbt
- array/blit_js.mbt
- array/blit_nonjs.mbt
- array/moon.pkg.json
> feat: use `slice` for FixedArray::copy under js target

- builtin/linked_hash_map.mbt
- hashmap/types.mbt
- hashset/hashset.mbt
- hashset/types.mbt
- immut/hashmap/HAMT.mbt
- immut/hashmap/bucket.mbt
- immut/hashmap/types.mbt
- immut/hashset/HAMT.mbt
- immut/hashset/bucket.mbt
- immut/hashset/types.mbt
- set/linked_hash_set.mbt
1. rename `Just_One` to `JustOne`
2. rename `growAt` to `grow_at`
> unify naming style

- strconv/additional_coverage_test.mbt
- string/additional_coverage_test.mbt
- string/op_as_view_test.mbt
- **add additional coverage tests for strconv and string modules**
- **remove warnings**
> MoonAgent: add more coverage

- .github/ISSUE_TEMPLATE/anything.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/consistency-review-request.md
- .github/ISSUE_TEMPLATE/feature_request.md
Provide issue templates to assist in issue creation
> Update issue templates

- builtin/array_block.mbt
> docs(Array:blit_to) use consistent parameter name between documentation and implementation

- char/char.mbt
- char/char.mbti
- char/char_test.mbt
add `to_ascii_lowercase` and  `to_ascii_uppercase` in `Char`.  the code is inspired from similiar function in rust
> implement to_ascii_lowercase and to_ascii_uppercase in Char

- array/array.mbti
- array/view.mbt
- array/view_test.mbt
- bytes/bytes.mbt
- bytes/bytes.mbti
- bytes/bytes_test.mbt
Part of the enhancement proposed in [this issue](https://github.com/moonbitlang/core/issues/1013)
> feat: add ArrayView::Iter2 and Bytes::Iter2

- builtin/builtin.mbti
- builtin/intrinsics.mbt
Next step: https://github.com/moonbitlang/core/pull/2146
> deprecate FixedArray::get

- builtin/builtin.mbti
- builtin/bytes.mbt
- builtin/bytes_test.mbt
- builtin/panic_test.mbt
- string/string.mbt
> refactor: deprecate Bytes::of_string

- array/array_test.mbt
- builtin/array.mbt
- builtin/builtin.mbti
> feat: add array.unsafe_pop_back

- json/json.mbti
- json/json_test.mbt
- json/lex_misc.mbt
- json/lex_number_test.mbt
- json/lex_string_test.mbt
- json/types.mbt
- **add ToJson for ParseError**
- **upgrade try?**
- **better practice**
> move more to `try?` 

- bytes/bytes.mbti
- bytes/view.mbt
- bytes/view_test.mbt
> feat: add `@bytes.View::to_bytes`

- bench/bench.mbt
- bench/stats.mbt
+ Eliminated redundant calculations to improve performance
+ Restructured code organization to make dependencies between statistical measures more explicit
+ Added comprehensive tests to verify behavior remains unchanged
> Refactor `Summary::new` in @bench

- builtin/linked_hash_map.mbt
- coverage/coverage.mbt
- hashset/hashset.mbt
- immut/hashmap/HAMT.mbt
- immut/hashmap/HAMT_test.mbt
- immut/hashmap/bucket.mbt
- immut/hashset/HAMT.mbt
- immut/hashset/HAMT_test.mbt
- immut/hashset/bucket.mbt
- immut/list/deprecated.mbt
- immut/list/dps_test.mbt
- immut/list/list.mbt
- immut/priority_queue/priority_queue.mbt
- immut/sorted_map/traits_impl.mbt
- immut/sorted_set/generic.mbt
- list/list.mbt
- priority_queue/priority_queue.mbt
- queue/queue.mbt
- set/linked_hash_set.mbt
- sorted_set/set.mbt
- strconv/int.mbt
- strconv/uint.mbt
Because this syntax will be deprecated.
> remove usage of loop with multi param

- bench/stats.mbt
> refactor(bench): rename `var` to `variance`

- builtin/builtin.mbti
- builtin/linked_hash_map.mbt
- builtin/linked_hash_map_test.mbt
> feat(Map): add `map` and `copy` for `Map`

- prelude/prelude.mbt
> doc: explain why `tap` and `then` are needed.

- builtin/double_to_int.mbt
- builtin/double_to_int64_native.mbt
- builtin/double_to_int_wasm.mbt
- builtin/intrinsics.mbt
> try to fix double print in windows

- array/fixedarray_sort.mbt
- array/fixedarray_sort_by.mbt
- array/sort.mbt
- array/sort_by.mbt
There are no letrec left in the core now.
> refactor: replace letrec with let in non-recursive cases

- .github/workflows/bleeding-check.yml
- .github/workflows/bleeding-native-opt-test.yml
- README.md
test : https://github.com/moonbitlang/core/pull/2343/checks
> enable bleeding check in pull request when branch name has prefix `bleeding/`

- double/to_uint_wasm.mbt
- float/float.mbt
- json/README.mbt.md
- priority_queue/README.mbt.md
- priority_queue/moon.pkg.json
- priority_queue/priority_queue.mbt
- priority_queue/priority_queue.mbti
- **fmt**
- **impl ToJson for @priority_queue.T**
> fmt docstring 

- bigint/bigint.mbt
- bigint/bigint.mbti
- bigint/bigint_js.mbt
- bigint/bigint_js_wbtest.mbt
- bigint/bigint_test.mbt
Implement Default for BigInt and add tests
> feat: impl default for Bigint

- strconv/number.mbt
- strconv/number_wbtest.mbt
> fix: handle overflow correctly in checked_mul

- deque/deque.mbt
- deque/deque.mbti
- deque/deque_test.mbt
PR Description​​
​​Summary​
This pr adds the shuffle method, but does not write a test
> feat(deque): add shuffle_in_place and shuffle method

- char/char.mbt
- char/char.mbti
- json/lex_main.mbt
- **remove unneeded b prefix in check mode**
- **add Char::utf16_len**
> Add Char::utf16_len

- list/list.mbt
Add comments for methods in list, so as to avoid some misunderstanding as of what the method does.
> doc: improve list comments

- char/char_test.mbt
- hashmap/types_test.mbt
> [!NOTE]
> This PR was made by an LLM agent.
This PR adds extensive test coverage for several modules in the MoonBit core library:
- **hashmap/types_test.mbt**: Complete test suite for HashMap equality implementation
- **math/prime_test.mbt**: Extended edge case tests for primality testing functions  
- **char/char_test.mbt**: Additional boundary tests for character classification functions
- **HashMap Equality Tests**: Added 11 comprehensive test cases covering identical maps, different orders, edge cases with empty maps, size differences, and modification scenarios
- **Math Prime Tests**: Added edge case validation for invalid iterations, boundary conditions for trial divisions, comprehensive primality tests, different bit sizes for prime generation, and Miller-Rabin edge cases
- …
> Add comprehensive tests to improve code coverage

- char/char_test.mbt
- hashmap/types_test.mbt
- string/methods.mbt
- **add more tests for char and hashmap**
- **tweak readability**
> tweak readability

- immut/list/list.mbt
This pr fix the duplicated attribute warnings.
> fix: remove duplicated deprecated attributes in immut/list

- double/moon.pkg.json
- Removed unnecessary entries from "test-import" and "warn-list"
- Streamlined the package configuration for better clarity and maintainability
> refactor: update moon.pkg.json structure

- array/view_test.mbt
- bytes/moon.pkg.json
- bytes/view.mbt
- bytes/view_test.mbt
- bytes/xxhash.mbt
- string/moon.pkg.json
- string/view_test.mbt
> test: add hash invariant

- hashset/hashset.mbt
- hashset/hashset.mbti
- hashset/hashset_test.mbt
- hashset/moon.pkg.json
- hashset/types.mbt
- set/linked_hash_set.mbt
- set/linked_hash_set_test.mbt
- set/set.mbti
This PR refactors the code base to reduce the maintenance cost by
1. Align the implementation between linked hash set and map
2. Align the implementation between linked hash set and hash set
This PR also adds the APIs for both linked hash set and hash set such that they share a similar interface.
> feat: align sets APIs

- bool/README.mbt.md
- unit/README.mbt.md
- Improved bool package documentation with comprehensive examples showing practical use cases:
- Boolean indexing and selection patterns
- Bit manipulation and flag operations
- Statistical and mathematical operations with boolean conversion
- Real-world conditional arithmetic examples
- Enhanced unit package documentation with better explanations of:
- The purpose and importance of Unit type in functional programming
- Side-effect function patterns and best practices
- Generic programming contexts where Unit is useful
- Practical use cases including result accumulation and builder patterns
- Fixed all type checking errors in .mbt.md files to ensure documentation examples compile correctly
- Added comprehensive context about when and why to use these fundamental types
> Enhance documentation for bool and unit packages

- immut/hashmap/HAMT.mbt
- immut/hashmap/HAMT_test.mbt
> fix(immut/hashmap): hash_combine

- coverage/coverage.mbt
- simplifies the implementation
- add a test for empty case
> simplify(coverage)

- builtin/array.mbt
- builtin/arrayview.mbt
- builtin/intrinsics.mbt
- builtin/iter.mbt
- builtin/linked_hash_map.mbt
- builtin/pkg.generated.mbti
- builtin/uninitialized_array.mbt
- bytes/pkg.generated.mbti
- bytes/view.mbt
- deque/deque.mbt
- deque/pkg.generated.mbti
- hashmap/hashmap.mbt
- hashmap/pkg.generated.mbti
- sorted_map/README.mbt.md
- sorted_map/map.mbt
- sorted_map/pkg.generated.mbti
> refactor: rename `op_set` to `set`

- array/fixedarray.mbt
> perf: add #locals to FixedArray::makei

- math/trig.mbt
- math/trig_test.mbt
Math.atan2f calculation in quadrant II is wrong.
> fix: resolve atan2f bug

- builtin/double_to_int64_js.mbt
- builtin/int64_js.mbt
- builtin/int64_test.mbt
Thanks @zxch3n to report that case.
> fix double to int64
